### ISSUE TITLE
可以考虑集成databinding

### ISSUE THREAD

**Issue by ysmintor** [JessYanCoding/MVPArms#1]
少了这个可不太好哦！

**Comment by JessYanCoding** [comment]
这个看个人习惯，作为mvp框架我是不可能在里面加databing的，你可以自己增加，按自己的喜好做定制就好，我不上传到jcenter或则maven得原因，就是按自己的使用习惯定制自己合适的框架，以后一个依赖就可以搭建一个项目，少去了复制和麻烦

**Comment by Sum41forever** [comment]
Arms 现在是有MVVM 的demo的了  @xiaobailong24
[MVVMArms - MVVM 与 Android Architecture Components 的最佳实战](https://github.com/xiaobailong24/MVVMArms)
