### ISSUE TITLE
鸿神的autolayout已经停止维护了，这个框架里是不是考虑移除

### ISSUE THREAD

**Issue by lu-xu** [JessYanCoding/MVPArms#100]
不移除的话，是不是也考虑下不要作为默认的实现。毕竟用在生产环境中，可能出现不可预料的结果

**Comment by xiaobailong24** [comment]
autolayout在此框架中是可选的，可以选择不使用，不是强制使用的。

**Comment by JessYanCoding** [comment]
不声明 **meta-data** 框架就不会使用 **Autolayout** 后期会考虑移除

**Comment by lu-xu** [comment]
明白了
