### ISSUE TITLE
FragmentDelegate没有执行？

### ISSUE THREAD

**Issue by yuqinyi** [JessYanCoding/MVPArms#101]
FragmentDelegateImpl没有执行？Fragment的初始化都没有走是什么原因？

**Comment by JessYanCoding** [comment]
详细描述

**Comment by xiaobailong24** [comment]
@yuqinyi Fragment的使用可参考：
https://github.com/xiaobailong24/MVPArms_Fragment

**Comment by yuqinyi** [comment]
我有个需求是在MainActivity里加载几个Fragment。我用ViewPager + TabLayout来实现。
arms里的BaseFragment是继承RXFragment的，无法使用FragmentManager加载Fragment。

**Comment by JessYanCoding** [comment]
你这么描述的话无法定位问题,更无法解决问题,建议你看看上面的链接

**Comment by xiaobailong24** [comment]
@yuqinyi 是你使用的不对吧。
1. 如果是嵌套fragment的话，可能需要getChildFragmentManager()；
2. arms 里 BaseFragment 继承的 RXFragment，是继承 android.support.v4.app.Fragment，可以用FragmentManager来加载啊

**Comment by yuqinyi** [comment]
我贴一下我的代码。错误是在MyFragmentPagerAdapter的33行。

//----这是Activity类，在这里加载Fragment---------------------------------


package com.yuqinyidev.android.azaz.main.mvp.ui.activity;

import android.support.design.widget.TabLayout;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;

import com.tbruyelle.rxpermissions2.RxPermissions;
import com.yuqinyidev.android.azaz.R;
import com.yuqinyidev.android.azaz.demo.mvp.presenter.UserPresenter;
import com.yuqinyidev.android.azaz.main.mvp.ui.adapter.MyFragmentPagerAdapter;
import com.yuqinyidev.android.framework.base.BaseActivity;
import com.yuqinyidev.android.framework.di.component.AppComponent;
import com.yuqinyidev.android.framework.widget.NoScrollViewPager;

import butterknife.BindView;

public class MainMenuActivity extends BaseActivity {
    private MyFragmentPagerAdapter myFragmentPagerAdapter;

    private TabLayout.Tab one;
    private TabLayout.Tab two;
    private TabLayout.Tab three;
    private TabLayout.Tab four;

    @BindView(R.id.main_menu_view_pager)
    NoScrollViewPager mViewPager;

    @BindView(R.id.main_menu_tab_layout)
    TabLayout mTabLayout;

    @Override
    public void setupActivityComponent(AppComponent appComponent) {
    }

    @Override
    public int initView(Bundle savedInstanceState) {
        return R.layout.act_main_menu;
    }

    @Override
    public void initData(Bundle savedInstanceState) { // 我在这里加载Fragment
        myFragmentPagerAdapter = new MyFragmentPagerAdapter(getSupportFragmentManager());
        mViewPager.setEnableScroll(true);
        mViewPager.setAdapter(myFragmentPagerAdapter);

        mTabLayout.setupWithViewPager(mViewPager);

        one = mTabLayout.getTabAt(0);
        two = mTabLayout.getTabAt(1);
        three = mTabLayout.getTabAt(2);
        four = mTabLayout.getTabAt(3);

        one.setIcon(R.drawable.ic_home_black_24dp);
        two.setIcon(R.drawable.ic_dashboard_black_24dp);
        three.setIcon(R.drawable.ic_notifications_black_24dp);
        four.setIcon(R.drawable.ic_mine_black_24dp);
    }
}

//----这是适配器类，继承android.support.v4.app.FragmentPagerAdapter---------------------------------

import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentManager;
import android.support.v4.app.FragmentPagerAdapter;

import com.yuqinyidev.android.azaz.main.mvp.ui.fragment.FragmentMainDiscover;
import com.yuqinyidev.android.azaz.main.mvp.ui.fragment.FragmentMainHome;
import com.yuqinyidev.android.azaz.main.mvp.ui.fragment.FragmentMainMine;
import com.yuqinyidev.android.azaz.main.mvp.ui.fragment.FragmentMainNotice;

public class MyFragmentPagerAdapter extends FragmentPagerAdapter {
    private String[] mTitles = new String[]{"首页", "发现", "通知", "我的"};

    public MyFragmentPagerAdapter(FragmentManager fragmentManager) {
        super(fragmentManager);
    }

    @Override
    public Fragment getItem(int position) { // 返回类型是android.support.v4.app.Fragment
        switch (position) {
            case 1:
                return new FragmentMainDiscover();
            case 2:
                return new FragmentMainNotice();
            case 3:
                return new FragmentMainMine();
        }
        return new FragmentMainHome(); // 这一行报错，Error:(33, 16) 错误: 不兼容的类型: FragmentMainHome无法转换为Fragment
    }
//----下面是FragmentMainHome类-----------------------------------
里面的方法一个都没走。

import android.content.Intent;
import android.os.Bundle;
import android.support.v7.widget.GridLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.tbruyelle.rxpermissions2.RxPermissions;
import com.yuqinyidev.android.azaz.R;
import com.yuqinyidev.android.azaz.main.di.component.DaggerMainMenuComponent;
import com.yuqinyidev.android.azaz.main.di.module.MainMenuModule;
import com.yuqinyidev.android.azaz.main.mvp.contract.MainMenuContract;
import com.yuqinyidev.android.azaz.main.mvp.presenter.MainMenuPresenter;
import com.yuqinyidev.android.framework.base.App;
import com.yuqinyidev.android.framework.base.BaseFragment;
import com.yuqinyidev.android.framework.base.DefaultAdapter;
import com.yuqinyidev.android.framework.di.component.AppComponent;
import com.yuqinyidev.android.framework.utils.UiUtils;

import butterknife.BindView;
import timber.log.Timber;

/**
 * Created by RDX64 on 2017/6/29.
 */

public class FragmentMainHome extends BaseFragment<MainMenuPresenter> implements MainMenuContract.View {
    private RxPermissions mRxPermissions;

    @BindView(R.id.recycler_view)
    RecyclerView mRecyclerView;

    @Override
    public void setupFragmentComponent(AppComponent appComponent) {
    }

    @Override
    public View initView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        return inflater.inflate(R.layout.fragment_main_home, container, false);
    }

    @Override
    public void initData(Bundle savedInstanceState) {
        this.mRxPermissions = new RxPermissions(getActivity());
        DaggerMainMenuComponent
                .builder()
                .appComponent(((App) getActivity().getApplicationContext()).getAppComponent())
                .mainMenuModule(new MainMenuModule(this))
                .build()
                .inject(this);
        mPresenter.requestAppItems(true);
    }

    @Override
    public void setData(Object data) {
        Timber.tag(TAG).w("setData");
    }

    @Override
    public void showLoading() {
        Timber.tag(TAG).w("showLoading");
    }

    @Override
    public void hideLoading() {
        Timber.tag(TAG).w("hideLoading");
    }

    @Override
    public void showMessage(String message) {
        UiUtils.snackbarText(message);
    }

    @Override
    public void launchActivity(Intent intent) {
        Timber.tag(TAG).w("launchActivity");
    }

    @Override
    public void killMyself() {
        Timber.tag(TAG).w("killMyself");
        getActivity().finish();
    }

    @Override
    public void setAdapter(DefaultAdapter adapter) {
        mRecyclerView.setAdapter(adapter);
        initRecycleView();
    }

    @Override
    public RxPermissions getRxPermissions() {
        return mRxPermissions;
    }

    private void initRecycleView() {
        UiUtils.configRecycleView(mRecyclerView, new GridLayoutManager(getActivity(), 5));
    }
}

**Comment by yuqinyi** [comment]
我看了下源码，RxFragment确实是继承的android.app.Fragment。


import android.app.Fragment;
import android.os.Bundle;
import android.support.annotation.CallSuper;
import android.support.annotation.CheckResult;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.view.View;
import com.trello.rxlifecycle2.LifecycleProvider;
import com.trello.rxlifecycle2.LifecycleTransformer;
import com.trello.rxlifecycle2.RxLifecycle;
import com.trello.rxlifecycle2.android.FragmentEvent;
import com.trello.rxlifecycle2.android.RxLifecycleAndroid;
import io.reactivex.Observable;
import io.reactivex.subjects.BehaviorSubject;

public abstract class RxFragment extends Fragment implements LifecycleProvider<FragmentEvent> {

**Comment by xiaobailong24** [comment]
@yuqinyi 建议你先看一下这个：
https://github.com/xiaobailong24/MVPArms_Fragment
可以使用 newInstance 静态方法获得 Fragment 的实例。

**Comment by YYYQYYY** [comment]
终于弄清楚了，是我的锅。
为了学习框架，我自己把整个框架重新敲了一遍。。。
import com.trello.rxlifecycle2.components.RxFragment;
BaseFragment的包引入弄错了，应该是
import com.trello.rxlifecycle2.components.support.RxFragment;
才对。
谢谢 @JessYanCoding 和 @xiaobailong24 两位大神不嫌麻烦的指点!~!~!~
拜谢！~

**Comment by xiaobailong24** [comment]
弄明白就好！😜😜

**Comment by JessYanCoding** [comment]
@YYYQYYY  ...,你和上面的账号是同一个人吧
