### ISSUE TITLE
ImageLoader切换图片库的问题

### ISSUE THREAD

**Issue by AvatarQing** [JessYanCoding/MVPArms#102]
从Glide切换到Picasso，给ImageLoader设置PicassoImageLoaderStrategy，所用泛型是PicassoImageConfig，之前GlideImageLoaderStrategy所用的泛型是GlideImageConfig，这么一更换，所有调用ImageLoader.loadImage()地方传的GlideImageConfig都要一个个手动改为PicassoImageConfig吧，不然只设置新的Strategy会出现ImageConfig的类型转换错误，这个ImageLoader还并不能做到无缝切换吧

**Comment by JessYanCoding** [comment]
GlideImageConfig 你继续使用,就可以了

**Comment by JessYanCoding** [comment]
GlideImageConfig 重命名为 PicassoImageConfig,就可以了,里面是 **Builder** 模式,里面的参数随意扩展, 名字并不重要

**Comment by AvatarQing** [comment]
如果在项目中途要无缝切换图片库，ImageConfig应该不能有图片库里特有的类，如Target、BitmapTransformation，否则更换图片库后这些调用的地方都要改吧

**Comment by JessYanCoding** [comment]
你仔细想想,这个是无法避免的,你如果不想调用端接触任何与三方库特有的属性,那你必须要有一个中间类,比如说在 GlideImageConfig 中定义一个,int,然后定义好规则,1是什么意思,2是什么意思,switch(int),任何对图片处理的操作,你都必须在这里面预先定义好,这样外部只用传基础属性,替换框架也只用修改这个中间类,这样就能完全的无痛替换,只是在写的时候必须预先定义很多操作

**Comment by JessYanCoding** [comment]
但是这样也是有代价的比如 BitmapTransformation 外部可能会有10种,那你必须在这中间类你们预先定义好10种不同的 BitmapTransformation ,比如 case 0 : new BitmapTransformationA, case 1 : new BitmapTransformationB,随着功能越大,类也会越来越复杂
