### ISSUE TITLE
dagger2 初始化 编译不通过 ，根据前面提到的issues 注释掉 错误代码 还是无法编译.报错内容给您截图，有空能看看嘛

### ISSUE THREAD

**Issue by luocaca** [JessYanCoding/MVPArms#105]
![image](https://user-images.githubusercontent.com/20178161/28001485-6ba2a882-655f-11e7-86f8-272d23c88037.png)

**Comment by xiaobailong24** [comment]
@luocaca

**Comment by luocaca** [comment]
对的。我是直接clone，
将 gradle 改成最新的  ，
使用 android studio canary 5 版本  
修改了gradle   classpath 'com.android.tools.build:gradle:3.0.0-alpha5'


会不会是不兼容 android studio 3.0 
我也clone 了您的 wiki里面说明的一个demo 
《ganamrs》

查看了  apt 中 component 已经自动生成了，。还是会报错



![upload](https://user-images.githubusercontent.com/20178161/28005149-b166067c-657b-11e7-8785-97cb1e8b6f96.png)

**Comment by JessYanCoding** [comment]
框架不会保证在非正式版上运行正常,你将 **Android Studio** 和 **Gradle** 改回最新的正式版 **v2.3.3** ,如果你执意要用 **Canary** 版本,请自行解决以上问题

**Comment by luocaca** [comment]
ok 了 ，切到android 2.3 就可以正常运行。
