### ISSUE TITLE
BaseActivity

### ISSUE THREAD

**Issue by taojin1207** [JessYanCoding/MVPArms#109]
您好：我通过Gradle依赖方式，引入MVPArms，这里的BaseActivity里面没有ButterKnife绑定布局的代码
![image](https://user-images.githubusercontent.com/15828658/28152155-88b5a374-67d1-11e7-9527-290e187f2820.png)
但是下载到本地项目里的arms库的BaseActivity却是有这样的操作
![image](https://user-images.githubusercontent.com/15828658/28152186-b7fb645c-67d1-11e7-8909-a7fa009eb46a.png)
请问Gradle依赖方式是不是ButterKnife需要自己写绑定布局的操作。

**Comment by JessYanCoding** [comment]
这个你不需要担心,至于需不需要,自己使用 **ButterKnife.bind(Activity)** ,你自己试试不写这句话 **ButterKnife** 是否生效就知道了,你最后会发现,不管是 **Gradle** 依赖的方式,和下载的方式都不用自己绑定,就可以使用 **ButterKnife** ,这时你会觉得 **Gradle** 依赖的方式没有写 **ButterKnife.bind(Activity)** 都可以生效,是不是有什么黑魔法,对的 **MVPArms** 就是这么神奇

**Comment by taojin1207** [comment]
我是不是做了什么错误的操作，我不调用ButterKnife.bind(Activity)给我报了NUll指针，就是控件找不到。

**Comment by JessYanCoding** [comment]
每个需要使用 **Butterknife** 的 Module 都必须在自己的build.gradle annotationProcessor com.jakewharton:butterknife-compiler:8.6.0     ,先不要怀疑我的黑魔法,我猜你肯定没有加这个

**Comment by JessYanCoding** [comment]
请认真看 **Wiki** 和 **Demo**

**Comment by taojin1207** [comment]
不不不，我从未怀疑你的黑魔法，我是说我是做了什么错误的操作，我通过Gradle方式引入compile 'me.jessyan:arms:2.1.0'你这个里面不是已经集成了那些jar包吗，还需要在Moudle里在引入一下所需要的jar包吗？

**Comment by JessYanCoding** [comment]
我上面已经说了每个需要使用 Butterknife 的 Module 都必须在自己的build.gradle 中加上 annotationProcessor com.jakewharton:butterknife-compiler:8.6.0

**Comment by taojin1207** [comment]
Sorry！我加上了就可以了，谢谢啦。小弟还有不解，我看了你arms库里的build.gradle文件。里面已经加入了ButterKnife啊，我Gradle依赖你的包，那我不是等于已经集成进去了，为什么还要在单独声明下。

**Comment by JessYanCoding** [comment]
你看我 arms库 只是引入了她的包,但是 annotationProcessor 插件我没引入,而且 annotationProcessor 插件必须在,每个需要使用的 Module 中引入,哪怕我在 arms 中引入了 annotationProcessor 插件,你还是必须在你自己的 app Module,中引入 annotationProcessor 插件,没有为什么这就是规则,你可能没这方面的经验

**Comment by taojin1207** [comment]
谢谢啦，我自己在琢磨琢磨，目前我对这方面经验确实不足，大哥的简书，小弟已关注，希望能取点经验。

**Comment by xiaobailong24** [comment]
@taojin1207 你的问题是：gradle远程依赖和直接clone看到的BaseActivity不一样，因为后来更新了arms的生命周期，已经提交到github，但是还没更新到远程依赖库。

**Comment by JessYanCoding** [comment]
好的,共同进步

**Comment by taojin1207** [comment]
@xiaobailong24 是的是你说的这个问题，谢谢啦。感激！
