### ISSUE TITLE
一个Activity重用多个Presenter的话，需要实现每个Presenter的Contract.View吗

### ISSUE THREAD

**Issue by yeyueduxing** [JessYanCoding/MVPArms#111]
看了Presenter和Module的实现，都是有Contract.View的参数
@ActivityScope
@Component(modules = {BaiduModule.class, UserModule.class}, dependencies = AppComponent.class)
public interface BaiduComponent {
    void inject(LoginActivity activity);
}
类似这种注入两个Module,在使用的时候，Module初始化的时候都需要Contract.View参数
 DaggerBaiduComponent //如找不到该类,请编译一下项目
                .builder()
                .appComponent(appComponent)
                .baiduModule(new BaiduModule(this))
                .userModule(new UserModule(this))
                .build()
                .inject(this);
这样子的话，重用多个Presenter的话，Activity需要实现每个Presenter的Contract.View吗

**Comment by JessYanCoding** [comment]
嗯,presenter  想重用的话, Presenter  里面应该都是可以共用的业务逻辑,不应该含有太多私有的业务逻辑,这样会导致 Presenter 重用时,Activity  被迫实现过多多余的接口,看看我写的一篇文章吧 http://www.jianshu.com/p/ac51c9b88af3

**Comment by yeyueduxing** [comment]
嗯，这些文章都看了。原本我还以为使用注入的话，Presenter可以和View解耦。这样子的话，的确只能重用公共的那个业务逻辑了

**Comment by JessYanCoding** [comment]
**Presenter** 依赖于 **View** 接口,所以只能和具体实现类解耦,和 **View** 接口还是会耦合,把每个 **Presenter** 的功能都限制到单一职责的范围,一个 **Presenter** 不要涉及太多不同功能的业务逻辑,这样就重用的时候就会好很多

**Comment by yeyueduxing** [comment]
嗯，好的，谢谢啊
