### ISSUE TITLE
targetCompatibility = '1.8' sourceCompatibility = '1.8'已改 为什么还报这个错

### ISSUE THREAD

**Issue by zhouxxiaolong** [JessYanCoding/MVPArms#114]
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.

**Comment by JessYanCoding** [comment]
google下

**Comment by zhouxxiaolong** [comment]
不是java8的问题 是引入一个google-format的jar包的文件夹名字太长导致的 估计

**Comment by JessYanCoding** [comment]
嗯嗯

**Comment by zhouxxiaolong** [comment]
那咋办？

**Comment by JessYanCoding** [comment]
这个和你自己的环境有关,只有你自己解决,我只能保证我Demo运行没问题

**Comment by MarsToken** [comment]
主项目里你有没添加compile 'net.orfjackal.retrolambda:retrolambda:2.5.1'这个依赖，如果有的话把他删了就好
