### ISSUE TITLE
Rxutils

### ISSUE THREAD

**Issue by taojin1207** [JessYanCoding/MVPArms#115]
我复制你的demo里的这个类，但是我的有个方法直接报错，让我强转成返回泛型
![image](https://user-images.githubusercontent.com/15828658/28708467-ea33ef96-73ae-11e7-9175-56d9e0ae09cf.png)
这个我方法都是一样的，怎么会报错呢
你的方法里直接返回的就是一个泛型，但我的是个object，不懂为啥
![image](https://user-images.githubusercontent.com/15828658/28708562-47848f8e-73af-11e7-8ae9-f1c60cc1fe81.png)

**Comment by kandra777** [comment]
你是不是把lamda的支持给注释了?

**Comment by xiaobailong24** [comment]
@taojin1207 把jdk版本改为java8

**Comment by taojin1207** [comment]
@xiaobailong24  只把jdk改为java8就可以了吗，我设置的不支持lamda

**Comment by taojin1207** [comment]
@xiaobailong24 这个设置实在那个里面 我试一下咯，非常感谢

**Comment by xiaobailong24** [comment]
@taojin1207 可以的，只要你不用lamda
