### ISSUE TITLE
刚看了下大大的开眼视频是基于这个架构的，可以写入README嘛

### ISSUE THREAD

**Issue by jp1017** [JessYanCoding/MVPArms#12]
这样，学习起来会更快了

太棒了 :smile: :+1: :100: :smile_cat:

**Comment by jp1017** [comment]
:disappointed: 刚看了下，貌似还有一些路要走，哈哈

**Comment by JessYanCoding** [comment]
之前其实在readme里面有传送门的，这项目很早就创建了，但是一直没时间写，只有写出来才好宣传，一个完整的项目作为demo的更好学习，后续写出了的话，我会贴到readme里的

**Comment by WooYu** [comment]
开眼视频是什么？期待有个完整的项目学习下。

**Comment by JessYanCoding** [comment]
好的,开眼是我之前想写的一个完整项目,因为时间问题,一只没完成，最近可能会慢慢开始写
