### ISSUE TITLE
建议将eventbus升级到3.0

### ISSUE THREAD

**Issue by trenail** [JessYanCoding/MVPArms#122]
建议将eventbus升级到 3.0,
eventbus 1.0在某些设备上出现ClassNotDefFoundError

**Comment by xiaobailong24** [comment]
@trenail 框架里使用的是 AndroidEentBus: https://github.com/hehonghui/AndroidEventBus ;
不是EventBus: https://github.com/greenrobot/EventBus。

**Comment by JessYanCoding** [comment]
导致 **java.lang.NoClassDefFoundError** 的原因很有可能是因为 **64k** 导致的,建议试试 **MultiDex**
