### ISSUE TITLE
缺东西,跑不起来

### ISSUE THREAD

**Issue by gslovemy** [JessYanCoding/MVPArms#123]
![image](https://user-images.githubusercontent.com/13553809/29017360-1111d290-7b89-11e7-91f6-e5ea6541a15d.png)

![image](https://user-images.githubusercontent.com/13553809/29017368-1c11a724-7b89-11e7-9a98-e5bb18d7e0c6.png)
![image](https://user-images.githubusercontent.com/13553809/29017383-23b90df0-7b89-11e7-90bd-18d044b7e4d4.png)

**Comment by xiaobailong24** [comment]
@gslovemy make 或者 rebuild 一下

**Comment by JessYanCoding** [comment]
@gslovemy 请你更新到最新版本,你这个是很老的版本了

**Comment by gslovemy** [comment]
@JessYanCoding  我直接从你的github下载的,不是最新的吗?最新的地址在什么地方?

**Comment by JessYanCoding** [comment]
哦哦,抱歉看错了

**Comment by gslovemy** [comment]
![image](https://user-images.githubusercontent.com/13553809/29053534-41e457fe-7c23-11e7-9785-792c9c7446c8.png)

我看过不是引用的问题,怎么处理这个问题,我看的mvparms

**Comment by JessYanCoding** [comment]
静态编译时的错误一般很好解决,你嫌麻烦就远程依赖吧

**Comment by gslovemy** [comment]
DaggerAppComponent 像这个类就没有,我怎么解决,不想远程依赖,想看看源码,你可以自己down下来看看,有什么问题,解决一下

**Comment by gslovemy** [comment]
@xiaobailong24  这个重新make 跟build就跑步起来,本身项目就少东西呀

**Comment by JessYanCoding** [comment]
我不用 Download ,这个本就是我传上去了,这个是类是 **Dagger** 自己生成的,只要你不是 Android studio 3.0以上一般都可以编译过

**Comment by xiaobailong24** [comment]
可以把Sdk改为25.3.试试1

**Comment by gslovemy** [comment]
我用的是2.3.2的,为什么不行

**Comment by gslovemy** [comment]
@xiaobailong24  完美解决,谢谢
