### ISSUE TITLE
java.lang.NoClassDefFoundError: dagger/Multibindings

### ISSUE THREAD

**Issue by chinaAdroidBoy** [JessYanCoding/MVPArms#125]
通过gradle的方式配置，出现这个错误？？？
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.NoClassDefFoundError: dagger/Multibindings

**Comment by JessYanCoding** [comment]
Demo？

**Comment by chinaAdroidBoy** [comment]
现在没问题了，貌似是config配置里的一些版本问题，我直接复制demo里最新的配置了

**Comment by JessYanCoding** [comment]
好的

**Comment by JessYanCoding** [comment]
你应该是没更新 config.gradle,导致 App 用的是旧版 Dagger ,而 Arms 用的却是新版而报错
