### ISSUE TITLE
BaseFragement 无Butterknife和mView对象

### ISSUE THREAD

**Issue by coolBreezes** [JessYanCoding/MVPArms#126]
请问为什么不在BaseFragament中使用butterknift
和创建view对象呢，像这样
 @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        mInflater = inflater;
        if (null == rootView){
            rootView = inflater.inflate(getLayoutId(),null);
            ButterKnife.bind(this,rootView);
        }else {
            ViewGroup viewGroup = (ViewGroup) rootView.getParent();
            if (null != viewGroup){
                viewGroup.removeView(rootView);
            }
        }
        return rootView;
    }

**Comment by JessYanCoding** [comment]
因为我在其他地方已经做了,你使用框架, 你不用担心 bind 的问题, butterknife  是可以正常使用的

**Comment by coolBreezes** [comment]
那请问一下，您是在哪里对butterknife进行绑定和回收的呢

**Comment by luocaca** [comment]
FragmentDelegateImpl   里面代理了 绑定。。
![image](https://user-images.githubusercontent.com/20178161/29099669-66fd76e0-7cd9-11e7-970a-355731fe3401.png)


你直接ctrl + alt + F 搜索一下 ButterKnife.bind  关键字就出来了

**Comment by coolBreezes** [comment]
恩，好的，太感谢了o(*￣︶￣*)o

**Comment by Sum41forever** [comment]
[Fragment在框架中的使用，ButterKnife的绑定](https://github.com/JessYanCoding/MVPArms/issues/181)

**Comment by Sum41forever** [comment]
详细解答在这里，把相同的问题定位在一起
[Fragment在框架中的使用，ButterKnife的绑定](https://github.com/JessYanCoding/MVPArms/issues/174)
