### ISSUE TITLE
为什么BaseApplication不继承.MultiDexApplication

### ISSUE THREAD

**Issue by coolBreezes** [JessYanCoding/MVPArms#127]
请问依赖的jar包这么多，为什么BaseApplication不继承.MultiDexApplication
防止方法数上限的问题呢

**Comment by JessYanCoding** [comment]
自己看 GlobalConfiguration#injectActivityLifecycle() 中的 attachBaseContext()  ,你需要并不代表别人需要,Arms 不会臆想别人是否会需要某个功能而去帮他提前完成这个工作,而是提前提供扩展方式协助他完成这个工作

**Comment by JessYanCoding** [comment]
Arms 现在又上千个项目,再使用,每个人有不同的需求,如果我今天将 BaseApplication 继承了  MultiDexApplication,那明天就有人提同样的 Issues 让我去掉继承关系,和作品一样,始终无法满足所有人的需求,我只会提供扩展的方式,给需求的人,而不是帮这部分人去实现

**Comment by coolBreezes** [comment]
恩恩，了解了，请问mvparms有没有交流的qq群呢，或者别的交流群呢

**Comment by JessYanCoding** [comment]
QQ群 一直挂到 README 上的哈,  301733278
