### ISSUE TITLE
关于返回的数据

### ISSUE THREAD

**Issue by sylarzhang** [JessYanCoding/MVPArms#128]
这个网络请求返回的数据要是是String应该怎么改，貌似是这个框架返回的是json。。。

**Comment by JessYanCoding** [comment]
百度 Retrofit 的用法,Arms 并没有自己封装网络请求,所以关于网络请求的教学文章,请自行向 Retrofit  学习,这里就暂且不讨论 Retrofit 的基础用法,随便一篇文章都讲的比我优秀

**Comment by sylarzhang** [comment]
这么晚的，辛苦大大了。感谢。
