### ISSUE TITLE
请问在dialog里面的网络需要怎么处理

### ISSUE THREAD

**Issue by ozy20** [JessYanCoding/MVPArms#131]
您好。请问在dialog里面要是需要请求网络要怎么处理呢。是单独为dialog创建一个P层？还是直接在dialog里面请求？
BaseApplication application = (BaseApplication) mContext.getApplicationContext();
        UserService userService = application.getAppComponent().repositoryManager().obtainRetrofitService(UserService.class);
        userService.getUsers()...

**Comment by JessYanCoding** [comment]
以我的习惯,我是会的

**Comment by ozy20** [comment]
好的。多谢解惑
