### ISSUE TITLE
GlobalConfigModule中的provideGlobalHttpHandler();

### ISSUE THREAD

**Issue by zhouhaoo** [JessYanCoding/MVPArms#132]
### 返回值

大神这个框架看的很有学习作用，看到这里，是不是这个做一下判断会不会更好。
![image](https://user-images.githubusercontent.com/19631075/29646194-856e8f1a-88b4-11e7-89f2-2d870c5608b5.png)

**Comment by JessYanCoding** [comment]
可能你没看懂,看到了上面加了一个 @Nullable 了吗,意思告诉 Dagger 这里可以返回 Null 对象,这里还真不是我疏忽,而是我故意这样设计的,使用者如果没有实现这个接口的需求,我没必要让拦截器每次调用一个空实现

**Comment by zhouhaoo** [comment]
谢谢，我明白了。
