### ISSUE TITLE
恢复任务

### ISSUE THREAD

**Issue by taojin1207** [JessYanCoding/MVPArms#133]
我想问下，我用Rxutils.bindLife后,每次跳转下一个页面，之前的页面会停止正在执行的网络任务，但是当我在回到该页面时，任务没有重新执行，请问下该怎么去处理。

**Comment by JessYanCoding** [comment]
这个是和业务逻辑有关,建议你自己处理,思路可以给你,无非就是停止时将任务加入一个任务栈,回来时恢复即可,也可以直接 **bindUntilEvent(DESTROY)** ,跳转的时候不让任务停止,细节就别问我了,自己想
