### ISSUE TITLE
返回上一个页面响应延迟

### ISSUE THREAD

**Issue by YubiwaStar** [JessYanCoding/MVPArms#135]
有时候返回上一个页面onResume到onStop的时间耗时 几百毫秒到 1s
ui.task.task.TaskActivity:onKeyDown=17时:31分:31秒:332毫秒
ui.task.task.TaskActivity:onPause=17时:31分:31秒:397毫秒
ui.mainpage.main.MainActivity:onRestart=17时:31分:31秒:412毫秒
ui.mainpage.main.MainActivity:onStart=17时:31分:31秒:419毫秒
ui.mainpage.main.MainActivity:onResume=17时:31分:31秒:440毫秒
ui.task.task.TaskActivity:onStop=17时:31分:31秒:891毫秒
ui.task.task.TaskActivity:onDestroy=17时:31分:32秒:013毫秒

**Comment by JessYanCoding** [comment]
这个和框架有关系吗

**Comment by JessYanCoding** [comment]
刚测试了下,不管是打开一个新的页面还是返回上一个页面,所执行的生命周期加起来都是在几十毫秒以内,所以你说的这个问题是并不是框架导致的

**Comment by YubiwaStar** [comment]
但是 我贴出来的这个生命周期 是专门用来的测试这个延迟项目 除了框架 没有任何其他的代码呢

**Comment by JessYanCoding** [comment]
我建议你直接用 Demo 测试,我有了多款手机测试,都没有这类问题,也没收到过此类问题的其他 Issues

**Comment by YubiwaStar** [comment]
08-28 13:54:36.057 21545-21545/me.jessyan.mvparms.demo D/TimeActivity: testbactivity.TestBActivityActivity:onKeyDown=13时:54分:36秒:057毫秒
testbactivity.TestBActivityActivity:onPause=13时:54分:36秒:060毫秒
testactivity.TestActivityActivity:onRestart=13时:54分:36秒:064毫秒
testactivity.TestActivityActivity:onStart=13时:54分:36秒:065毫秒
testactivity.TestActivityActivity:onResume=13时:54分:36秒:067毫秒
testbactivity.TestBActivityActivity:onStop=13时:54分:36秒:435毫秒
testbactivity.TestBActivityActivity:onDestroy=13时:54分:36秒:436毫秒
还是出现了这个问题 这次用的是最新的框架···我都有点怀疑人生了

**Comment by JessYanCoding** [comment]
那你新建一个新的项目,不导入框架,看会不会出现这个问题,再试试,导入框架,在 **AndroidManifest** 中不生命 **BaseApplication** 看会不会出现这个问题

**Comment by xiaobailong24** [comment]
@YubiwaStar 是不是过渡动画引起的？

**Comment by YubiwaStar** [comment]
不知道你统计生命周期的判断依据是什么
我关注的是从当前页面onResume到返回页面onStop的时间 现在看不用框架是在280毫秒
用了框架大约会多了100毫秒


//不导入框架 
08-28 14:36:16.814 12962-12962/com.example.star.timedemo D/TimeActivity: TestCActivity:onKeyDown=14时:36分:16秒:814毫秒
TestCActivity:onPause=14时:36分:16秒:817毫秒
TestBActivity:onRestart=14时:36分:16秒:822毫秒
 TestBActivity:onStart=14时:36分:16秒:823毫秒
TestBActivity:onResume=14时:36分:16秒:824毫秒
TestCActivity:onStop=14时:36分:17秒:106毫秒
TestCActivity:onDestroy=14时:36分:17秒:107毫秒

//导入框架 不集成
08-28 14:57:32.776 17855-17855/me.jessyan.mvparms.demo D/TimeActivity: com.example.star.timedemo.TestCActivity:onKeyDown=14时:57分:32秒:776毫秒
com.example.star.timedemo.TestCActivity:onPause=14时:57分:32秒:779毫秒
com.example.star.timedemo.TestBActivity:onRestart=14时:57分:32秒:785毫秒
com.example.star.timedemo.TestBActivity:onStart=14时:57分:32秒:786毫秒
com.example.star.timedemo.TestBActivity:onResume=14时:57分:32秒:786毫秒
com.example.star.timedemo.TestCActivity:onStop=14时:57分:33秒:068毫秒

**Comment by YubiwaStar** [comment]
嗯 我的app用的时候 能感觉到明显的卡顿 卡顿结束后才开始执行切换动画

**Comment by YubiwaStar** [comment]
我的app用的时候 能感觉到明显的卡顿 卡顿结束后才开始执行切换动画

**Comment by JessYanCoding** [comment]
嗯,按你提供的数据:
1.不导入框架使用: 1107 - 814 = 293毫秒
2.导入框架不集成 **BaseApplication** 使用: 1068 -776 = 292 毫秒
3.完全集成框架使用: 436 - 057 = 379 毫秒

得出结论: 
前面两个属于正常情况所以耗费时间几乎一致
可以确定加入框架后确实耗时会多,但也不超过 100 毫秒(379 - 292 = 87 毫秒),耗时主要在 **onResume** 和 **onStop** 之间

**Comment by JessYanCoding** [comment]
具体 onResume 和 onStop 之间做了什么,现在暂时还不清楚,但是和你说的 1S ,还是相差甚远,让你在 **Demo** 上作实验的目的就是为了屏蔽,一些自己 **App** 业务逻辑和其他框架以及开发环境上等带来的卡顿,这样最纯净

**Comment by YubiwaStar** [comment]
嗯 现在确定框架是有100毫秒左右的延迟 我认为是可以接受的。我的app延迟一般在400毫秒左右，只是偶尔会到达1s，这个时候就会有明显的卡顿。我再考虑下其他问题。

**Comment by JessYanCoding** [comment]
AActivity:onPause=1277
BActivity:onStart=1277
BActivity:onResume=1282
AActivity:onStop=1317
AActivity:onDestroy=1319

我又试了几次,使用的是 **SystemClock.currentThreadTimeMillis()** 获取的时间,整个过程加起来,都很少超过50毫秒,所以我也很郁闷为什么你就要几百毫秒,而且我还是在我公司的项目测试的,还不是 **Demo** ,我的项目还不小,组件化项目,4个核心模块,2个公共模块,框架也只是有30个以上

**Comment by JessYanCoding** [comment]
我唯一的能想到的就是设备问题,你不会用红米测试的吧？

**Comment by JessYanCoding** [comment]
AActivity:onPause=1843
BActivity:onCreate=1848
BActivity:onStart=1877
BActivity:onResume=1882
AActivity:onStop=1920

这次新建一个页面,多调用了一个 **onCreate** ,到上一个页面 ** onStop** 也才(1920 - 1843 = 77) 100 毫秒不到

**Comment by YubiwaStar** [comment]
我用魅蓝测试的之前用的System.currentTimeMillis()) 换成  SystemClock.currentThreadTimeMillis()
 毫秒数马上降下来了···
········无语

**Comment by JessYanCoding** [comment]
那就是 **System.currentTimeMillis()** 在耗时,不是框架的问题

**Comment by xiaobailong24** [comment]
直接看一下 logcat 的时间，不要用 System 里的时间计算
