### ISSUE TITLE
CustomPopupWindow 位置显示不能改变吗

### ISSUE THREAD

**Issue by yyminoz** [JessYanCoding/MVPArms#139]
暴露的show方法 不能改变pop显示的位置吗

**Comment by JessYanCoding** [comment]
他本质就是一个 **PopupWindow** , **PopupWindow** 有的方法他都有,你之前怎么显示,这个就怎么显示

**Comment by JessYanCoding** [comment]
暴露了 **show()** 只实现了显示到中间,需要改变现实位置,自己调用 **PopupWindow** 的 **Api**

**Comment by yyminoz** [comment]
OK 谢谢你

**Comment by JessYanCoding** [comment]
@yyminoz  没事, **Star** 一下就可以了
