### ISSUE TITLE
网络请求session问题 

### ISSUE THREAD

**Issue by StephenCMZ** [JessYanCoding/MVPArms#142]
服务器采用session判定用户的身份，发现每次网络请求session不一样，请问如何保证session一样？

**Comment by JessYanCoding** [comment]
您好,这里只回答框架问题,关于服务器的逻辑问题请咨询你们公司的后台,谢谢

**Comment by StephenCMZ** [comment]
你好，很抱歉没有把问题表达清楚。我的问题是该框架发送网络请求的session每次都不一致，请问如何保证请求的session一致？

**Comment by JessYanCoding** [comment]
框架没有封装 **Session** ,所以 **Session** 是你自己管理的,并且框架是使用的 **Okhttp** 做的网络请求,关于网络的东西,框架只是提供 **Okhttp** , **Retrofit** 给使用者,自己并没有封装,所以这方面的问题和框架关系不大,你应该百度如何使用 **Okhttp** xxxx

**Comment by StephenCMZ** [comment]
谢谢大神！
