### ISSUE TITLE
mPresent is null in fragment

### ISSUE THREAD

**Issue by ericfjl** [JessYanCoding/MVPArms#143]
![image](https://user-images.githubusercontent.com/4636005/30091499-795b4f00-92ec-11e7-8e53-ca47e7a36595.png)
是不是我的配置没有对？麻烦帮忙看看，谢谢

**Comment by JessYanCoding** [comment]
自己打断点测试,参考 https://github.com/lianhuo/Ganamrs ,无非就是自己疏忽造成的错误,自己认真比对

**Comment by JessYanCoding** [comment]
没事重写什么 onCreate 方法,提供的 initData() 不能用吗

**Comment by ericfjl** [comment]
老大威武，一语惊醒梦中人

**Comment by DavikChen** [comment]
initData() 执行两遍 你们没遇到？
