### ISSUE TITLE
initData is not call in fragment if create in xml

### ISSUE THREAD

**Issue by ericfjl** [JessYanCoding/MVPArms#144]
1.  用xml添加的fragment的情况，initData没有调用
`<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.DrawerLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/activity_main"
    android:background="@color/color_ffffff"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <com.xirmei.suwen.mvp.ui.widget.CustomNestedScrollView
        android:id="@+id/scroll_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <RelativeLayout
            android:id="@+id/jieqi_view"
            android:layout_width="fill_parent"
            android:layout_height="fill_parent">

            <RelativeLayout
                android:id="@+id/jieqi_head_all"
                android:layout_width="fill_parent"
                android:layout_height="fill_parent">

                <ImageView
                    android:id="@+id/background_img"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:src="@drawable/jq11_l_heat"
                    android:scaleType="centerCrop"
                    android:layout_alignParentTop="true"
                    android:layout_alignParentStart="true" />
                <include
                    android:id="@+id/circle_menu"

                    layout="@layout/include_cycle"
                    />

                <fragment
                    android:id="@+id/mian_head"
                    android:name="com.xirmei.suwen.mvp.ui.fragment.HeadFragment"
                    android:layout_below="@+id/circle_menu"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent">

                </fragment>

            </RelativeLayout>

            <fragment
                android:id="@+id/mian_body"
                android:name="com.xirmei.suwen.mvp.ui.fragment.BodyFragment"
                android:layout_below="@+id/jieqi_head_all"
                android:layout_marginTop="20dp"
                android:layout_width="match_parent"
                android:layout_height="match_parent">

            </fragment>
        </RelativeLayout>`
2. 在代码中直接添加fragment的情况，initData能调用
`        HeadFragment headFragment = HeadFragment.newInstance(mJieqiDatas.get(startJq));
        BodyFragment bodyFragment = BodyFragment.newInstance(mJieqiDatas.get(startJq));
        FragmentTransaction fragmentTransaction = getSupportFragmentManager().beginTransaction();
        fragmentTransaction.add(R.id.mian_head, headFragment);
        fragmentTransaction.add(R.id.mian_body, bodyFragment);
        fragmentTransaction.commit();`

请问是什么原因呢？

**Comment by JessYanCoding** [comment]
更新到最新版
