### ISSUE TITLE
When is Android studio 3.0 official release?

### ISSUE THREAD

**Issue by TYUpya** [JessYanCoding/MVPArms#146]
When is Android studio 3.0 official release?

I want to use the release version of Android studio 3.0.

**Comment by xiaobailong24** [comment]
When Google release the AS3🤣🤣

**Comment by TYUpya** [comment]
All right. ‼

**Comment by JessYanCoding** [comment]
😂😂😂

**Comment by xiaobailong24** [comment]
@TYUpya but u can look at the below, I have supported AS3:🤣
https://github.com/xiaobailong24/MVVMArms/tree/dev
