### ISSUE TITLE
app的build.gradle中导入框架就报错

### ISSUE THREAD

**Issue by gitgeek4dx** [JessYanCoding/MVPArms#147]
Error:Failed to resolve: com.github.VictorAlbertos.Jolyglot:gson:0.0.3
openFile:E:/Android/jiuqu.app/android/MvpArmsDemo/app/build.gradle"

Error:Failed to resolve: com.android.support:support-v4:26.0.1
Install Repository and sync project openFile:E:/Android/jiuqu.app/android/MvpArmsDemo/app/build.gradle"
Show in Project Structure dialog

Error:Failed to resolve: com.android.support:design:26.0.1

Error:Failed to resolve: com.android.support:appcompat-v7:26.0.1

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/MVPArms/wiki#1.2 复制里面的内容,你如果能认真看 Wiki 就能够节约大家的时间

**Comment by gitgeek4dx** [comment]
我不至于不看wiki就接入，下面这段，我是原封复制的
apply from: "config.gradle" //这里表示引用config.gradle文件
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }//rxcahche 需要 jitpack 仓库
        maven { url "https://maven.google.com" }//Support-library 需要 Google 仓库
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

依然有以下报错，
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

**Comment by xiaobailong24** [comment]
你的module是不是跟arms里的依赖有冲突？仔细检查一下，实在不行新建个新工程试试。

**Comment by Txxyyy** [comment]
我也遇到同样的问题，请问解决了吗？
