### ISSUE TITLE
按键相应问题

### ISSUE THREAD

**Issue by flamenvo** [JessYanCoding/MVPArms#148]
有时点击按钮会报错，提示View清理Focus时空指针异常   偶现问题，但频率较高

**Comment by JessYanCoding** [comment]
用的最新的 Demo 出现的问题?

**Comment by flamenvo** [comment]
@JessYanCoding   使用了框架里的AdapterViewPager,会出现这个问题。我自定义了FragmentStatePagerAdapter，不添加instantiateItem和destroyItem，就好了

**Comment by JessYanCoding** [comment]
ok
