### ISSUE TITLE
add a roate imageView to MVPArms's activity is slow

### ISSUE THREAD

**Issue by ericfjl** [JessYanCoding/MVPArms#149]
我自定义了一个imageView，圆形图片随手移动（MotionEvent.ACTION_MOVE）而旋转，主要代码如下：

```
    @Override
    protected void onDraw(Canvas canvas) {

        int height = this.getHeight();
        int width = this.getWidth();
        centerX = width / 2;
        centerY = height / 2;
        canvas.rotate(mDirection, width / 2, height / 2);
        super.onDraw(canvas);

    }
```
我在android studio 新建一个普通的工程，能够很流畅的旋转图片
在MVPArms（V2.1.5）框架中使用我自定义的imageView 会有卡顿现象，请问是为什么？

**Comment by JessYanCoding** [comment]
**View** 的东西和框架都没有关系,所以也就无法回答

**Comment by ericfjl** [comment]
那为什么我用没有带框架的activity来使用我的View，没有卡顿，在MVPArms框架中就有卡顿呢？
我猜测 框架中有事件在监听，我在不停【onDraw】的时候，会卡住

**Comment by JessYanCoding** [comment]
Android 之提供了全局监听 **Activity** 和 **Fragment** 的生命周期,根本没有提供涉及到 **View** 的全局监听,框架除了 **AndroidAutoLayout** ,也没有封装过一处与 **View** ,有关的封装

**Comment by JessYanCoding** [comment]
你一个普通项目,什么库都不引入,所有环境都初始化的状态,不卡很正常,相对于你之前的业务密集的项目卡很正常,并不能说明框架有什么问题,绘制时我框架都能影响的话,那我框架也已经强大到可以作为测试工具了

**Comment by ericfjl** [comment]
对不起，我错了，我拿MVPArms demo测试了一下，是正常的，说明跟框架没有任何关系，刚开始只是怀疑！

**Comment by JessYanCoding** [comment]
ok
