### ISSUE TITLE
不是BUG，问一下，如何在普通的类中拿到AppManager

### ISSUE THREAD

**Issue by tulongchao** [JessYanCoding/MVPArms#152]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Related Code:
```java
  

```

### Bug Log:
```log


```

**Comment by xiaobailong24** [comment]
@tulongchao **ArmsUtils.java**，如果有Context的话

**Comment by JessYanCoding** [comment]
**ArmsUtils.obtainAppComponentFromContext(Context())** ,非 Bug 或改进建议,建议加群 
 [ ![QQGroup](https://img.shields.io/badge/QQ群-301733278-ff69b4.svg) ](https://shang.qq.com/wpa/qunwpa?idkey=1a5dc5e9b2e40a780522f46877ba243eeb64405d42398643d544d3eec6624917)
