### ISSUE TITLE
谢谢分享。bug反馈。手机横竖屏切换异常

### ISSUE THREAD

**Issue by mavenjan** [JessYanCoding/MVPArms#153]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Related Code:
```java
  

```

### Bug Log:
```log


```

### Others
为监测适配屏幕效果，横竖屏切换时，MVPArms和MVPArt都有以下问题（测试手机：华为 mate 9）：
1.横竖屏切换时，数据都会刷新，用户体验不好
2.横竖屏切换之后，顶部返回操作失效。
学习中，希望demo可以有更多的操作可以体验^-^

**Comment by xiaobailong24** [comment]
@mavenjan 框架并没有做配置改变时数据恢复的工作，这个应该是demo里做的，但是为了demo尽可能简单，这些操作应该是开发者自己适配的。

**Comment by JessYanCoding** [comment]
抱歉, Demo 只是为了展示,框架的基本功能,所以对 Demo 并不会做太多产品以及逻辑上的优化,我的精力主要还是放在框架的迭代中,至于 Demo 这里还有其他人贡献的 [学习Demo](https://github.com/JessYanCoding/MVPArms/blob/master/CONTRIBUTING_APP.md), 如果您对本框架以及用户体验感兴趣,也欢迎用本框架自己写一个 Demo, 提升自己也帮助他人

**Comment by mavenjan** [comment]
好的，明白了

**Comment by JessYanCoding** [comment]
@mavenjan 你说的第二个问题[已修复](https://github.com/JessYanCoding/MVPArms/commit/1cee705d34602425de0c4569757f916d9a742938), 第一个关于用户体验的问题已忽略
