### ISSUE TITLE
网络请求后，如何得到不解析的结果。返回什么就是什么。

### ISSUE THREAD

**Issue by hxlailfh1314** [JessYanCoding/MVPArms#154]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Related Code:
```java
  

```

### Bug Log:
```log


```

### Others
因为项目需求比较特殊。我希望将得到的xml数据，原封不动的返回给我。我试着用  Observable  <字符串> ，但是返回的数据是空的。求指点

**Comment by JessYanCoding** [comment]
自己看[这里](https://github.com/JessYanCoding/MVPArms/issues/150),最重要的是最后一条,最后一句话,这个 **Issues** 并不符合我, 我前面声明的规范, 所以按我规范中所说的解决方案, 直接 **Close**, 你想解决 **Retrofit** 的问题, 请自行百度, 或者加群询问, **Issues** 上不解答此类问题
