### ISSUE TITLE
AndStudio 3.0 Release Issues

### ISSUE THREAD

**Issue by JessYanCoding** [JessYanCoding/MVPArms#159]
已知是 **Dagger** 报错,  可能 **Gradle** 引起的, 你们先各自描述讨论问题把, 后续参考描述解决问题

**Comment by xiaobailong24** [comment]
AS 3 Release 了啦？！！可以出门了，没法体验了

**Comment by JessYanCoding** [comment]
@xiaobailong24 是啊, 升级后还是之前 **Dagger** 的问题, 我这还没升级, 你看你那里有没有解决方案

**Comment by 4what2do** [comment]
C:\Users\Administrator\Desktop\MVPArms-master\arms\src\main\java\com\jess\arms\base\delegate\AppDelegate.java:26: 错误: 找不到符号
import com.jess.arms.di.component.DaggerAppComponent;
                                 ^
  符号:   类 DaggerAppComponent
  位置: 程序包 com.jess.arms.di.component
注: [1] Wrote GeneratedAppGlideModule with: []

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':arms:compileDebugJavaWithJavac'.
> java.lang.NoClassDefFoundError: dagger/Provides

**Comment by xiaobailong24** [comment]
@JessYanCoding 期待已久了。不过我今明两天出门了，没带电脑出来。等回去看看

**Comment by JessYanCoding** [comment]
@xiaobailong24 你说的 **MVVMArms** 库的适配方案地址发出来下,让兄弟们看看

**Comment by xiaobailong24** [comment]
@JessYanCoding 
https://github.com/xiaobailong24/MVVMArms/tree/dev

**Comment by JessYanCoding** [comment]
@xiaobailong24 最后给出具体文件

**Comment by GillX** [comment]
@4what2do 
我使用的是金丝雀版本。进行以下调整，一直正常编译运行。

annotationProcessor rootProject.ext.dependencies["dagger2-compiler"]
//    annotationProcessor(rootProject.ext.dependencies["dagger2-compiler"]) {
//        exclude module: 'dagger'
//    }

annotationProcessor(rootProject.ext.dependencies["butterknife-compiler"]) {
        exclude module: 'support-annotations'
//        exclude module: 'butterknife-annotations'
    }

**Comment by 4what2do** [comment]
我自己新建项目 集成进去  把这个注释掉可以编译成功  就是下下来的demo 编译挂了 @GillX

**Comment by GillX** [comment]
@4what2do 我用的是Art的demo，可以正常跑。Arm倒是没试过，你看看小白龙的做法咯。

**Comment by jp1017** [comment]
根gradle 仍然保持2.3.3即可

```
classpath 'com.android.tools.build:gradle:2.3.3'
```

**Comment by thymleaf** [comment]
grade 升级到4.1 build 报错

classpath 'com.android.tools.build:gradle:3.0.0'

distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip



Error:(11, 39) 错误: 找不到符号
符号:   类 DaggerAppComponent
位置: 程序包 com.library.common.di.component

**Comment by devzwy** [comment]
修改app和arms库的build.gradle下的defaultConfig:       
```xml
 defaultConfig {
        applicationId rootProject.ext.android["PACKAGENAME"]
        minSdkVersion rootProject.ext.android["minSdkVersion"]
        targetSdkVersion rootProject.ext.android["targetSdkVersion"]
        versionCode rootProject.ext.android["versionCode"]
        versionName rootProject.ext.android["versionName"]
        testInstrumentationRunner rootProject.ext.dependencies["androidJUnitRunner"]
        //gradle3.0.0报错 加入下面代码
        javaCompileOptions {
            annotationProcessorOptions { includeCompileClasspath = true }
        }
    }
```
目测解决。

**Comment by JessYanCoding** [comment]
Fix and close the issues https://github.com/JessYanCoding/MVPArms/commit/92d9ebcbfd8bc4402e056f88288594130247e4d4
