### ISSUE TITLE
BasePresenter<M, V extends IBaseView>, 当没有V时如何处理？

### ISSUE THREAD

**Issue by jp1017** [JessYanCoding/MVPArms#16]
有这样一个契约, 获取服务器时间，不需要View

```
public interface TimeContract {
    //Model层定义接口,外部只需关心model返回的数据,无需关心内部细节,及是否使用缓存
    interface Model {
        Observable<SvrTime> getServerTime();
    }
}
```

当建立 TimePresenter时，继承`BasePresenter`没有View,如何是好？

我的处理：

1. 加个空View

```
public interface TimeContract {
    interface View extends IBaseView {
    }
    //Model层定义接口,外部只需关心model返回的数据,无需关心内部细节,及是否使用缓存
    interface Model {
        Observable<SvrTime> getServerTime();
    }
}
```

2. 新建一个BaseMPresenter, 然后TimePresenter继承BaseMPresenter

```
BasePresenter<M> 
```

可以看到，方法1多出无用的View, 方法2多了基类Presenter, 我还没测试方法2,请问还有没更好的方法

**Comment by JessYanCoding** [comment]
我个人对你不需要view层的理解是,这个页面只有这一个功能,并且逻辑不复杂很简单,不需要更新ui,这种情况的话,可以暂时不需要presenter,也就是说直接在activity用model处理,或者直接在activity请求,但是如果以后很有可能会增加其他功能,那就需要把mvp都生成,毕竟写一个项目在开发时考虑扩展和耦合对以后会很有,按自己的需求灵活运用

**Comment by jp1017** [comment]
@JessYanCoding 谢谢，直接 Model 处理了

**Comment by hopecyb** [comment]
@jp1017 请问，你是如何用model直接处理的，能否贴下代码。刚接触安卓，不好意思。

**Comment by jp1017** [comment]
> 也就是说直接在activity用model处理,或者直接在activity请求

有V时正常用P请求，没有V就如上用M请求。
