### ISSUE TITLE
一点小问题

### ISSUE THREAD

**Issue by wuyingtong** [JessYanCoding/MVPArms#162]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Bug Description:

  /**
     * 退出应用程序
     */
    public void appExit() {
        try {
            killAll();
            release();// 释放资源
            ActivityManager activityMgr =//mApplication is null
                    (ActivityManager) mApplication.getSystemService(Context.ACTIVITY_SERVICE);
            activityMgr.killBackgroundProcesses(mApplication.getPackageName());
            System.exit(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

 /**
     * 释放资源
     */
    public void release() {
        EventBus.getDefault().unregister(this);
        mActivityList.clear();
        mHandleListener = null;
        mActivityList = null;
        mCurrentActivity = null;
        mApplication = null;
    }

### Related Code:
```java
  

```

### Bug Log:
```log


```

**Comment by JessYanCoding** [comment]
这个方法里的代码早就修改了, 下个版本发布
