### ISSUE TITLE
为什么导入的时候一直报这个错，网上的方法都试了一遍还是不呢给解决。。

### ISSUE THREAD

**Issue by Txxyyy** [JessYanCoding/MVPArms#163]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### MVPArms Version:
compile 'me.jessyan:arms:2.2.3'

### AndroidStudio Version:
2.3.3

### Target Android Version：
5.0

### Bug Description:
按照wiki上面一步步的配置下来，最后build的时候就报这个错，我也新建了几个项目也还是导入不进来，希望能提供一下解决思路！

### Related Code:
```java
  

```

### Bug Log:
```log
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

```

**Comment by JessYanCoding** [comment]
只要在你的电脑上从 github 下载下来的 Demo 不改任何代码能直接运行,那就是你的问题

**Comment by JessYanCoding** [comment]
只要 Demo 能正常运行,  那就是你和 Demo 配置的不对, 自己和 Demo 比对, 连连看的游戏就自己找

**Comment by Txxyyy** [comment]
你好，我把Demo下载下来一行代码都没改，就只改了gradle版本，也是不能直接编译成功，我不清楚是不是我android studio的原因还是我建项目SDK版本的原因！

**Comment by JessYanCoding** [comment]
Gradle 也不能改
