### ISSUE TITLE
design 26.1.0 下不下来，怎么办

### ISSUE THREAD

**Issue by zhouxxiaolong** [JessYanCoding/MVPArms#164]
我可以翻墙 但是就是下不了26.1.0的包，现在可以更新这个包了？我sdk也没看到这个呀

**Comment by JessYanCoding** [comment]
此类问题自行解决

**Comment by jp1017** [comment]
远程库添加 google()　库

**Comment by zhouxxiaolong** [comment]
就是加了没用我才问的，我走了代理也没拉下来。。。。自己的私服也没拉下来

**Comment by xiaobailong24** [comment]
@zhouxxiaolong http://www.jianshu.com/p/78f4f71dee8c
