### ISSUE TITLE
项目第一次运行不了

### ISSUE THREAD

**Issue by HeMa321** [JessYanCoding/MVPArms#166]
项目下载下来第一次运行   Error:Unexpected metadata type found.
build  clean和rebuild也不行  提示 Error:A problem occurred configuring root project 'MVPArms-master'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not load module metadata from C:\Users\Administrator\.gradle\caches\modules-2\metadata-2.23\descriptors\org.apache.httpcomponents\httpclient\4.2.1\22da77b0d76ea8df17298218f3ec1f87\descriptor.bin
这个什么问题,求请教,谢谢

**Comment by xiaobailong24** [comment]
@HeMa321 把以下目录删掉试试：
**C:\Users\Administrator.gradle\caches\modules-2\metadata-2.23\descriptors\org.apache.httpcomponents\httpclient\4.2.1**

**Comment by HeMa321** [comment]
过滤一一次发现是 项目下的build.dradle  错误  
classpath 'com.github.dcendents:android-maven-gradle-plugin:2.0'
//        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7.3'  //这行注释掉就不会报上述的错误

删掉还是不行,clean与sync跟上面的问题

**Comment by HeMa321** [comment]
我就改动了config.build这一块, 还原回去重试也是不行
 android = [
               compileSdkVersion       : 25,
               buildToolsVersion       : "25.0.1",
               minSdkVersion           : 15,
               targetSdkVersion        : 25,
               versionCode             : 146,
               versionName             : "2.3.1"
    ]

     version = [
                   androidSupportSdkVersion: "25.3.1",

**Comment by JessYanCoding** [comment]
我只会处理没有改动任何代码的 Demo 报错的情况, 哪怕你改动了某些 **Build.gralde** 的代码, 又返回回去了, 但是 **Gradle** 已经执行过一遍, 该生成的文件已经生成, 所以报错也不能说明什么问题

**Comment by HeMa321** [comment]
现在我是重新下载下来,直接导入demo 出现 Error:Unexpected metadata type found. 
是不是之前的缓存还在,需要清理哪个文件夹?多谢

**Comment by JessYanCoding** [comment]
直接运行 Demo, 不要使用导入, 如果运行不起, 就在一个全新的项目中, 通过远程库依赖的方式按照 wiki 的步骤依赖

**Comment by HeMa321** [comment]
好的,多谢,我自己再琢磨琢磨

**Comment by HeMa321** [comment]
再请教下,如果我as是2.3的我需要下载哪个?
多谢

**Comment by JessYanCoding** [comment]
如果你只想跑 Demo 在 [这里](https://github.com/JessYanCoding/MVPArms/releases) 下载 2.2.3 的源码

**Comment by HeMa321** [comment]
多谢,麻烦啦

**Comment by HeMa321** [comment]
这是只是跑一下demo,如果我在demo更改写项目可以吗?

**Comment by JessYanCoding** [comment]
可以的, 如果你使用远程依赖, 可以使用最新的 2.3.1

**Comment by HeMa321** [comment]
好的  ,多谢,两种方法我都试试
