### ISSUE TITLE
AppManager类的appExit()方法有BUG，appExit()方法无法结束进程，报空指针

### ISSUE THREAD

**Issue by TYUpya** [JessYanCoding/MVPArms#167]
### Related Code:
    /**
     * 释放资源
     */
    public void release() {
        EventBus.getDefault().unregister(this);
        mActivityList.clear();
        mHandleListener = null;
        mActivityList = null;
        mCurrentActivity = null;
        mApplication = null;
    }    

    /**
     * 退出应用程序
     */
    public void appExit() {
        try {
            killAll();
            release();
            ActivityManager activityMgr = (ActivityManager)  mApplication.getSystemService(Context.ACTIVITY_SERVICE);
            activityMgr.killBackgroundProcesses(mApplication.getPackageName());
            System.exit(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
  
### 描述
你的appExit()方法里第二个调用了release()方法，它把mApplication = null，导致appExit()方法第三个调用ActivityManager activityMgr = (ActivityManager)  mApplication.getSystemService(Context.ACTIVITY_SERVICE) 永远都会报空指针。

**Comment by JessYanCoding** [comment]
上个月就[修复](https://github.com/JessYanCoding/MVPArms/commit/5c5e48e4125f5474e2be398f19424f42ff829485)了, 并且这个问题的 Issues 已经回答过一次了, 提问前最好先搜索下之前提过的问题
