### ISSUE TITLE
应用后台被杀死后，glide的生命周期绑定问题！

### ISSUE THREAD

**Issue by Zweihui** [JessYanCoding/MVPArms#168]
### Environment

- [x] MVPArms Version:  v2.2.0
- [x] AndroidStudio Version: v2.3.2
- [x] Gradle Plugin Version: v2.3.1
- [x] Target Android Version:Android 7.0
- [x] Device Model:MIUI 9

### Bug Description:
我的glide版本是3.8.0，当应用进入后台，因为内存不足被系统杀死后，重新进入应用，加载栈顶的第一个Activity，第一个Activity的图片加载正常。当按返回时，进入第二个Activity，第二个Activity里的图片会一闪而逝。分析应该是第二个Activity的glide的生命周期因为是和appManager().getTopActivity()（也就是第一个Activity）绑定的，才会出现这样的问题。测试调试后，确实是这样。所以，glide通过appManager().getTopActivity()绑定生命周期，并不能保证和当前View的Activity绑定。

### Related Code:
Arms的Demo里的代码,运行有问题：
```java
  mImageLoader.loadImage(mAppComponent.appManager().getTopActivity() == null
                        ? mAppComponent.application() : mAppComponent.appManager().getTopActivity(),
                ImageConfigImpl
                        .builder()
                        .url(data.getAvatarUrl())
                        .imageView(mAvatar)
                        .build());
```
修改后,运行正常：
```java
  mImageLoader.loadImage(view.getContext(),
                ImageConfigImpl
                        .builder()
                        .url(data.getAvatarUrl())
                        .imageView(mAvatar)
                        .build());
```

**Comment by JessYanCoding** [comment]
首先这个问题是发生在 Demo 上的, 和框架以及 **AppManager** 没有任何关系, **Demo** 只是一个简单的引导使用的作用, 我并没有投入多少精力, 而且 Demo 只有一个 Activity 所以我写的时候也不会考虑太多其他的东西, 仅仅是为了实现, 但这个和框架没有任何直接联系也不会影响框架

第二, 假设你的问题出现并且你的分析是正确的, 但是你的方法并不能真的解决这个问题, 因为你传入的是 Context, 这时是没有和 Activity 绑定生命周期的, 虽然不会出现你说的一闪而逝的现象, 但当发生 Glide 正在加载但 Activity 被销毁的情况时, 这时是会内存泄漏的, 所以要彻底解决你说的问题, 就是从 Glide 能直接拿到 Activity, 或者使用 **AppManager** 通过其他方法查找到你想要的 Activity 实例, 比如说通过名字查找

**Comment by JessYanCoding** [comment]
另外说一句,  **getTopActivity() 获取的是最近一个启动的 Activity, 如果这个 Activity 在没有被销毁的情况下打开了之前已经存在并没有被销毁的 Activity, 那个新打开的 Activity 调用 getTopActivity() 肯定是上一个 Activity**

**Comment by Zweihui** [comment]
嗯，仅仅是记录一下自己遇到的坑，毕竟一般人都会照着Demo里的写法，难免会有人和我一样遇到。

这是glide源码，glide会自己把Context强转成Activity，所以我的方法不存在内存泄漏。
```java

public static RequestManager with(Context context) {
        RequestManagerRetriever retriever = RequestManagerRetriever.get();
        return retriever.get(context);
   }

public RequestManager get(Context context) {
        if (context == null) {
            throw new IllegalArgumentException("You cannot start a load on a null Context");
        } else if (Util.isOnMainThread() && !(context instanceof Application)) {
            if (context instanceof FragmentActivity) {
                return get((FragmentActivity) context);
            } else if (context instanceof Activity) {
                return get((Activity) context);
            } else if (context instanceof ContextWrapper) {
                return get(((ContextWrapper) context).getBaseContext());
            }
        }

        return getApplicationManager(context);
    }
```

**Comment by JessYanCoding** [comment]
这个并不绝对, 你并不能保证 getContext 就一定是 Activity, 在 5.0 以下的的系统还是会存在内存泄漏 http://blog.csdn.net/wingichoy/article/details/72868959

**Comment by Zweihui** [comment]
glide已经考虑到这个了，如果是是ContextWrapper，就通过getBaseContext()获取Context，再递归调用get(Context context)，最后还是能强转成Activity。
```java
else if (context instanceof ContextWrapper) {
                return get(((ContextWrapper) context).getBaseContext());
            }
```

**Comment by JessYanCoding** [comment]
好的, 了解👌

**Comment by JessYanCoding** [comment]
Demo 已按照你的方式更新, 感谢你提这个建议
