### ISSUE TITLE
你好,能不能基于2.2.3版本，发布一个小版本，解决BUG的，例如Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: 

### ISSUE THREAD

**Issue by tulongchao** [JessYanCoding/MVPArms#170]
我发现最新版本跨度有点大，升级到最新版本，项目有问题，我建议：这边能不能在稳定的版本上进行重构，或者升级。个人建议。

**Comment by JessYanCoding** [comment]
兄弟, 你使用 v2.3.1 也不让你, 必须使用 v3.0 以上的 AS, 单独维护某个版本是不可能的, 我没这么多精力和时间, 我还有其他的事要做, 维护这框架, 我已经牺牲了我很多业余时间

**Comment by tulongchao** [comment]
辛苦了，个人建议的。呵呵
