### ISSUE TITLE
在app主工程中me.jessyan.mvparms.demo.di.component包下，没有DaggerUserComponent这个java类

### ISSUE THREAD

**Issue by hardstruglling** [JessYanCoding/MVPArms#171]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment

- [x] MVPArms Version: 
- [x] AndroidStudio Version: 
- [x] Gradle Plugin Version: 
- [x] Target Android Version: 
- [x] Device Model: 

### Related Code:
```java
  

```

### Bug Log:
```log


```

**Comment by JessYanCoding** [comment]
自己看常用 Issues, 你按提问流程走了吗, 不按流程走, 一看到 Id 就直接 Close 这个 Id 的问题, 不管是什么问题
