### ISSUE TITLE
Presenter 怎么注入的，注入对象的来源

### ISSUE THREAD

**Issue by Sum41forever** [JessYanCoding/MVPArms#173]
#### Presenter 怎么注入的 ？
A：`Presenter`的注入通过`Inject`方式注入，位置是`BaseActivity`，类型是泛型 `IPresenter`及其子类

![qq 20171227114232](https://user-images.githubusercontent.com/18468976/34369937-169cfbea-eafb-11e7-9a51-060a74f4c657.png)

#### Presenter 注入对象的来源 ？
A：以框架中`UserPresenter`为例子 红色的在`UserModule`  蓝色的在`AppComponent`的接口实现类里面
![1](https://user-images.githubusercontent.com/18468976/34369984-793aac3e-eafb-11e7-8c32-769ec079b80b.png)

*userModule*
![18](https://user-images.githubusercontent.com/18468976/34370023-b71fb7b0-eafb-11e7-8b9a-0d4ddb5e6a7e.png)
![114102](https://user-images.githubusercontent.com/18468976/34370024-b825e904-eafb-11e7-8e71-8941dfe0213a.png)

*AppComponent的接口实现类DaggerAppComponent中*
![da](https://user-images.githubusercontent.com/18468976/34370029-c0f7d7ae-eafb-11e7-8390-479cc23ce103.png)
![4057](https://user-images.githubusercontent.com/18468976/34370049-e929dfec-eafb-11e7-8331-2dce24066934.png)

**Comment by JessYanCoding** [comment]
Nice. --> https://github.com/JessYanCoding/MVPArms/wiki/Issues#12

**Comment by LaoXiZi** [comment]
基础篇：Dagger2 学习 404了

**Comment by JessYanCoding** [comment]
@xiaobailong24

**Comment by xiaobailong24** [comment]
@LaoXiZi coming back soon

**Comment by WilliamChief** [comment]
mPresenter为空时 如何重新注入

**Comment by WilliamChief** [comment]
@JessYanCoding mPresenter为空时 如何重新注入
