### ISSUE TITLE
Fragment在框架中的使用，ButterKnife的绑定

### ISSUE THREAD

**Issue by Sum41forever** [JessYanCoding/MVPArms#174]
## Fragment在框架中的使用
Fragment的初始化时在`ActivityLifecycle`的Oncreate中，通过 IActivity接口的useFragment()方法设置是否使用注册回掉监听
![image](https://user-images.githubusercontent.com/18468976/34507849-fe46204c-f074-11e7-95aa-af9fe8eef5e6.png)
---
![image](https://user-images.githubusercontent.com/18468976/34507917-a2e17534-f075-11e7-9b82-f2e33e385f8c.png)

## ButterKnife在Fragment中的绑定
**问题**：为什么框架里的`BaseActivity`提供了通用的`ButterKnife`绑定，而`BaseFragment`没有提供？      
**回答**：框架对`Fragment`提供了`ButterKnife`绑定，不过和`BaseActivity`以基类的形式绑定不同，`Frament`中对`ButterKnife`绑定是通过注册回掉的形式绑定的。
![image](https://user-images.githubusercontent.com/18468976/34508035-ac66b60e-f076-11e7-85b3-09854c20fbd6.png)
![image](https://user-images.githubusercontent.com/18468976/34508114-36fd29e2-f077-11e7-8689-9dbae63812bc.png)
![image](https://user-images.githubusercontent.com/18468976/34508151-74b6699c-f077-11e7-829a-608cd3abc3c7.png)

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/MVPArms/wiki/Issues#13
