### ISSUE TITLE
GlideImageLoaderStrategy扩展问题

### ISSUE THREAD

**Issue by wuyingtong** [JessYanCoding/MVPArms#175]
复制框架的GlideImageLoaderStrategy和ImageConfigImpl,扩展了下,会发生.ClassCastException

**Comment by JessYanCoding** [comment]
如果想扩展, 之前所有引用 ImageCofigImpl 的地方,必须全部换成扩展后的 Config 类

**Comment by wuyingtong** [comment]
com.jess.arms.http.imageloader.glide.ImageConfigImpl cannot be cast to com.ibenew.bravat.app.BNGlideImageConfigImp

com.ibenew.bravat.app.BNGlideImageLoaderStrategy.clear(BNGlideImageLoaderStrategy.java:30)
我是照着框架改的,引用的地方都改成扩展后的了

**Comment by JessYanCoding** [comment]
那你要贴出 ClassCastException 错误的日志

**Comment by wuyingtong** [comment]
不好意思,这是完整错误日志
com.ibenew.bravat.app.BNGlideImageLoaderStrategy.clear(BNGlideImageLoaderStrategy.java:31)
com.jess.arms.http.imageloader.ImageLoader.clear(ImageLoader.java:64)
com.jess.arms.base.delegate.AppDelegate$AppComponentCallbacks.onLowMemory(AppDelegate.java:203)
 android.app.Application.onLowMemory(Application.java:126)
 android.app.ActivityThread.handleLowMemory(ActivityThread.java:4410)
 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1500)
 android.os.Handler.dispatchMessage(Handler.java:102)
 android.os.Looper.loop(Looper.java:154)
 android.app.ActivityThread.main(ActivityThread.java:5527)
 java.lang.reflect.Method.invoke(Native Method)
 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by JessYanCoding** [comment]
这个问题已修复, 下个版本会 release

**Comment by wuyingtong** [comment]
好的,多谢大佬!预计下个版本什么时候

**Comment by JessYanCoding** [comment]
在优化框架中的网络日志的东西, 顺利的话这个星期

**Comment by tpnet** [comment]
@JessYanCoding 大佬，我也遇到这个问题了，等待修复

**Comment by JessYanCoding** [comment]
@tpnet Glide 已经自己做了低内存的管理

**Comment by JessYanCoding** [comment]
@tpnet 而且就算 Glide 没有自己处理低内存的情况, 系统在低内存时的回调是Android SDK 自带的 Api, 你自己可以在任何地方向 Application 注册, 框架再提供出来只是多此一举, 框架内部注册的这个回调只是为了框架内部的一些操作

**Comment by tpnet** [comment]
@JessYanCoding  原来这样子，好滴，谢谢大佬
