### ISSUE TITLE
如何复用P层或者M层

### ISSUE THREAD

**Issue by yedajiang44** [JessYanCoding/MVPArms#176]
在主页面需要退出登录，想复用登录的P层或者M层，这该怎么做？？

**Comment by Sum41forever** [comment]
通用的P 可以用写通用的接口。在所有要实现通用逻辑的Activity里面去实现这个通用的接口就行了。

**Comment by yedajiang44** [comment]
@Sum41forever 但是这样还是要重复写具体的实现啊，不知道是不是我没理解你说

**Comment by Sum41forever** [comment]
![image](https://user-images.githubusercontent.com/18468976/34656748-35b56a46-f459-11e7-8a0a-7752414f6360.png)

像这个通用的P 。你每个Activity去实现这个接口，请求就可以直接调用方法，他自己回把请求的数据回掉到，你可以少些请求。直接获得数据

**Comment by yedajiang44** [comment]
@Sum41forever 懂了懂了！多谢大佬

**Comment by Sum41forever** [comment]
@yedajiang44  你看下 新的一个issue 我写了一个简单的示范例子
[Arms复用的Presenter 注入简单示例](https://github.com/JessYanCoding/MVPArms/issues/181)

**Comment by yedajiang44** [comment]
@Sum41forever 豁然开朗~哈哈哈！多谢多谢~

**Comment by Sum41forever** [comment]
@yedajiang44 之前issue那个不对，不符合实际业务场景，已经做了更新，你可以看看新的是怎么样实现复用的
