### ISSUE TITLE
框架中 RxLifecycle 的绑定使用和注意事项。

### ISSUE THREAD

**Issue by Sum41forever** [JessYanCoding/MVPArms#177]
> 这个Issue不涉及 RxLifecycle 原理，原理可以参考我写的一篇Blog [Android Rxlifecycle 实现原理及过程](http://www.sum41forever.com/post/5c5e110400c2)，如果发现问题，欢迎交流，共同进步 。

## 常规 RxLifecycle 的使用和缺点
**RxLifecycle** 的常规使用是通过继承，如下面的这样
```java
    RetrofitHelper.getApi().login()//登陆接口
            .compose(this.<BaseModel<List<BasicData>>>bindToLifecycle())//绑定生命周期
            .subscribeOn(Schedulers.io())
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe(new Acition...);
```
这种通过继承的方法，有以下几个问题。
1. 多一层继承关系：
我们的基类**Activity**，**Fragment**必须继承于**RxActivity**，**RxFragment**，才能调用**compose()**方法绑定
2. 不适合扩展 ：
如果在**MVP**结构 **P**层中有**Rx**流操作，那么就不能调用**compose()**方法绑定，因为该方法在**RxActivity**中。同理其他类一样。
3. 不好区分是**Activity**还是**Fragment**绑定 ：
**RxLifecycle** 的绑定是区分 **Fragment** 和 **Activity**的，如果你是在**P**里面把**View接口**强转成**RxActivity**，那么就可能出错。因为如果**P**可以在**Fragment**复用，那么强转就会带来问题。而且**View接口**的父类可能是**RxActivity**,也有可能是**RxFragmentActivity**，当然你可以通过if else + insteadof 来处理，但是每个流都这么写是很痛苦的，代码不好读，也很繁琐。

---
## 框架中RxLifecycle 绑定
框架对**RxLifecycle**的实现方式 是通过接口**Lifecycleable**实现 具体实现在父类**BaseActivity**中
`绑定方式`是通过`工具类` **RxLifecycleUtils**
```java
 mModel.getUsers(lastUserId, isEvictCache)
                .subscribeOn(Schedulers.io())
                .compose(RxLifecycleUtils.bindToLifecycle(mRootView))//使用 Rxlifecycle,使 Disposable 和 Activity 一起销毁
                .subscribe(new ErrorHandleSubscriber<List<User>>(mErrorHandler) {
                 .....//省略
                });
```
好处是解决了上面说的三个不足的地方。
1. 接口实现，所以少一层继承关系
2. 因为是工具类**RxLifecycle**绑定，只需要你传入一个 **IView**的接口就行,这意味着你可以在P或者其他地方直接使用。
3. 工具类**RxLifecycle**绑定过程中会自动判断是**Activity**类型绑定还是**Fragment**类型绑定
```java

    //绑定 Activity/Fragment 的生命周期
    public static <T> LifecycleTransformer<T> bindToLifecycle(@NonNull IView view) {
        if (view instanceof Lifecycleable) {
            return bindToLifecycle((Lifecycleable) view);
        } else {
            throw new IllegalArgumentException("view isn't Lifecycleable");
        }
    }

    public static <T> LifecycleTransformer<T> bindToLifecycle(@NonNull Lifecycleable lifecycleable) {
        if (lifecycleable instanceof ActivityLifecycleable) {
            return RxLifecycleAndroid.bindActivity(((ActivityLifecycleable) lifecycleable).provideLifecycleSubject());
        } else if (lifecycleable instanceof FragmentLifecycleable) {
            return RxLifecycleAndroid.bindFragment(((FragmentLifecycleable) lifecycleable).provideLifecycleSubject());
        } else {
            throw new IllegalArgumentException("Lifecycleable not match");
        }
    }
```
---

## 注意事项
1. **Activity**必须继承**BaseActivity**：这个很好理解，因为对**RxLifecycle**的实际实现核心对象是在**BaseActivity**中
```java
    private final BehaviorSubject<ActivityEvent> mLifecycleSubject = BehaviorSubject.create();
    public final Subject<ActivityEvent> provideLifecycleSubject() {
        return mLifecycleSubject;
    }
```
2. 对于第三方的Activity是无法绑定的
因为你不能继承**BaseActivity**，也可以说无法实现**Lifecycleable**这个接口，

3. 如果确实不能继承**BaseActivity**，该如何实现**RxLifecycle**
模仿**BaseActivity** 去实现**Lifecycleable**这个接口

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/MVPArms/wiki#3.14

**Comment by NerdAnonymous** [comment]
@JessYanCoding 我用框架之前没怎么注意这篇文章 直接上手 今天偶然发现onStop后不走回调了，我猜就是这个东西的问题，上来一找果然，稳的很

**Comment by PiPiCaptain** [comment]
@NerdAnonymous 我也遇到这问题，但看不太懂，请问要怎么处理？

**Comment by PiPiCaptain** [comment]
@NerdAnonymous 我解决了。看了一下RxLifecycle和MVPArms源码，找到了方法。
RxLifecycleUtils.bindUntilEvent(mRootView, FragmentEvent.DESTROY) 或者
RxLifecycleUtils.bindUntilEvent(mRootView, ActivityEvent.DESTROY)

**Comment by cjcj125125** [comment]
fragment里面怎么使用呢

**Comment by JessYanCoding** [comment]
@cjcj125125 和 Activity 的用法没有任何区别

**Comment by LeeeeeYao** [comment]
mModel.getTimUserAndSig(replaceToken, userRole)
                **.compose(RxLifecycleUtils.bindUntilEvent(mRootView, ActivityEvent.DESTROY))**
                .subscribe(new ErrorHandleSubscriber<BaseResponse<TimUserAndSig>>(mErrorHandler) {
                    @Override
                    public void onNext(BaseResponse<TimUserAndSig> userBaseResponse) {
                        if (userBaseResponse.isSuccess()) {
                            mRootView.getTimUserAndSigSuccess(userBaseResponse.getBody());
                        } else {
                            mRootView.showMessage(userBaseResponse.getMsg());
                        }
                    }
                });
我添加了这样的方法，但是依然不执行onNext是什么原因呢，求助
