### ISSUE TITLE
AppManager线程安全有问题

### ISSUE THREAD

**Issue by JamesIsTheMan** [JessYanCoding/MVPArms#178]
### Others:
建议把synchronised扩大到整个方法，或者一开始就初始化一个空的LinkedList会不会更好一点？
/**
     * 添加 {@link Activity} 到集合
     */
    public void addActivity(Activity activity) {
        if (mActivityList == null) {
            mActivityList = new LinkedList<>();
        }
        synchronized (AppManager.class) {
            if (!mActivityList.contains(activity)) {
                mActivityList.add(activity);
            }
        }
    }

    /**
     * 删除集合里的指定的 {@link Activity} 实例
     *
     * @param {@link Activity}
     */
    public void removeActivity(Activity activity) {
        if (mActivityList == null) {
            Timber.tag(TAG).w("mActivityList == null when removeActivity(Activity)");
            return;
        }
        synchronized (AppManager.class) {
            if (mActivityList.contains(activity)) {
                mActivityList.remove(activity);
            }
        }
    }

**Comment by JessYanCoding** [comment]
建议请给理由, 如果自己都不知道理由, 或者自己都不确定, 那也说服不了我

**Comment by JamesIsTheMan** [comment]
理由已贴出了，例如addActivity/removeActivity之间显然不是线程安全的，除非synchronize放在整个方法级别，或者让synchronised块包括正个方法的全部代码。

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/MVPArms/commit/9780048ffde72039a354bb43143db5d19ad5756a

**Comment by JessYanCoding** [comment]
你看下

**Comment by JamesIsTheMan** [comment]
挺好，谢谢！
