### ISSUE TITLE
EventBus怎么用?

### ISSUE THREAD

**Issue by Littleiii** [JessYanCoding/MVPArms#18]
楼主你的arms已经引入我们项目中,但是我一直有一个疑问,就是EventBus怎么用?,它的应用场景是什么?可否解答一下?

**Comment by jp1017** [comment]
事件总线，可以替换掉Handler, 接口，广播等, 常用于Activity, Fragment, Service间传值 :smile:

**Comment by jp1017** [comment]
我也引入了，强烈需要QQ群啊: https://github.com/JessYanCoding/MVPArms/issues/13

**Comment by JessYanCoding** [comment]
哎,兄弟你问的大部分问题确实都不属于issue了,你给我说qq算了，我加你,你直接问我,你一直提issue,也不方便

**Comment by JessYanCoding** [comment]
好吧,QQ群:301733278

**Comment by Littleiii** [comment]
1373519715
