### ISSUE TITLE
android.os.BadParcelableException: ClassNotFoundException when unmarshalling: data

### ISSUE THREAD

**Issue by tulongchao** [JessYanCoding/MVPArms#180]
已经升级到最新版本，2.3.1,我退出app，并没有杀死进程，就是finish所有的Activity，在打开app有时会报这个错误，

**Comment by Sum41forever** [comment]
Parcelable 看上去是序列化的问题。有更详细的log信息吗

**Comment by JessYanCoding** [comment]
先上完整 **Log**, 如果是 **ActivityDelegate** 的错误, 这个错误已经修复, 下个版本 release

**Comment by tulongchao** [comment]
java.lang.RuntimeException:Unable to start activity ComponentInfo{com.lanyife.futures/com.lanyife.futures.mvp.ui.activity.MainActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: data
--
2 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2408)
3 ......
4 Caused by:
5 android.os.BadParcelableException:ClassNotFoundException when unmarshalling: data
6 android.os.Parcel.readParcelableCreator(Parcel.java:2154)
7 android.os.Parcel.readParcelable(Parcel.java:2104)
8 com.jess.arms.base.delegate.FragmentDelegateImpl.<init>(FragmentDelegateImpl.java)
9 com.jess.arms.base.delegate.FragmentDelegateImpl$1.createFromParcel(FragmentDelegateImpl.java)
10 com.jess.arms.base.delegate.FragmentDelegateImpl$1.createFromParcel(FragmentDelegateImpl.java)
11 android.os.Parcel.readParcelable(Parcel.java:2111)
12 android.os.Parcel.readValue(Parcel.java:2020)
13 android.os.Parcel.readArrayMapInternal(Parcel.java:2321)
14 android.os.Bundle.unparcel(Bundle.java:249)
15 android.os.Bundle.getParcelable(Bundle.java:1206)
16 com.jess.arms.integration.FragmentLifecycle.fetchFragmentDelegate(FragmentLifecycle.java)
17 com.jess.arms.integration.FragmentLifecycle.onFragmentAttached(FragmentLifecycle.java)
18 android.support.v4.app.FragmentManagerImpl.dispatchOnFragmentAttached(FragmentManager.java)
19 android.support.v4.app.FragmentManagerImpl.dispatchOnFragmentAttached(FragmentManager.java)
20 android.support.v4.app.FragmentManagerImpl.dispatchOnFragmentAttached(FragmentManager.java)
21 android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java)
22 android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java)
23 android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java)
24 android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java)
25 android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java)
26 android.support.v4.app.Fragment.restoreChildFragmentState(Fragment.java)
27 android.support.v4.app.Fragment.onCreate(Fragment.java)
28 android.support.v4.app.Fragment.performCreate(Fragment.java)
29 android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java)
30 android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java)
31 android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java)
32 android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java)
33 android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java)
34 android.support.v4.app.Fragment.restoreChildFragmentState(Fragment.java)
35 android.support.v4.app.Fragment.onCreate(Fragment.java)
36 android.support.v4.app.Fragment.performCreate(Fragment.java)
37 android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java)
38 android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java)
39 android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java)
40 android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java)
41 android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java)
42 android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java)
43 android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java)
44 android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java)
45 com.jess.arms.base.BaseActivity.onCreate(BaseActivity.java)
46 com.lanyife.futures.mvp.ui.activity.MainActivity.onCreate(Native Method)
47 com.lanyife.futures.mvp.ui.activity.MainActivity.onCreate(Native Method)
48 android.app.Activity.performCreate(Activity.java:5406)
49 android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
50 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2362)
51 android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2460)
52 android.app.ActivityThread.access$800(ActivityThread.java:164)
53 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1362)
54 android.os.Handler.dispatchMessage(Handler.java:110)
55 android.os.Looper.loop(Looper.java:193)
56 android.app.ActivityThread.main(ActivityThread.java:5542)
57 java.lang.reflect.Method.invokeNative(Native Method)
58 java.lang.reflect.Method.invoke(Method.java:515)
59 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
60 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:657)
61 dalvik.system.NativeStart.main(Native Method)

**Comment by tulongchao** [comment]
还有个BUG，顺便改一下吧？

java.lang.NullPointerException:
--
6 com.jess.arms.utils.DeviceUtils.netIsConnected(DeviceUtils.java)
 ConnectivityManager connectMgr = (ConnectivityManager) context.getSystemService(Context.CONNECTIVITY_SERVICE);
        //手机网络连接状态
        NetworkInfo mobNetInfo = connectMgr.getNetworkInfo(ConnectivityManager.TYPE_MOBILE);
        //WIFI连接状态
        NetworkInfo wifiNetInfo = connectMgr.getNetworkInfo(ConnectivityManager.TYPE_WIFI);
        if (!mobNetInfo.isConnected() && !wifiNetInfo.isConnected()) {
            //当前无可用的网络
            return false;
        }
        return true;
两个对象mobNetInfo,wifiNetInfo,可能为null

**Comment by JessYanCoding** [comment]
第一个 bug 是已经解决了的, 第二个bug 中 **DeviceUtils** 是复制别人的, 你提 pr 吧

**Comment by tulongchao** [comment]
第一个BUG，在说的那种情况下，还是存在的，退出app，并没有杀死进程，当然也有可能是我这边代码导致的，目前，我这变的代码还没有找到问题

**Comment by tulongchao** [comment]
这个BUG也算是个偶发的，大神没事的时候可以在研究一下，呵呵

**Comment by JessYanCoding** [comment]
第一个 BUG 我前段时间已经移除了 **Parcelable** 相关的操作, 换了一种实现方式, 是不会再出现 ** BadParcelableException** 错误的, v2.3.1 还没更新, 要下个版本 **release**

**Comment by tulongchao** [comment]
/* mvparms */
    compile 'me.jessyan:arms:2.3.1'我现在用的2.3.1的啊，难道目前2.3.1还不是release版本吗

**Comment by JessYanCoding** [comment]
... 是我没解释清楚, 还是你理解有问题, 下个版本 release 意思就是, 还没发布即将 release 的下个正式版本, v2.3.1 是目前最新的正式版, 是还没修复这个 bug 的版本

**Comment by tulongchao** [comment]
下个版本大概什么时候，我关注一下，呵呵

**Comment by JessYanCoding** [comment]
这个星期
