### ISSUE TITLE
通用逻辑层Presenter的注入简单示例

### ISSUE THREAD

**Issue by Sum41forever** [JessYanCoding/MVPArms#181]
通用的P 命名为**TestPresenter** 逻辑就是验证账号密码是否正确
#### UserActivity 中注入通用P
![UserActivity中注入通用P](https://user-images.githubusercontent.com/18468976/34705060-839670cc-f538-11e7-9d53-372fa2553a7e.png)
#### UserModule 提供对象
![UserModule.class](https://user-images.githubusercontent.com/18468976/34704951-d3c1d0ba-f537-11e7-8346-a75a960844d6.png)
#### TestPresenter
![TestPresenter.class](https://user-images.githubusercontent.com/18468976/34704933-ba4bbeb6-f537-11e7-9902-63d50bbf128e.png)
#### TestContract
![TestContract.class](https://user-images.githubusercontent.com/18468976/34704940-c6a2ab7a-f537-11e7-9df7-a5b02006e5c6.png)

-----

#### 代码测试
UserActivity 执行通用 TestPresenter 逻辑
![P1](https://user-images.githubusercontent.com/18468976/34704997-0e3a6022-f538-11e7-8261-cb92949cf99f.png)
![P2](https://user-images.githubusercontent.com/18468976/34704998-1008a800-f538-11e7-9152-2c970109c804.png)
UserActivity 回调成功
![P3](https://user-images.githubusercontent.com/18468976/34704999-1109ee08-f538-11e7-80ad-1967ec67a9c6.png)

**Comment by Sum41forever** [comment]
复杂的重用问题可以看下这里
[Presenter重用问题](https://github.com/JessYanCoding/MVPArms/issues/22)

**Comment by JessYanCoding** [comment]
如果想复用依赖关系比较复杂的 **Presenter**, 可以选择复用该 **Presenter** 的 **Module**, 因为 **Module**, 描述了该 **Presenter** 的依赖关系图, 指导 **Dagger** 的如何注入, 参考 [这里](https://github.com/JessYanCoding/MVPArms/issues/22)

**Comment by Sum41forever** [comment]
如果通用的P用自己的Component注入，就要依赖Component，而不同的Component,Scope不能相同，如果通用的P用单独的Component，那么Scope必须单独提供，既不好维护，也不容易理解，一个Activity，2个P的Scope不同。。

暂时还没找到比较好的方法
```java
  UserComponent userComponent =  DaggerUserComponent
                .builder()
                .appComponent(appComponent)
                .userModule(new UserModule(this))
                .build();

        //通用的P的注入
        DaggerGirlComponent
                .builder()
                .userComponent(userComponent)
                .girlModule(new GirlModule(this))
                .build()
                .inject(this);

···

**Comment by Sum41forever** [comment]
在实验第二种复用方式 所查阅的比较不错的文章：
[Dagger2：Scope, Component间依赖和subComponent](https://juejin.im/entry/59ed7c9c6fb9a045023acb94)
[Dagger 2. Part II. Custom scopes, Component dependencies, Subcomponents](https://proandroiddev.com/dagger-2-part-ii-custom-scopes-component-dependencies-subcomponents-697c1fa1cfc)

**Comment by h2uan3g** [comment]
如果acticity和fragment间的复用会不会有问题， @FragmentScope /@ActivityScope

**Comment by ruanbaojun1105** [comment]
@h2uan3g make编译都不会通过，我也不知如何复用带@FragmentScope /@ActivityScope注入的类 ，，，

**Comment by buyaomiege** [comment]
### 对于新版本的模板的做法
这里假设新建UserDetailActivityActivity复用UserPresenter
UserDetailActivityComponent的代码如下
<pre name="code" class="java">@ActivityScope
@Component(modules = {UserDetailActivityModule.class,UserModule.class}, dependencies = AppComponent.class)
public interface UserDetailActivityComponent {
    void inject(UserDetailActivityActivity activity);
    @Component.Builder
    interface Builder {
        @BindsInstance
        UserDetailActivityComponent.Builder view(UserDetailActivityContract.View view);
        //名字随便
        @BindsInstance
        UserDetailActivityComponent.Builder view2(UserContract.View view);

        UserDetailActivityComponent.Builder appComponent(AppComponent appComponent);

        UserDetailActivityComponent build();
    }
}
</pre>
UserDetailActivityActivity的代码如下
<pre name="code"  class="java">
public class UserDetailActivityActivity extends BaseActivity<UserDetailActivityPresenter> implements
        UserDetailActivityContract.View,UserContract.View {
    @Inject
    UserPresenter userPresenter;
    @Inject
    RxPermissions mRxPermissions;
    @Override
    public void setupActivityComponent(@NonNull AppComponent appComponent) {
        DaggerUserDetailActivityComponent //如找不到该类,请编译一下项目
                .builder()
                .appComponent(appComponent)
                .view(this)
                .view2(this)
                .build()
                .inject(this);
    }

    @Override
    public int initView(@Nullable Bundle savedInstanceState) {
        return R.layout.activity_user_detail; //如果你不需要框架帮你设置 setContentView(id) 需要自行设置,请返回 0
    }

    @Override
    public void initData(@Nullable Bundle savedInstanceState) {
        userPresenter.requestUsers(true);
    }

    @Override
    public void showLoading() {

    }

    @Override
    public void hideLoading() {

    }

    @Override
    public void showMessage(@NonNull String message) {
        checkNotNull(message);
        ArmsUtils.snackbarText(message);
    }

    @Override
    public void launchActivity(@NonNull Intent intent) {
        checkNotNull(intent);
        ArmsUtils.startActivity(intent);
    }

    @Override
    public void killMyself() {
        finish();
    }

    @Override
    public void startLoadMore() {

    }

    @Override
    public void endLoadMore() {

    }

    @Override
    public Activity getActivity() {
        return this;
    }

    @Override
    public RxPermissions getRxPermissions() {
        return mRxPermissions;
    }
}
</pre>

**Comment by ruanbaojun1105** [comment]
@buyaomiege 你编译能通过，但是在inject的时候必须传两个实现view,不然dagger初始化都不过

**Comment by buyaomiege** [comment]
> @buyaomiege 你编译能通过，但是在inject的时候必须传两个实现view,不然dagger初始化都不过

 DaggerUserDetailActivityComponent //如找不到该类,请编译一下项目
                .builder()
                .appComponent(appComponent)
                .view(this)
                .view2(this)//这里不是传了吗
                .build()
                .inject(this);

**Comment by ruanbaojun1105** [comment]
@buyaomiege 在activity里

**Comment by FeatherZhong** [comment]
> @buyaomiege 在activity里

能够具体说明一下上面代码怎么修改吗，谢谢。

**Comment by JessYanCoding** [comment]
关于 @FragmentScope /@ActivityScope 这里统一回复：

重用同一个 Presenter，最简单的方式就是 Fragment 也使用和 Activity 一样的 Component，如果 Fragment 有自己独立的 Component，并且 Component 的 scope 和要重用的 Presenter 的 scope 不同肯定会报错。

有时候不要纠结 ActivityScope，Scope 的作用只是保证 Module 和 Component 同步。

也就是说，如果 Component 的 Scope 和 Module 的 Scope 是一样，就不会生成新的对象，也就是说，你 Fragment 的 Component 用 ActivityScope 也是可以的，但只要保证 Presenter 也是用的  ActivityScope 就可以了，达到的效果和用 FragmentScope 没有任何区别，所以你的 Presenter 本身用的就是 ActivityScope，你在 Fragment 中想重用这个 Presenter，那给 Fragment 的 Component 和 Module 定义 ActivityScope 也是可以的。

自定义的 Scope 本来也就没什么实际意义，就是为了在阅读源码时好区分业务层的逻辑，但是在 Dagger 编辑器中和官方定义的 @Singleton 都是使用相同的处理逻辑，核心在于 Module 和 Component 是否是同一个 scope，至于这个 scope 是什么 scope，不是太重要。

**Comment by ruanbaojun1105** [comment]
hah哈哈，我也之前还一直纠结ActivityScope 和FragmentScope ，你这么一讲，我想到多建的P层类好委屈

**Comment by guan25** [comment]
1、以上讨论的复用是指，一个Activity/fragment 对应多个Presenter，如果反过来呢一个Presenter对应多个Activity（虽说，这样设计并不合适）？
2、一般我理解，mvp中Presenter复用，应该是可以切换不同的view层acitivity（Presenter多个实例对应不同v层），但貌似试了几种也不行

**Comment by guan25** [comment]
后来试了这样直接复用component，来实现复用Presenter ，在component 多加 inject，每次调用就会生成一个新的presenter实例。这样也ok
![image](https://user-images.githubusercontent.com/5926540/71100249-a5283f00-21ef-11ea-8c49-7aa036b0f974.png)

ps: 觉得模板类生成的Presenter类的上面添加 单例scope（@FragmentScope）并没有什么用哈
![image](https://user-images.githubusercontent.com/5926540/71100380-e0c30900-21ef-11ea-8c07-3c8c4180d09f.png)

**Comment by lhzlg3368** [comment]
你好，我也是关于一些代码复用的问题。我的项目是用的kotlin，androidx（如果需要集成很多第三方库不建议切换到Androidx，很多库还没适配）。
项目中有一些公共的接口我想把它们放在一起，不希望在每个使用的地方再写一遍重复的内容。
我尝试参考上面提到的第一种方式复用代码
在CommonModule.kt
`@Module
class CommonModule(private val view: CommonContract.View) {

    @ActivityScope
    @Provides
    fun provideCommonView(): CommonContract.View {
        return view
    }

    @ActivityScope
    @Provides
    fun provideCommonModel(model: CommonContract.Model): CommonContract.Model {
        return model
    }
}`

在LoginComponent.kt
`@ActivityScope
@Component(
    modules = [LoginModule::class, CommonModule::class],
    dependencies = [AppComponent::class]
)
interface LoginComponent {
    fun inject(activity: LoginActivity)
}
`
重新make project之后
在DaggerLoginComponent.java中是这样的

`    /**
     * @deprecated This module is declared, but an instance is not used in the component. This method is a no-op. For more, see https://dagger.dev/unused-modules.
     */
    @Deprecated
    public Builder commonModule(CommonModule commonModule) {// 为什么这里是会这样？？没有赋值
      Preconditions.checkNotNull(commonModule);
      return this;
    }
`

在LoginActivity中
`
// 如果这两行去掉项目编译通过  生成DaggerLoginComponent.java 但commonModule()方法里面没有赋值 为何
//如果不去这两行项目直接编译不通过 不会生成DaggerLoginComponent.java 报错信息为 LoginComponent.java:8: 错误: [Dagger/DependencyCycle] Found a dependency cycle: 为何？
//    @Inject
//    lateinit var mCommonPresenter:CommonPresenter 

    override fun setupActivityComponent(appComponent: AppComponent) {
        DaggerLoginComponent //如找不到该类,请编译一下项目
            .builder()
            .appComponent(appComponent)
            .loginModule(LoginModule(this))
            .commonModule(CommonModule(this))
            .build()
            .inject(this)
    }
`

🙏望回复 谢谢

**Comment by llzj1991** [comment]
关于的Presenter复用，经过几天的折腾终于实现了
![image](https://user-images.githubusercontent.com/36752868/87743731-28f4e900-c81c-11ea-92f9-845835328b25.png)
![image](https://user-images.githubusercontent.com/36752868/87743835-740efc00-c81c-11ea-8e68-69c736495501.png)
![Uploading image.png…]()
实测编译通过，Presenter调用正常

**Comment by Jett399** [comment]
> 关于的Presenter复用，经过几天的折腾终于实现了
> ![image](https://user-images.githubusercontent.com/36752868/87744134-41193800-c81d-11ea-82bf-ce8ac2c15e8c.png)
> ![image](https://user-images.githubusercontent.com/36752868/87743731-28f4e900-c81c-11ea-92f9-845835328b25.png)
> ![image](https://user-images.githubusercontent.com/36752868/87743835-740efc00-c81c-11ea-8e68-69c736495501.png)
> 
> 实测编译通过，Presenter调用正常

编译报错
