### ISSUE TITLE
Toast的信息被自动加了appname前缀

### ISSUE THREAD

**Issue by cxmmxc** [JessYanCoding/MVPArms#183]
如题；
例如：Toast.makeText(context, "Hello", Toast.LENGTH_SHORT).show();
         我的appname是"App";
       结果UI界面弹出的Toast提示为 "App:Hello"。
  我Debug跟踪，发现传入的就是"Hello"

**Comment by cxmmxc** [comment]
原来是小米捣的鬼。。。。我的锅，更新了新的MIUIbane版本，测试机都是小米了。。。

**Comment by TYUpya** [comment]
变态的小米。
