### ISSUE TITLE
 java.security.InvalidParameterException File cache directory does not exist com.jess.arms.di.module.ClientModule.provideRxCache(ClientModule.java)

### ISSUE THREAD

**Issue by tulongchao** [JessYanCoding/MVPArms#187]
MVPArms Version:  v2.3.1
 AndroidStudio Version: v3.0.0
 Gradle Plugin Version:  v3.0.1
荣耀 CHE-TL00 | Android 5.0.2,level 21,
魅族 M1 METAL | Android 5.1,level 22
华为 PE-TL20 | Android 4.4.2,level 19
这个BUG并不是在所有的机型上出现，以上的机型出现频率最高，

java.lang.RuntimeException:Unable to start activity ComponentInfo{com.lanyife.futures/com.lanyife.futures.mvp.ui.activity.MainActivity}: java.security.InvalidParameterException: File cache directory does not exist
--
2 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432)
3 ......
4 Caused by:
5 java.security.InvalidParameterException:File cache directory does not exist
6 io.rx_cache2.internal.RxCache$Builder.persistence(RxCache.java)
7 com.jess.arms.di.module.ClientModule.provideRxCache(ClientModule.java)
8 com.jess.arms.di.module.ClientModule_ProvideRxCacheFactory.get(ClientModule_ProvideRxCacheFactory.java)
9 com.jess.arms.di.module.ClientModule_ProvideRxCacheFactory.get(ClientModule_ProvideRxCacheFactory.java)
10 dagger.internal.DoubleCheck.get(DoubleCheck.java)
11 com.jess.arms.integration.RepositoryManager.obtainCacheService(RepositoryManager.java)
12 com.lanyife.futures.mvp.model.MainModel.getMainData(MainModel.java)
13 com.lanyife.futures.mvp.presenter.MainPresenter.requestHomeData(MainPresenter.java)
14 com.lanyife.futures.mvp.ui.fragment.MainFragment.initData(MainFragment.java)
15 com.jess.arms.base.delegate.FragmentDelegateImpl.onActivityCreate(FragmentDelegateImpl.java)
16 com.jess.arms.integration.FragmentLifecycle.onFragmentActivityCreated(FragmentLifecycle.java)
17 android.support.v4.app.FragmentManagerImpl.dispatchOnFragmentActivityCreated(FragmentManager.java)
18 android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java)
19 android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java)
20 android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java)
21 android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java)
22 android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java)
23 android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java)
24 android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java)
25 android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java)
26 android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java)
27 android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java)
28 android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java)
29 android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java)
30 android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java)
31 android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1224)
32 android.app.Activity.performStart(Activity.java:6032)
33 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2395)
34 android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2492)
35 android.app.ActivityThread.access$1200(ActivityThread.java:158)
36 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
37 android.os.Handler.dispatchMessage(Handler.java:102)
38 android.os.Looper.loop(Looper.java:135)
39 android.app.ActivityThread.main(ActivityThread.java:5564)
40 java.lang.reflect.Method.invoke(Native Method)
41 java.lang.reflect.Method.invoke(Method.java:372)
42 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
43 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

我这边首页用了缓存

**Comment by JessYanCoding** [comment]
兄弟这个情况是因为发生问题的手机, 创建缓存文件夹失败, 或者创建成功, 然后被系统删了, 这个只有你自己解决, 找到出问题机型为什么使用系统 Api **File.mkdirs()** 都不能创建文件夹, 或者自己重新指定缓存文件夹(别问在哪指定, 自己找)
