### ISSUE TITLE
Dagger 注入的常见问题

### ISSUE THREAD

**Issue by Sum41forever** [JessYanCoding/MVPArms#189]
在研究Arms种注入多个通用Persenter #181 的过程中，发现一些Dagger注入的常见问题。所以总结一下。
如果下面没有你所遇到的问题，可以提出交流。也欢迎各位在这个Issue下面加入自己解决的和Dagger2有关的问题

---

### Dagger2不生成“Dagger_”文件
清理项目，Rebuild项目，更改依赖版本，同时删除Gradle caching。

---
### bound multiple times
```java
me.jessyan.mvparms.demo.mvp.contract.TestContract.View is bound multiple times
```
1. component关联的（n个或者1个）module中有重复的provider
1. component A有dependencies的component B，A关联的Module A中有provider，component B关联的Module B中也有provider，且在component B中暴露出来了（不暴露不影响）
---
### Types may only contain one @Inject constructor.
一个类的构造函数只能有一个有@inject

---
###  cannot be provided without an @Inject constructor or from an @Provides-annotated method
1. 没有provider或者inject
2. 如果component含有dependencies，可能没有向外面暴露。
 (特别是注入多个Persenter 比如这个issue #22 )
```java
Error:(39, 10) 错误: me.jessyan.mvparms.demo.mvp.contract.UserContract.Model cannot be provided without an @Provides-annotated method.
```
---
###  may not reference scoped bindings
dagger 要求依赖的 Component 和当前 Component 必须是不一样的 Scope，如果依赖的 component 超过一个, 他们的 Scope 还必须一样

1. component的dependencies与component自身的scope不能相同，即组件之间的scope不同
2. Singleton的组件不能依赖其他scope的组件，只能其他scope的组件依赖Singleton的组件。
没有scope的不能依赖有scope的组件，
3. 一个component不能同时有多个scope(Subcomponent除外)
---
###  找不到语法的错误. 但就是报错
1. @inject注入的对象的泛型没有指定  [Dagger2找不到符号的原因总结](http://blog.csdn.net/z1020573553/article/details/70156810)

---

> JessYanCoding：dagger 要求每个 Component 都必须提供当前类里面被@inject 修饰的所有对象。
所以，如果一个类，里面这个@inject 被一个component 提供，另外一个@inject 被另外一个component 提供是不行的，必须两个component 都能独立完成这两个@inject 的注入。所以也间接的规定一个类里面只能允许一个component 的存在，想重用component 只能通过依赖的方式,这也进一步解释了依赖component 的作用

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/MVPArms/wiki/Issues#1

**Comment by DexterLin007** [comment]
**[Dagger/DependencyCycle] Found a dependency cycle**
Dagger的依赖注入出现重复注入

**Comment by JessYanCoding** [comment]
@DexterLin007 重复注入，是你自己依赖的问题，只有你自己处理。
