### ISSUE TITLE
提个泛型继承问题

### ISSUE THREAD

**Issue by wanglg** [JessYanCoding/MVPArms#196]
就是在框架使用的时候一般项目都会自己的BaseActivity，这时候就需要自己的BaseActivity继承框架的BaseActivity，然而到具体Activity的时候发现会指定不了具体的Presenter，不知道怎么解决的

**Comment by JessYanCoding** [comment]
不知道你说的什么意思

**Comment by wanglg** [comment]
看你demo中，UserActivity只有一重继承关系，比如我还有个Activity继承UserActivty，这种情况怎么指定泛型类型啊

**Comment by JessYanCoding** [comment]
贴代码

**Comment by wholwh** [comment]
干嘛要继承,把自己的BaseActivity里的东西提取到框架里的BaseActivity,然后业务Activity继承框架里的BaseActivity就好了.

**Comment by JessYanCoding** [comment]
@wholwh 为什么不自己的 BaseActivity 继承框架里的 BaseActivity, 然后业务 Activity 继承自己的 BaseActivity, 只要才符合开闭原则, 也让业务和基础模块划分的详细

**Comment by wanglg** [comment]
@JessYanCoding 我一开始就是这样做的啊，发现在业务Activity中无法指定具体的Presenter，你可以试试

**Comment by JessYanCoding** [comment]
如何指定范型, 和声明范型, 建议自己百度下

**Comment by wanglg** [comment]
我肯定是百度过的，子类是可以指定父类的
`public class Father<V extends View> {
    V v;
}`
``public` class Son extends Father<ImageView> {

    public void test() {
        v.setImageBitmap(null);
    }
}`
`public class GrandSon extends Son {
}`
在GrandSon 中如何可以指定Father中v的类型的，可能水平太次，确实没找到方法

**Comment by JessYanCoding** [comment]
看了你上面的代码, 果然和我之前猜测的一样, 所以我上面让你百度下如何声明范型, 你在 **Son** 里面已经都把 **Fathe**r 的范型指定死了, 指定为 <ImageView>, 最底部的子类 **GrandSon** 当然就不能再次指定 **Father** 的范型, 你应该在 **Son** 再次声明范型, 达到传递范型的作用

```java

public class Son<V extends View> extends Father<V> {

}

public class GrandSon extends Son<ImageView> {

}
```

说真的这个问题够基础的,  算是 **Java SE** 基础语法的问题, 百度真是一大把, 本不想在 **Issues** 中回答的, 不然会有更多人想都不想就提这类 **Issues**, 算是破例, 下次学会自己解决此类问题
