### ISSUE TITLE
Fragment对应的Presenter中使用@Inject注解的RxErrorHandler等对象获取为null

### ISSUE THREAD

**Issue by AngkiZ** [JessYanCoding/MVPArms#199]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment

- [x] MVPArms Version: 2.3.5
- [x] AndroidStudio Version: 3.0.1
- [x] Gradle Plugin Version: 4.1
- [x] Target Android Version: 5.0；6.0；7.0
- [x] Device Model: 

### Bug Description:
在一个Activity中有几个Fragment，Fragment不使用同一套Module，Component，Presenter，Model，Contract，也不和Activity使用一样的。在Fragment对应的Presenter中使用@Inject获取RxErrorHandler，Application等对象为null。出现这个问题是使用姿势不对还是在Activity中的Fragment必须使用Activity的Module和Component等。

### Related Code:
```java
 其中一个Fragment的Presenter：
@FragmentScope
public class POne extends BasePresenter<IFCO.IFCOModel, IFCO.IFCOView>{

    @Inject
    RxErrorHandler mErrorHandler;
    @Inject
    Application mApplication;
    @Inject
    ImageLoader mImageLoader;
    @Inject
    AppManager mAppManager;


    @Inject
    public POne(IFCO.IFCOModel model, IFCO.IFCOView view) {
        super(model, view);
    }

    /**
     * 绑定生命周期
     */
    @OnLifecycleEvent(Lifecycle.Event.ON_CREATE)
    void onCreate() {
        LogUtils.e(mErrorHandler);
        //打开页面自动加载数据
        init();
    }

    public void init() {
       略...
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        this.mErrorHandler = null;
        this.mAppManager = null;
        this.mImageLoader = null;
        this.mApplication = null;
    }
}

```

### Bug Log:
```log
log打印为null

```

**Comment by JessYanCoding** [comment]
这些单例对象都是 AppComponent 提供的, 你使不使用 Activity 的 Component 和这里没有什么关系, Dagger 的问题, 无非就是使用的方式没符合它的规则造成的, 都是死东西, 就是按既定的规则去生成需要的代码, 所以这些问题都自行解决

**Comment by AngkiZ** [comment]
尴尬，刚发现问题，就是在绑定生命周期这@OnLifecycleEvent(Lifecycle.Event.ON_CREATE)，当ON_CREATE时获取的就是null。。

**Comment by JessYanCoding** [comment]
生命周期？

**Comment by MartinDong** [comment]
使用Fragment同样遇到了问题，希望卤煮可以放个demo带网络请求的那种，感激

**Comment by JessYanCoding** [comment]
https://github.com/xiaobailong24/MVPArms_Fragment

**Comment by arronvera** [comment]
> 尴尬，刚发现问题，就是在绑定生命周期这@OnLifecycleEvent(Lifecycle.Event.ON_CREATE)，当ON_CREATE时获取的就是null。。

请问你怎么解决的？

**Comment by arronvera** [comment]
> 尴尬，刚发现问题，就是在绑定生命周期这@OnLifecycleEvent(Lifecycle.Event.ON_CREATE)，当ON_CREATE时获取的就是null。。

谢谢  多亏你的提醒，我也是出现了一样的问题，终于解决了

**Comment by asd821300801** [comment]
> > 尴尬，刚发现问题，就是在绑定生命周期这@OnLifecycleEvent(Lifecycle.Event.ON_CREATE)，当ON_CREATE时获取的就是null。。
> 
> 谢谢 多亏你的提醒，我也是出现了一样的问题，终于解决了

要把这段注解注释掉吗？还是把ON_CREATE改成其他？

**Comment by AngkiZ** [comment]
> > > 尴尬，刚发现问题，就是在绑定生命周期这@OnLifecycleEvent(Lifecycle.Event.ON_CREATE)，当ON_CREATE时获取的就是null。。
> > 
> > 
> > 谢谢 多亏你的提醒，我也是出现了一样的问题，终于解决了
> 
> 要把这段注解注释掉吗？还是把ON_CREATE改成其他？

不涉及到需要注入的那些对象可以用ON_CREATE，涉及到的话建议手动调

**Comment by afckd** [comment]
已解决

**Comment by afckd** [comment]
如果是activity 关联 fragment 不能在 @OnLifecycleEvent(Lifecycle.Event.ON_CREATE)里面获取，单独的activity可以
