### ISSUE TITLE
关于IView处理列表如何再进行多一步封装？

### ISSUE THREAD

**Issue by magic0908** [JessYanCoding/MVPArms#200]
项目中很多地方只需要单纯显示列表，每个列表都有下拉刷新、上拉加载更多、加载完成、加载错误等等的UI，框架中每个View都需要继承IView。我写一个IBaseListView extends IView，然后把上面的几个常用方法写出来，以后如果是单纯显示列表的时候就可以直接继承IBaseListView。但是遇到一个问题，每个列表的数据类型是不一样的，比如一个是List<User>，另一个是List<News>，如果我在IBaseListView 
定义一个void setData(List<T>)方法，然后在activity最后设置数据的时候，只是拿到一个List，没有具体的数据类型。

**Comment by JessYanCoding** [comment]
你明显没有在 IBaseListView 接口上声明这个 T,  以及在 IBaseListView 子接口中指定这个 T 的类型, 做了这两步后 Activity 实现 IBaseListView 子接口, 它的 setData(List<T>) 方法中的 T 自然就会变成 IBaseListView 子接口中指定的这个 T 的类型, 至于范型相关知识请百度
