### ISSUE TITLE
新版ImageLoader在自定义ImageView控件上图片加载不出来

### ISSUE THREAD

**Issue by sunzqAndroid** [JessYanCoding/MVPArms#201]
新版http包下的ImageLoader，在使用自定义ImageView（CircleImageView）时，图片显示不出来。而老版本widget包下的ImageLoader能够正常显示。

额外问个问题：想单独实例化一个widget包下的ImageLoader，有没有这样的方式？

**Comment by JessYanCoding** [comment]
**ImageLoder** 只是包装了图片请求框架(默认使用 **Glide**), 实际请求是调用图片请求框架的 **API**, 所以具体能否请求成功和 **ImageLoder** 与 *Arms* 都没有关系,** 是图片请求框架的问题, 可以用最新的 **Glide** 试试

想实例化就自己 new, 想切换图片请求框架或者更改图片请求框架的请求方式看文档

**Comment by sunzqAndroid** [comment]
我直接用glide加载是可以加载出来的，或者把自定义控件换成普通的ImageView也可以加载出来。
相同的自定义控件，在另一个项目里用的历史版本的imageloader，可以加载出来

**Comment by JessYanCoding** [comment]
那你就自定义 **BaseImageLoaderStrategy**, 这些都提供了接口扩展的, 默认不行就用自己扩展

**Comment by sunzqAndroid** [comment]
测试了下，自带的GlideImageLoaderStrategy类里transition(DrawableTransitionOptions.withCrossFade())，设置淡入淡出效果导致图片在自定义控件上不能显示

**Comment by JessYanCoding** [comment]
好的, 下个版本, 默认实现类会移除所有对 UI  的默认配置, 全部由外部控制

**Comment by FlyArthur** [comment]
@sunzqAndroid 同遇到

**Comment by sunzqAndroid** [comment]
我也没有真正解决，只是去掉了fade效果
