### ISSUE TITLE
Icon/Logo Proposal

### ISSUE THREAD

**Issue by loydjayme25** [JessYanCoding/MVPArms#205]
Hello, I am a graphics designer and i am willing to make a logo/icon for your project.

**Comment by JessYanCoding** [comment]
sure you can

**Comment by loydjayme25** [comment]
how about this one ? I am open for any suggestions 

![proposals](https://user-images.githubusercontent.com/37318022/40173441-71663942-5a04-11e8-9af1-d3aa960b9044.png)

**Comment by JessYanCoding** [comment]
I want to design a logo related to **Arms**

**Comment by loydjayme25** [comment]
okay sir, i will do it.

**Comment by loydjayme25** [comment]
if you have any suggestions about how will the design will look like, that would be very okay sir if you can give so that i can imagine what is your perspective about the logo.

**Comment by JessYanCoding** [comment]
like this [logo](https://raw.githubusercontent.com/JessYanCoding/MVPArms/master/image/arms_logo_v1.0.jpg)

**Comment by loydjayme25** [comment]
![proposals](https://user-images.githubusercontent.com/37318022/40245883-6daffc16-5af9-11e8-987d-aa5d30c3f4c9.png)

**Comment by JessYanCoding** [comment]
Thank you very much for your work, but I decided to use my friend's logo, thx.
