### ISSUE TITLE
recylerview实现多种type

### ISSUE THREAD

**Issue by wangchang163** [JessYanCoding/MVPArms#21]
作者封装了defaultadapter，但是这可以用于item布局相同的列表，在item 布局不同的列表就没法在用defaultadapter，而现在的项目中很多都是多type的recylerview，希望作者考虑一下

**Comment by JessYanCoding** [comment]
github上面已经提供很多类似的库,adapter我只是做了简单封装应对最简单的需求,关于ui的东西,作为通用框架,本框架都不会封装关于ui的东西

**Comment by jp1017** [comment]
@wangchang163 可以参考这个: https://github.com/drakeet/MultiType

**Comment by JessYanCoding** [comment]
上面这个库不错,应该可以满足你的需求,每个项目对ui的需求都不一样,我不能为了某个人的需求,将ui封装进框架,ui本身是变动最大的东西,如果封装过多,使很多不需要此ui的开发者引入,影响开发者体验,增加包的体积
