### ISSUE TITLE
Android Studio3.1.3 app build.gradle出现错误

### ISSUE THREAD

**Issue by lp377762984** [JessYanCoding/MVPArms#211]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment

- [x] MVPArms Version:2.4.1 
- [x] AndroidStudio Version: 3.1.3
- [x] Gradle Plugin Version: 3.1.2
- [x] Target Android Version: no
- [x] Device Model: no

### Related Code:
```java
  

```

### Bug Log:
```log
Failed to resolve: common
Open File
Failed to resolve: common
Open File
以上4行是控制台输出
Open File 打开的文件时build.gradle，但是没有具体的错误。
注：Android Studio 3.1.3强制使用gradle4.4及4.4以上。不知道跟gradle是否有关系。

### Others:

**Comment by JessYanCoding** [comment]
你好, 我把 AS 升到 3.1.3, [Gradle 插件也升到了 3.1.3](https://github.com/JessYanCoding/MVPArms/commit/1fb66d0b2bd18b295d3aab0a3df676e9613e16ce), 并没有发现有什么问题

你这个问题就如同你说的和 AS 或者 Gradle 有关, 但和框架并没有什么关系

**Comment by lp377762984** [comment]
谢谢作者，我会继续测试。看看问题到底出在哪里。

**Comment by lp377762984** [comment]
我依然没有找出原因，但是项目莫名奇妙地好了。我只是pull了一下，然后点击了一下gradle中的try again。

**Comment by JessYanCoding** [comment]
... , AndroidStuido 就是这样

**Comment by lp377762984** [comment]
现在已经知道原因 (注意是自己的项目不是demo)
将 project build.gradle中的
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }//RxCache 需要 jitpack 仓库
        maven { url "https://maven.google.com" }//Support-library 需要 Google 仓库
        google() //AndroidStudio v3.0 可以使用 google() 替代 maven { url "https://maven.google.com
    }
}
改为
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
可以解决以上问题，因为这三个仓库是有优先级的。

**Comment by JessYanCoding** [comment]
对，我上个星期，在 travis 平台上也意识到了这个问题，已经把 google() 放到了 jcenter() 前面
