### ISSUE TITLE
我基于mvpArms进行修改

### ISSUE THREAD

**Issue by candebbs** [JessYanCoding/MVPArms#213]
我clone下来代码，然后在`settings.gradle`去掉了`':arms'`，然后在app的`build.gradleimplementation` 打开`'me.jessyan:arms:2.4.1'`，gradle，报以前下的错：
错误: 找不到符号
符号:   类 IntelligentCache
位置: 程序包 com.jess.arms.integration.cache

me.jessyan.mvparms.demo.app.IntelligentCache找不到。而这个类是在arms的module中的。

找不到这个类，请问怎么回事？

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/MVPArms/wiki/Issues#2

**Comment by cocowobo** [comment]
1.首先查看github上2.4.1的代码me.jessyan.mvparms.demo.app.IntelligentCache这个类是不存在的，daemo中就是不存在的，你找不到很正常。
2.其二：不存在的类，谁又会需要他？你考虑一下
3.其三：IntelligentCache类是什么类，搜不到这个类，你制造的还是历史代码遗留下来的你考虑过没有
4.建议：重新down代码注意下载2.4.1的。而不是作者每天更新的未发布成正式版的代码。当然，如果你确信你使用的2.4.1 代码，那就请你重新down一份使用beyond compare 工具对比一下代码
