### ISSUE TITLE
MVPArms-Module-Template不能再as 3.1.3 中使用

### ISSUE THREAD

**Issue by kkfd008** [JessYanCoding/MVPArms#214]
MVPArms-Module-Template不能再as 3.1.3 中使用

**Comment by JessYanCoding** [comment]
AS 3.1.10 更新当天，我已经测试了我的所有模板，都可以使用

如果你这样提问的话，我是不能帮你解决问题的，因为我根本不知道错误是什么

**Comment by Roc-egg** [comment]
**AS-3.1.3中使用MVPArmsTemplate新建项目，再使用MVPArms-Module-Template创建Module关联之后报错如下**

![ro 41q9pz78q u0 e fn1n](https://user-images.githubusercontent.com/15016163/42499658-ef91fc84-8461-11e8-82f2-397b1f903c35.png)

**Comment by Roc-egg** [comment]
**AS-3.1.3中使用MVPArmsTemplate新建项目，再使用MVPArms一模块模板创建模块关联之后报错如下**
![ro 41q9pz78q u0 e fn1n](https://user-images.githubusercontent.com/15016163/42499988-bd0069da-8462-11e8-9a7b-186153197e68.png)
