### ISSUE TITLE
如何拓展AppComponent

### ISSUE THREAD

**Issue by pengbs** [JessYanCoding/MVPArms#218]
我想将room数据库也提供成全局单例DbComponent，但是引用的时候总是报错如下:
depends on more than one scoped component:
@Singleton com.jess.arms.di.component.AppComponent
@Singleton com.ultron.wallet.app.di.component.DbComponent
如何解决比较好呢?

**Comment by JessYanCoding** [comment]
你自己像 AppComponent 一样，在 Application 初始化时自己构建一个 Component 如 ApplicationComponent (里面放你需要提供给项目的单例类)，然后提供一个方法返回这个 ApplicationComponent 即可，在项目中拿到 Application 对象就可以拿到 ApplicationComponent 中单粒类，和 AppComponent 的用法一样，AppComponent 现在没有官方的扩展方式，因为暂时没有更好的办法解决扩展的问题，所以现在需要自己按上面的方式去实现

**Comment by pengbs** [comment]
好的，非常感谢

**Comment by hmpfeng** [comment]
可以直接通过修改源码来达成效果吗，构建一个需要提供项目的Module然后添加到AppComponent
