### ISSUE TITLE
项目中使用AdapterViewPager类会出现跳转bug

### ISSUE THREAD

**Issue by yogkin** [JessYanCoding/MVPArms#219]
### Related Code:
```java
  @Override
    public Object instantiateItem(ViewGroup container, int position) {
        Fragment f = (Fragment) super.instantiateItem(container, position);
        View view = f.getView();
        if (view != null)
            container.addView(view);
        return f;
    }

    @Override
    public void destroyItem(ViewGroup container, int position, Object object) {
        View view = mList.get(position).getView();
        if (view != null)
            container.removeView(view);
    }



```

## 分析原因
当切换viewpager会执行上面的2个方法，如果执行了destroyItem() 则在页面跳转时候（比如跳转到其他Activity）会发生crash
原因应该是 viewpager会在跳转前执行removeViews（）方法，导致NullPointerException 不知道我分析得对不对
最后感谢作者提供这么好的框架给我们学习

### Bug Log:
```log
![image](https://user-images.githubusercontent.com/13175725/43335966-ca142a46-9202-11e8-8b2a-ad1b540e578c.png)

```

**Comment by JessYanCoding** [comment]
你截图并没有截出真正的报错位置，你说的空指针，那就截图具体报空指针的位置

你是使用的 Activity.startActivity() 跳转到其他 Activity，和 Fragment 以及 AdapterViewPager 都没什么关系，你为什么会将错误定位到 AdapterViewPager 这个类上，如果 AdapterViewPager 有报错就请截图

如果确定报错在 AdapterViewPager 中，那就请不使用 AdapterViewPager，使用他的父类 FragmentStatePagerAdapter 自行实现，看是否还是有同样的报错，如果还有报错说明不是 AdapterViewPager 的问题，需要自行排除是否是自己业务引起的原因

**Comment by yogkin** [comment]
嗯，在AdapterViewPager移除这两个方法之后正常了

**Comment by JessYanCoding** [comment]
AdapterViewPager 的具体报错位置？

**Comment by yogkin** [comment]
![image](https://user-images.githubusercontent.com/13175725/43355554-c473e160-9290-11e8-9d2c-08f1d598137c.png)

**Comment by yogkin** [comment]
#134

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/MVPArms/commit/cf239c4ea63aa85844dde7212e19400a806afd58
