### ISSUE TITLE
Presenter重用问题

### ISSUE THREAD

**Issue by jp1017** [JessYanCoding/MVPArms#22]
我现在有一个MainFragment, 里面有很多操作, 有登录, 获取消息。而登录和获取消息分别对应两个Persenter, 登录Persenter里有三个接口, 获取消息Presenter里面有两个接口。

MainFragMent用到了登录Presenter里的一个接口, 用到了获取消息Presenter里面的一个接口。

我现在的做法是把消息Presenter里的那个接口写到了登录Presenter里面, 这样MainFragment就可以使用了，感觉不好，以后接口多了的话，不好玩，

第二种方法就是和上面一样，登录的写入消息Persenter
第三种就是新建一个Presenter, 包含公用的两个接口

感觉都不好啊

请问如何优雅的处理。

**Comment by JessYanCoding** [comment]
你说的接口，应该是presenter持有的view接口，接口最小化，你不应该为了少实现把不同的东西写到一个接口里，还有写程序看远点，你现在的做法只是为了当前这个页面当前这个需求，强制的做一些调整，以后其他页面也需要这些presenter呢，又改接口？

**Comment by jp1017** [comment]
Presenter持有的Model的接口，现在的是下面这样定义的：

```
public interface PushMsgContract {
    //对于经常使用的关于UI的方法可以定义到 IBaseView 中,如显示隐藏进度条,和显示文字消息
    interface View extends IBaseView {
    }

    //Model层定义接口,外部只需关心model返回的数据,无需关心内部细节,及是否使用缓存
    interface Model {
        //获取推送消息
        Observable<PushMsgEntity> getPushMsg(String imei);
    }
}
```


```
public interface RegisterContract {
    //对于经常使用的关于UI的方法可以定义到 IBaseView 中,如显示隐藏进度条,和显示文字消息
    interface View extends IBaseView {
        //获取推送消息
        void getPushMsg(String msg);
    }

    //Model层定义接口,外部只需关心model返回的数据,无需关心内部细节,及是否使用缓存
    interface Model {
        //注册
        Observable<RegisterEntity> getRegister(Map<String, String> map);

        //登录
        Observable<LoginEntity> getLogin(Map<String, String> map);

        //更新密码
        Observable<PwdUpdateEntity> updatePwd(Map<String, String> map);

        //获取推送消息
        Observable<PushMsgEntity> getPushMsg(String imei);

    }
}
```

他们的使用

+ MainFragement extends BaseFragment<RegisterPresenter>
+ RegisterActivity extends BaseActivity<RegisterPresenter>
+ PushMsgActivity extends BaseActivity<PushMsgPresenter>

如何再处理下？

**Comment by JessYanCoding** [comment]
范型是只能帮你自动注入一个presenter,但是你自己可以自己注入n个presenter

**Comment by jp1017** [comment]
不会玩,,,是在MainFragment里面注入别的Persenter吗？属于Dagger2范畴？

**Comment by JessYanCoding** [comment]
我只是在base里面写了，@inject p  ，你自己在当前fragment，写@inject其他presenter不就对了

**Comment by jp1017** [comment]
在MainFragment里面加入:

>    @Inject
    public PushMsgPresenter mPushMsgPresenter;

component里面inject: 

>public interface PushMsgComponent {
        void inject(PushMsgActivity activity);
        void inject(MainFragment fragment);
}

然后编译错误:

>mvp.contract.PushMsgContract.Model cannot be provided without an @Provides-annotated method.
    void inject(MainFragment fragment);
         ^
      mvp.contract.PushMsgContract.Model is injected at
          mvp.presenter.PushMsgPresenter.<init>(model, …)
      mvp.presenter.PushMsgPresenter is injected at
          mvp.ui.fragment.MainFragment.mPushMsgPresenter
      mvp.ui.fragment.MainFragment is injected at
         di.component.RegisterComponent.inject(fragment)

**Comment by JessYanCoding** [comment]
你根本不理解dagger，component注入两个presenter，但是只依赖了一个module，这个module只提供了一个presenter需要的，view和model接口，另外一个presenter
需要的view和model你没提供出来，又@inject能不报错吗，用两个component，之前怎么builder.build.inject就怎么做，只是现在里面注入两个，你可以好好看看dagger，不要想当然得操作，你用的是我的框架，但是你如果不懂里面用法及原理，你用再好，经验再高，也只是熟练工，换其他框架，你又要重新熟练

**Comment by JessYanCoding** [comment]
你没有提供 mvp.contract.PushMsgContract.Model,dagger的文章你最好好好看看,理解下,这类问题我不可能随时都能帮你,自己解决对你来说,是最大的进步

**Comment by jp1017** [comment]
哈哈，会玩了，姿势优雅， 谢谢！

只要在 `RegisterComponent` 里面添加 `PushMsgModule`就可以了

```
@ActivityScope
@Component(modules = {PushMsgModule.class, RegisterModule.class}, dependencies = AppComponent.class)
public interface RegisterComponent {
    void inject(LoginActivity activity);

    void inject(MainFragment fragment);
}
```

**Comment by Sum41forever** [comment]
同类型Issue 简单的示例 可以参考这个Issue
[复用的Presenter 注入简单示例](https://github.com/JessYanCoding/MVPArms/issues/181)

**Comment by Sum41forever** [comment]
我昨天回去也试了你之前的那种做法，用2个Compnent来注入，但是构建能成功，文件能生成，编译就和你报一样的错误
```java
 DaggerUserComponent
                .builder()
                .appComponent(appComponent)
                .userModule(new UserModule(this))
                .build()
                .inject(this);

        //通用的P的注入
        DaggerGirlComponent
                .builder()
                .appComponent(appComponent)
                .girlModule(new GirlModule(this))
                .build()
                .inject(this);
```

```java
Error:(39, 10) 错误: me.jessyan.mvparms.demo.mvp.contract.UserContract.Model cannot be provided without an @Provides-annotated method.
me.jessyan.mvparms.demo.mvp.contract.UserContract.Model is injected at
me.jessyan.mvparms.demo.mvp.presenter.UserPresenter.<init>(model, …)
me.jessyan.mvparms.demo.mvp.presenter.UserPresenter is injected at
com.jess.arms.base.BaseActivity.mPresenter
me.jessyan.mvparms.demo.mvp.ui.activity.UserActivity is injected at
me.jessyan.mvparms.demo.di.component.GirlComponent.inject(activity)
```
