### ISSUE TITLE
一些Log日志打印的问题

### ISSUE THREAD

**Issue by imliujun** [JessYanCoding/MVPArms#220]
FragmentLifecycle 中的每个生命周期回调都打印了日志，并且还是W级别，影响观察正常日志信息。希望把这些日志打印给去掉，或者框架内的日志打印提供一个统一的开关来控制是否打印。

网络请求的日志打印使用了Timber，如果我们初始化Timber内部使用Logger进行日志打印，导致网络请求的日志每一行都带上了 Logger 的样式

**Comment by JessYanCoding** [comment]
两个问题都已解决https://github.com/JessYanCoding/MVPArms/commit/a2c0aa4ea10f6d7c0f1917cf25179f66e35e97e5
