### ISSUE TITLE
请问如何在Model里面直接注入一个ApiService

### ISSUE THREAD

**Issue by baneyue** [JessYanCoding/MVPArms#224]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment

- [x] MVPArms Version: 
- [x] AndroidStudio Version: 
- [x] Gradle Plugin Version: 
- [x] Target Android Version: 
- [x] Device Model: 

### Related Code:
```java
  

```

### Bug Log:
```log


```

### Others:
尝试在LoginModule里面通过如下方式注入，结果会报错：
1、Model代码
@Singleton
public class UserCenterModel extends BaseModel implements UserCenterMvp.Model {

    @Inject
    CASService casService;
下面省略...
2、Module代码
省略一部分代码...
    @Provides
    static CASService provideCASService(RepositoryManager repositoryManager){
        return repositoryManager.obtainCacheService(CASService.class);
    }
省略一部分代码...
3、报错
[Dagger/MissingBinding] [dagger.android.AndroidInjector.inject(T)]com.demo.mvp.model.service.CASService cannot b
e provided without an @Provides-annotated method.
4、之所以要这么做，我是想在具体业务的Module里面去注入ApiService。我也尝试在AppModule里面相同方式去注入ApiService是成功的

**Comment by JessYanCoding** [comment]
如果你需要使用 Dagger 的方式注入 ApiService 的话，建议不要使用业务的 Module 来提供 ApiService，建议创建一个单独的 Module 来提供所有 ApiService，这样业务页面只需要依赖这个 Module，可以少些重复代码

**Comment by JessYanCoding** [comment]
除非你这个业务 Module 需要将 ApiService 注入到除了 model 之外的多个对象中，否则不建议使用 Dagger 提供 ApiService，直接使用 RepositoryManager.obtainRetrofitService(Class) 方便的多
