### ISSUE TITLE
在GlobalConfiguration的builder.baseurl(Api.HOST) 设置自己的请求地址了，怎么还是默认的 https://api.github.com/

### ISSUE THREAD

**Issue by huanyuan** [JessYanCoding/MVPArms#226]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment

- [x] MVPArms Version: 
- [x] AndroidStudio Version: 
- [x] Gradle Plugin Version: 
- [x] Target Android Version: 
- [x] Device Model: 

### Related Code:
```java
  

```

### Bug Log:
```log


```

**Comment by JessYanCoding** [comment]
建议你在官方 Demo 上试试 builder.baseurl 中填写其他的 Url，如果能切换，就是你的问题

**Comment by huanyuan** [comment]
我动态添加url路径会出现地址拼接https://api.github.com/170.178.167.10:8080/forcetech/login/                             这样添加的时候@POST("170.178.167.10:8080/forcetech/login/")

**Comment by huanyuan** [comment]
哦，知道了，是没加https://前缀
