### ISSUE TITLE
这个框架默认为gson解析数据，但我请求响应回来的是xml数据，这时报200错误，请问该如何设置？即如何单独对返回来的数据进行解析

### ISSUE THREAD

**Issue by huanyuan** [JessYanCoding/MVPArms#227]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment

- [x] MVPArms Version: 
- [x] AndroidStudio Version: 
- [x] Gradle Plugin Version: 
- [x] Target Android Version: 
- [x] Device Model: 

### Related Code:
```java
  

```

### Bug Log:
```log


```

**Comment by JessYanCoding** [comment]
https://github.com/square/retrofit/wiki/Converters  看不懂就自己百度，这个和框架无关，是 Retrofit 的用法

**Comment by huanyuan** [comment]
嗯嗯我使用SimpleXml可以了，但我的项目里有xml和json两种数据啊，那该怎么协调，已经配置了xml解析方式了，在框架里又如何跳出其它方式来解析数据呢
