### ISSUE TITLE
远程依赖的方式获取的框架中缺少IntelligentCache.java这个类

### ISSUE THREAD

**Issue by hardlove** [JessYanCoding/MVPArms#229]
远程依赖的方式获取的框架（2.4.1最新版）中com.jess.arms.integration.cache包下缺少IntelligentCache.java这个类。请确认下2.4.1是否没有这个类了呢

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/MVPArms/wiki/Issues#2
