### ISSUE TITLE
退出程序可考虑EventBus或RxBus, 广播感觉有些繁琐。

### ISSUE THREAD

**Issue by jp1017** [JessYanCoding/MVPArms#23]

**Comment by JessYanCoding** [comment]
后面会修改,这些东西都不用用就可以实现

**Comment by JessYanCoding** [comment]
新增了AppManager，管理所有activity，以及在前台的activity，可以在全局任何地方,对所有activity,以及前台activity做处理,支持eventbus远程遥控, 意味着你可以在任何地方对任何activity做处理,比如在okhttp interceptor(全局处理,不用在每个activity做处理)中获取服务器超时时让前台的activity做ui响应

**Comment by jp1017** [comment]
看到了，又更新了一波啊，厉害 :small_red_triangle: :+1:
