### ISSUE TITLE
glide图片怎么进行缓存

### ISSUE THREAD

**Issue by huanyuan** [JessYanCoding/MVPArms#230]
楼主你的gilde加载图片 mImageLoader.loadImage(mAppComponent.appManager().getCurrentActivity() == null ? mAppComponent.application() : mAppComponent.appManager().getCurrentActivity(),
                GlideImageConfig
                        .builder()
                        .url(data.getAvatarUrl())
                        .imageView(mAvater)
                        .build());

我想在Glide.with(context)
                .load(url)
                .diskCacheStrategy(DiskCacheStrategy.NONE)
                .signature(new StringSignature(sigautre))
                .into(imageView);
sigautre这个字符为可以变化的时间字符来判断是否更新图片，你的框架里边没有看到有进行图片是否缓存.signature(new StringSignature(sigautre))这个方法 该怎么弄 应该不是加这个                      .isClearDiskCache()吧

**Comment by JessYanCoding** [comment]
没有的字段，自行扩展 https://github.com/JessYanCoding/MVPArms/wiki#3.4
