### ISSUE TITLE
关于动态url问题

### ISSUE THREAD

**Issue by huanyuan** [JessYanCoding/MVPArms#231]
我在请求方法里传这个@Ur参数来动态改变我的地址，地址里边含有path路径，我的代码
 @Override
    public Observable<String> getLayoutData() {
        LogTools.d("getLayoutData()====:");
        return  mRepositoryManager.obtainRetrofitService(LayoutService.class)
                .getLayoutString("http://www.tvboxgroup.com/mihua/iptv_get_ui.php",getLayoutParams());
    }

    private String getLayoutParams() {
        String params = "getlayout";
        return params;
    }

接口：
@POST
    Observable<String> getLayoutString(@Url String url, @Query("op") String layoutParams);

但请求出问题了，我使用张鸿洋的就可以成功返回数据 代码如下
    public static final String HOST = "http://www.tvboxgroup.com/mihua/iptv_get_ui.php?op=getlayout";
private void getData() {
        String json = new Gson().toJson(new Databean("68:1d:ef:0c:7e:d4"));
        Log.d("Main3Activity","getData()====json:" + json.toString());
        OkHttpUtils.post().url(HOST).addParams("getuilayout",json).build().execute(new StringCallback() {
            @Override
            public void onError(Call call, Exception e, int id) {
            }
            @Override
            public void onResponse(String response, int id) {
//                JSON.parse(response);
                Log.d("Main3Activity","getData()====response:" + response.toString());
                msg.setText(response.toString());
            }   
        });
    }

这是怎么回事啊

**Comment by JessYanCoding** [comment]
你好，根据本库 issues 规则，网络请求相关操作都与本库无关，涉及到 retrofit  的操作，至于 retrofit 的学习，请百度，精力有限不回答其他库的用法
