### ISSUE TITLE
数据的加密解密问题

### ISSUE THREAD

**Issue by onlywsw** [JessYanCoding/MVPArms#233]
因为在实际开发中，用到了俩个服务器地址，一个需要加密解密，一个不需要加密解密，还是希望在统一的地方，根据url进行区分，进行加密解密，在GlobalHttpHandler的回调onHttpResultResponse中，发生了一些未知错误，可能是在组装Response的时候，出现了代码问题，有比较好的解决方案吗

public Response onHttpResultResponse(String httpResult, Interceptor.Chain chain, Response response) {
        if (response != null && !TextUtils.isEmpty(response.request().url().host())
                && Api.BASE_URL.contains(response.request().url().host())) {
            try {

                String strBeffor = response.body().string();
                Object object = new JSONTokener(strBeffor).nextValue();
                if (object instanceof JSONObject) {
                    JSONObject data = (JSONObject) object;
                    if (data.has("code") && data.has("desc")) {

                        if (data.has("data") && !data.isNull("data")) {
                            //需要修改
                            String result = data.opt("data").toString();
                            result = DES3Utils.decryptMode(result);
                            data.put("data", result);

                        }
                        ResponseBody responseBody = ResponseBody.create(response.body().contentType(),
                                data.toString());
                        response.newBuilder().body(responseBody);
                        responseBody.close();
                        response.close();
                    }
                }

            } catch (IOException e) {
                e.printStackTrace();
            } catch (JSONException e) {
                e.printStackTrace();
            }
        }

       /* Log.e("wu", response.newBuilder().build().body().toString());
        response.newBuilder().build().body();*/
        /* 这里如果发现 token 过期, 可以先请求最新的 token, 然后在拿新的 token 放入 Request 里去重新请求
        注意在这个回调之前已经调用过 proceed(), 所以这里必须自己去建立网络请求, 如使用 Okhttp 使用新的 Request 去请求
        create a new request and modify it accordingly using the new token
        Request newRequest = chain.request().newBuilder().header("token", newToken)
                             .build();

        retry the request

        response.body().close();
        如果使用 Okhttp 将新的请求, 请求成功后, 再将 Okhttp 返回的 Response return 出去即可
        如果不需要返回新的结果, 则直接把参数 response 返回出去即可*/
        return response;
    }

**Comment by JessYanCoding** [comment]
你好，如果是框架问题，可以贴出框架的错误日志，如果是业务问题，只有你自己解决了，精力有限，业务问题，不在 Issues 的范围内
