### ISSUE TITLE
怎么和kotlin混合使用？

### ISSUE THREAD

**Issue by GhRyuJin** [JessYanCoding/MVPArms#234]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment

- [x] MVPArms Version: 
- [x] AndroidStudio Version: 
- [x] Gradle Plugin Version: 
- [x] Target Android Version: 
- [x] Device Model: 

### Related Code:
```java
  

```

### Bug Log:
```log


```

### Others:
和kotlin混合使用的时候Arouter会找不到路径

**Comment by JessYanCoding** [comment]
兄弟，这个和框架无关哈，引入 kotlin 无法就是将之前 java 的插件变为 kotlin 插件，找不到路径明显和框架是没关系的，明显是你自己没配置对 Arouter 的插件，要不你去找 Arouter，要不你在群里问问，用过 kotlin 的兄弟，我没用 kotlin 也帮不了你

**Comment by dukezhao** [comment]
后来解决了吗
