### ISSUE TITLE
demo内存占用很多，activity.finish关闭后仍被持有

### ISSUE THREAD

**Issue by zmylls** [JessYanCoding/MVPArms#235]
### Environment

- [x] MVPArms Version:运行demo前pull了一次项目，应该是最新的
- [x] AndroidStudio Version: 3.1.13和3.1.14均试过
- [x] Gradle Plugin Version: 3.1.13
- [x] Target Android Version: 
- [x] Device Model: 6.0，7.0，8.0 均用过

@JessYanCoding 您好，我现在直接给demo加了个LoginActivity,是仿照UserActivity写的。我在UserActivity中增加了一个按钮，点击之后打开LoginActivity,界面内容比较简单，只显示一个按钮。LoginActvity中点击按钮之后直接调用activity.finish()，关闭LoginActivity。这个时候回到UserActivity。但是我查看内存占用情况，还是能看到LoginActivity。我在实际项目中也碰到这样的问题。一直没有找到真正持有的LoginActivity的地方，不知道您么有碰到这样的情况。

我这里直接使用了您的demo项目，主要添加代码如下：
1、UserActivity
![image](https://user-images.githubusercontent.com/4530506/44990228-f85a8c00-afc2-11e8-8eab-6df3c47c07ed.png)

2、LoginActivity
![image](https://user-images.githubusercontent.com/4530506/44990263-1627f100-afc3-11e8-8e1e-33ef535f47d6.png)

LoginActivity就直接finish掉了，但是内存仍然能看到这个对象
![image](https://user-images.githubusercontent.com/4530506/44990449-a108eb80-afc3-11e8-8b1e-7a475819a5de.png)

以上是我的测试结果，不知道您是否有留意过这个问题。这个问题很大概率出现，而且leak几乎每次都有提示泄露，希望您可以多试两次。我找了挺久，好像都是系统的代码在引用，所以在此提一下，希望您能看看是否有什么修改建议？
另外demo每次一运行起来就占了很多内存，如图：
![image](https://user-images.githubusercontent.com/4530506/44990524-da415b80-afc3-11e8-804d-48ab601ee65d.png)

我是在最近应用程序中杀了demo，再重新打开UserActivity，其它操作都没有做的情况下截取这张图的。请您参考下，在内存这块是否还有什么优化的空间。

**Comment by JessYanCoding** [comment]
关于你说的内存占用的问题，这个群友提过，我通过 AndroidStudio 的工具，查找过的确，Demo 运行起来会占用内存，但是占用的内存大部分是 RecyclerView，Glide 等 Arms 之外的模块占用的，具体值我忘了，大概百分90多的内存都是其他模块占用的，这个你可以自己跟踪下内存的占用情况

**Comment by JessYanCoding** [comment]
关于你说的第一个泄漏问题，我暂时没遇到，其他人也没给我提过类似 isseus，你最好能截图 LeakCanary 的泄漏详情，LeakCanary 的一些与系统有关的泄漏，是无解的，可以忽略，是系统或者一些不可修改的问题导致的，这个你可以自行 google 就可以找到

**Comment by zmylls** [comment]
![screenshot_20180911-205633](https://user-images.githubusercontent.com/4530506/45361647-5f9cbf80-b605-11e8-9b15-472851c44141.jpg)
![screenshot_20180911-205657](https://user-images.githubusercontent.com/4530506/45361651-61668300-b605-11e8-808b-508bb3b815b0.jpg)
![screenshot_20180911-205708](https://user-images.githubusercontent.com/4530506/45361657-63304680-b605-11e8-9c88-9b0bbc4a0cd3.jpg)

@JessYanCoding  我这里用的是华为荣耀9，系统为8.0；还是在demo中操作，在useractivity中添加一个按钮打开一个新的activity，新activity也有一个按钮，点击后直接关闭新activity. 加的内容不多的，希望楼主有空可以试试看。

**Comment by JessYanCoding** [comment]
我没华为手机测试不了，我看是华为的 FrameWork 导致的内存泄漏，不排除是华为手机的问题，我其他手机没这问题
