### ISSUE TITLE
RequestInterceptor日志打印工具中中文带有%时URLDecode会抛出异常

### ISSUE THREAD

**Issue by dengchaoAndroid** [JessYanCoding/MVPArms#237]
抛出URLDecoder: Illegal hex characters in escape (%) pattern :异常 。新版本可以通过关闭请求日志解决这个问题，不知道有没有办法在可以打印日志的情况下解决呢。

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/MVPArms/commit/f470260fff122fcbe926f2f5998b8f3af80a77ef
