### ISSUE TITLE
该框架怎样在基类P里面做网络请求,请求返回的数据是子类P的网络请求参数？

### ISSUE THREAD

**Issue by m511386374** [JessYanCoding/MVPArms#238]
如果只是单纯在基类P里面做个网络请求是可以做到不过有点low,但是要结合框架来写就不知道怎么入手.

**Comment by JessYanCoding** [comment]
关于业务问题建议在群里讨论

**Comment by cnmao** [comment]
@JessYanCoding 你好 请问下 群是多少 
我这边遇到一个token刷新的问题 ， 帮忙看下 整了两天了  还是没办法 联系你们也找不到

**Comment by cnmao** [comment]
@JessYanCoding 18137503798 这个是我的电话  
看到后帮忙指导一下 万分感谢
