### ISSUE TITLE
少一个类

### ISSUE THREAD

**Issue by andya1985** [JessYanCoding/MVPArms#24]
import com.jess.arms.di.component.DaggerBaseComponent

DaggerBaseComponent缺少

**Comment by JessYanCoding** [comment]
编译一下就可以了  BTW：虽然本人在尽量降低本框架的门槛，但还是建议你先看下dagger的文章，编译时生成静态代码是dagger的入门常识

**Comment by andya1985** [comment]
嗯嗯，谢谢，已经踩完坑，并填好了
