### ISSUE TITLE
关于代码一键转kotlin代码的一个坑

### ISSUE THREAD

**Issue by xiejingwlin** [JessYanCoding/MVPArms#241]
在把java代码转成kotlin代码后，运行会报如下错误：
Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method 
kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter savedInstanceState

---------------------
需要把ActivityLifecycleCallbacksImpl 里面的 onActivityCreated(activity: Activity, savedInstanceState: Bundle)改成onActivityCreated(activity: Activity, savedInstanceState: Bundle?)    这个问题坑了我几个小时，在这提醒一下后来者

**Comment by JessYanCoding** [comment]
好的，这是关于空安全的问题，感谢贡献
