### ISSUE TITLE
Dagger二次继承注入的问题

### ISSUE THREAD

**Issue by TanJunDang** [JessYanCoding/MVPArms#249]
好像是二次继承Dagger注入会出问题。比如我Afragment继承BaseMvpFragment<Model,View>，此时B继承AFragment，在里面随意注入一个对象，编译就会出现父类的DaggerAComponent找不到，其实这个类是已经生成了的。只要注释掉Component里的这句void inject(BFragment f)就没错了。但是这样B的Dagger就无法生成。。。请问这个怎么解决啊。

**Comment by xiaobailong24** [comment]
@TanJunDang 代码贴出来看下。Dagger 的 inject 不支持继承。

**Comment by TanJunDang** [comment]
不支持继承就行了，那就是了。
