### ISSUE TITLE
ButterKnife 问题

### ISSUE THREAD

**Issue by maoruibin** [JessYanCoding/MVPArms#25]
在 Base 类里 
```java
mUnbind = ButterKnife.bind(this);
```

后 为什么在 子 Activity 中 
```java
@BindView(R.id.activity_main)
FrameLayout activityMain;
```

activityMain 会为空，很奇怪！会是什么问题

**Comment by JessYanCoding** [comment]
必须在initData里调用,才能确保注入完毕

**Comment by maoruibin** [comment]
找到原因了，Butterknife 配置姿势不对，如果是在 lib 中使用需要进行额外的配置，否则可能无法使用注解，https://github.com/JakeWharton/butterknife#library-projects

thanks for your response!

**Comment by JessYanCoding** [comment]
嗯,当前lib如果要使用必须在当前lib的build.gradle中引入apt
