### ISSUE TITLE
关于RepositoryManager的优化

### ISSUE THREAD

**Issue by NeVaDaAAA** [JessYanCoding/MVPArms#250]
框架很好用，我最近刚好看了一篇关于Retrofit优化的文章
https://zhuanlan.zhihu.com/p/40097338
可否将此优化加入框架中呢？

以下是我尝试优化的代码
/**
     * 根据传入的Class获取对应的Retrofit service
     */
    public synchronized <T> T obtainRetrofitService(Class<T> service) {
        return createWrapperService(service);
    }

/**
     * 根据 https://zhuanlan.zhihu.com/p/40097338 对 Retrofit 进行的优化
     *
     * @param serviceClass ApiService class
     * @param <T>          ApiService class
     * @return ApiService
     */
    public <T> T createWrapperService(final Class<T> serviceClass) {
        return (T) Proxy.newProxyInstance(serviceClass.getClassLoader(),
                new Class<?>[]{serviceClass}, new InvocationHandler() {
                    @Override
                    public Object invoke(Object proxy, final Method method, @Nullable final Object[] args) throws Throwable {
                        if (method.getReturnType() == Observable.class) {
                            // 如果方法返回值是 Observable 的话，则包一层再返回
                            return Observable.defer(new Callable<ObservableSource<T>>() {
                                @Override
                                public ObservableSource<T> call() throws Exception{
                                    final T service = getRetrofitService(serviceClass);
                                    // 执行真正的 Retrofit 动态代理的方法
                                    return ((Observable) getRetrofitMethod(service, method)
                                            .invoke(service, args))
                                            .subscribeOn(Schedulers.io());
                                }
                            }).subscribeOn(Schedulers.single());
                        }
                        // 返回值不是 Observable 的话不处理
                        final T service = getRetrofitService(serviceClass);
                        return getRetrofitMethod(service, method).invoke(service, args);
                    }
                });
    }

**Comment by NeVaDaAAA** [comment]
![image](https://user-images.githubusercontent.com/20659340/48185630-9e829380-e370-11e8-9266-0a29803c896c.png)

**Comment by JessYanCoding** [comment]
感谢分享，这个优化，两个月前已经有人提交了 https://github.com/JessYanCoding/MVPArms/pull/228/files
