### ISSUE TITLE
能否将dagger-android 整合进去，避免Component的重复创建

### ISSUE THREAD

**Issue by ncworm** [JessYanCoding/MVPArms#260]
如题

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/MVPArms/issues/40#issuecomment-419343336  可以看看这里，Dagger.android 用的是 subComponent，需要在父类 Component 中声明子类 Component，框架中的父类 Component AppComponent，是在框架中远程提供，我是无法知道你的子类业务 Component 有哪些，你也无法向 AppComponent 添加代码，所以 Dagger.android  是需要你自己去做处理的
