### ISSUE TITLE
从2.4.1升级到2.5.0以后GlideArms的into方法没了???????????

### ISSUE THREAD

**Issue by z2700589** [JessYanCoding/MVPArms#261]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment

- [x] MVPArms Version: 
- [x] AndroidStudio Version: 
- [x] Gradle Plugin Version: 
- [x] Target Android Version: 
- [x] Device Model: 

### Bug Description:

从2.4.1升级到2.5.0以后GlideArms的into方法没了???????????

### Related Code:
```java
                      GlideArms.with(this).load(fileUri.getAbsolutePath()).centerCrop().into(task_img_mater_photo);


```

### Bug Log:
```log


```

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/MVPArms/blob/master/arms-imageloader-glide/src/main/java/com/jess/arms/http/imageloader/glide/GlideImageLoaderStrategy.java#L119
