### ISSUE TITLE
GlobalHttpHandlerImpl问题

### ISSUE THREAD

**Issue by NerdAnonymous** [JessYanCoding/MVPArms#262]
如何让Glide的请求不被拦截

**Comment by JessYanCoding** [comment]
并没有拦截，只是打印了请求信息

**Comment by NerdAnonymous** [comment]
@JessYanCoding 我加载图片的时候他是真的拦截了 我打的断点 ...在onHttpRequestBefore（）中

**Comment by NerdAnonymous** [comment]
全局中这个拦截确实是拦截了Glide中的OKhttp请求

**Comment by NerdAnonymous** [comment]
我现在是在onHttpRequestBefore中添加了一些公共参数，但是我希望在加载图片的时候不进这个拦截器，有办法么 大佬

**Comment by JessYanCoding** [comment]
框架中 Glide 使用的是 OKhttp 进行的网络请求，OKhttp 的所有请求当然都会经过这个拦截器，有两种方法可以解决你的问题
第一个方法是，在拦截器中区分是 Glide 的请求，还是普通的网络请求，怎么区分？可以通过请求头中的 ContentType，可以参考框架中，[区分请求类型](https://github.com/JessYanCoding/MVPArms/blob/master/arms/src/main/java/com/jess/arms/http/log/RequestInterceptor.java#L133)，来打印信息的代码

第二个方法是，Glide 切换为其他的网络请求框架

**Comment by huangruiLearn** [comment]
@NerdAnonymous   怎么解决了
