### ISSUE TITLE
该框架如何实现retrofit baseurl的切换

### ISSUE THREAD

**Issue by urtheone** [JessYanCoding/MVPArms#267]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment

- [x] MVPArms Version: 
- [x] AndroidStudio Version: 
- [x] Gradle Plugin Version: 
- [x] Target Android Version: 
- [x] Device Model: 

### Related Code:
```java
  

```

### Bug Log:
```log


```

**Comment by jsd01** [comment]
![image](https://user-images.githubusercontent.com/30396294/50439140-e31bbb80-092b-11e9-8dbe-7de075a1e12b.png)
![image](https://user-images.githubusercontent.com/30396294/50439201-1fe7b280-092c-11e9-9665-b72254fa73b0.png)
在接口中设置头参数，在Presenter中做切换
