### ISSUE TITLE
No support for androidX support library

### ISSUE THREAD

**Issue by micrologic** [JessYanCoding/MVPArms#268]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment

- [x] MVPArms Version: 
- [x] AndroidStudio Version: 
- [x] Gradle Plugin Version: 
- [x] Target Android Version: 
- [x] Device Model: 

### Related Code:
```java
  

```

### Bug Log:
```log


```

**Comment by JessYanCoding** [comment]
由于个人精力有限，本人只会保证又一个稳定版本的持续维护，不会存在第二个分支版本，框架使用 androidX 后，即代表放弃含有 support 包版本的维护，而修改 androidX 会将整个项目的所有 support 包名替换，增加很多工作量，影响大量老旧项目，所以我只会在 androidX 大量普及后，接入 Arms，如果你很需要的话，建议自行修改，现在暂时只能保证大部分用户的利益

**Comment by yuandonghua** [comment]
@micrologic 把你的方案发出来看看，谢谢

**Comment by JessYanCoding** [comment]
https://mp.weixin.qq.com/s/XeJQrwbxKk6JbBn8C3fqKg
