### ISSUE TITLE
BaseFragment 为什么不加一个懒加载的功能

### ISSUE THREAD

**Issue by candebbs** [JessYanCoding/MVPArms#269]
在main页，有四个fragment，经常需要懒加载的，BaseFragment应该加上来支持懒加载。

**Comment by walkthehorizon** [comment]
懒加载在arm中可以有多种方式实现，比如[这里](https://github.com/JessYanCoding/MVPArms/tree/2.4.1to2.5.0)我就增加一个固定的BaseLazyLoadFragment实现懒加载，并让BaseFragment继承，当然你也可以自定义一个独立的LazyLoadFragment，在需要使用懒加载的Fragment时让其继承LazyLoadFragment即可，但是此时你要么让LazyLoadFragment继承于BaseFragment，要么完全重写一个BaseLazyLoadFragment在需要的位置使用即可。

**Comment by candebbs** [comment]
找不到BaseLazyLoadFragment，但自己实现了。
