### ISSUE TITLE
# 使用Arms，glide升级为4.9报错

### ISSUE THREAD

**Issue by snowf07** [JessYanCoding/MVPArms#278]
java.lang.NoSuchMethodError: No super method apply(Lcom/bumptech/glide/request/RequestOptions;)Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears in /data/app/com.yanjing.voice-2/base.apk:classes38.dex)
        at com.jess.arms.http.imageloader.glide.GlideOptions.apply(GlideOptions.java:604)
        at com.jess.arms.http.imageloader.glide.GlideRequests.setRequestOptions(GlideRequests.java:168)

**Comment by JessYanCoding** [comment]
编译报错还是运行报错，我这里没问题啊

**Comment by snowf07** [comment]
> 编译报错还是运行报错，我这里没问题啊

runtime

**Comment by JessYanCoding** [comment]
看下是不是 Glide v4.9 的某些 API 修改了，导致了框架不兼容，如果是，只能等框架下个版本修复

**Comment by LinXueyuanStdio** [comment]
我也遇到了这问题，坐等修复（吃瓜

**Comment by JessYanCoding** [comment]
Arms 已更新

**Comment by brivelee** [comment]
我的用Arms 2.5.0也是这个问题

**Comment by JessYanCoding** [comment]
@brivelee 用最新版，最新版不是2.5.0
