### ISSUE TITLE
最新的项目更新了，包的分类

### ISSUE THREAD

**Issue by zjllh** [JessYanCoding/MVPArms#28]
大神，您最新的项目更新了，包的分类，为什么model包里还要有aPi和entity包，问什么不和model分开来处于同一级上。
还有一个问题请教，您说过，写新项目，最好直接在开源项目里写，那您的项目更新了，像这次归类到common里去，那我不是要原来项目全部重新复制、粘贴，复制、粘贴了吗？您有什么方法可以减少这种功夫消耗？

**Comment by jp1017** [comment]
arms可以编译成aar库，群主更新时大部分就是更新arms，到时候重新编译下就ok :smile:
