### ISSUE TITLE
后台返回复杂Json 格式 gosn Factory 无法正常解析，必须自定义FastJson 这样点话就和博主点建议冲突了，忘给个解决方法。

### ISSUE THREAD

**Issue by liuxuesong001** [JessYanCoding/MVPArms#282]
builder
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())//使用 Rxjava
                .addConverterFactory(GsonConverterFactory.create(gson));//使用 Gson
------------------------------------------------------------------------------------------
.retrofitConfiguration((context1, retrofitBuilder) -> {//这里可以自己自定义配置 Retrofit 的参数, 甚至您可以替换框架配置好的 OkHttpClient 对象 (但是不建议这样做, 这样做您将损失框架提供的很多功能)
                                                            //retrofitBuilder.addConverterFactory(FastJsonConverterFactory.create());//比如使用fastjson替代gson
                    retrofitBuilder.addConverterFactory(FastJsonConverterFactory.create());
                })

**Comment by jasonlee3652** [comment]
我也遇到这个问题。
我的数据json格式为：
`{"code":"200","errorCode":"SUCCESS","msg":"ok","data":{"pageNo":1,"nextPage":true,"list":[{"merchantId":"398835612519497728","storeAddr":"象角唐吉祥花园","shortName":"大众精品店","storePic":"http://img.mojivip.com/o_1ctcqgl3i110n22sdlj1cjegui7.jpg","ticket":0,"ticketActivityList":[{"ticketActivityId":"546335641642729472","ticketType":1,"discountCriteria":0,"discountValue":80,"activityLabel":"8折","endTime":"1555395759000"}]},{"merchantId":"404763118472790016","storeAddr":"坂田街道龙颈路15号","shortName":"半山烤鸡","storePic":"http://img.mojivip.com/o_1ctc2q4mv118qj681hjq3ad1r1s7.jpg","ticket":0,"ticketActivityList":[]},{"merchantId":"466987970994372608","storeAddr":"深圳市龙华新区观澜街道新田社区新田市场A区36号","shortName":"澳滋烘焙面包店","storePic":"http://img.mojivip.com/o_1ctc2tc9e61tiig1t9scb1k387.jpg","ticket":0,"ticketActivityList":[]},{"merchantId":"467259656859811840","storeAddr":"深圳市龙华新区观澜街道新田社区。新丰路左侧024号","shortName":"杜佳湘赣木桶饭","storePic":"http://img.mojivip.com/o_1ctc3s78ueur1fm5qt318gq1s667.jpg","ticket":0,"ticketActivityList":[]},{"merchantId":"469305489839095808","storeAddr":"深圳市龙岗区平湖街道新木老村文新路31号","shortName":"瑜茶","storePic":"http://img.mojivip.com/o_1ctc434mvg7qj6j17etm610187.jpg","ticket":0,"ticketActivityList":[]},{"merchantId":"471643928181866496","storeAddr":"深圳市龙华区福城街道章阁社区中港星商业广场F栋第一层F809号商铺","shortName":"祁阳米粉","storePic":"http://img.mojivip.com/o_1ctc4893p1m5211g268b1uoa6i97.jpg","ticket":0,"ticketActivityList":[]},{"merchantId":"471665551878389760","storeAddr":"深圳市龙华区福城章阁街道社区中港星商业广场F栋第一层F808号","shortName":"喜茶屋","storePic":"http://img.mojivip.com/o_1ctc4cl2j1mva1n0a1sn1vloph7.jpg","ticket":0,"ticketActivityList":[]},{"merchantId":"472019410781995008","storeAddr":"深圳市龙华新区观澜镇格澜郡商业中心A08","shortName":"三宅一生咖啡馆","storePic":"http://img.mojivip.com/o_1ctc4fvr012a0pukgpe1tj5144p7.jpg","ticket":0,"ticketActivityList":[]},{"merchantId":"472076072339374080","storeAddr":"深圳市龙华区大水坑路68-2","shortName":"简约音乐美食烤吧","storePic":"http://img.mojivip.com/o_1ctc4k8cq1hec175o44hrs610pu7.jpg","ticket":0,"ticketActivityList":[]},{"merchantId":"472816291997024256","storeAddr":"深圳市龙华新区民治街道横岭村四区59栋102","shortName":"广式云吞面馆","storePic":"http://img.mojivip.com/o_1ctc4slbsnaa1585c0b173d161b7.jpg","ticket":0,"ticketActivityList":[]}],"totalCount":14,"pageSize":10,"totalPage":2}}`

我接收这个json的泛型类

`public class BaseListResponse<T> implements Serializable {

    private ListData<T> data;
    private String code;
    private String msg;
    private String errorCode;

    public ListData<T> getData() {
        return data;
    }

    public void setData(ListData<T> data) {
        this.data = data;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public String getErrorCode() {
        return errorCode;
    }

    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }

    public class ListData<T> {
        private int pageNo;
        private boolean nextPage;
        private int totalCount;
        private int pageSize;
        private int totalPage;
        private List<T> list;

        public int getPageNo() {
            return pageNo;
        }

        public void setPageNo(int pageNo) {
            this.pageNo = pageNo;
        }

        public boolean isNextPage() {
            return nextPage;
        }

        public void setNextPage(boolean nextPage) {
            this.nextPage = nextPage;
        }

        public int getTotalCount() {
            return totalCount;
        }

        public void setTotalCount(int totalCount) {
            this.totalCount = totalCount;
        }

        public int getPageSize() {
            return pageSize;
        }

        public void setPageSize(int pageSize) {
            this.pageSize = pageSize;
        }

        public int getTotalPage() {
            return totalPage;
        }

        public void setTotalPage(int totalPage) {
            this.totalPage = totalPage;
        }

        public List<T> getList() {
            return list;
        }

        public void setList(List<T> list) {
            this.list = list;
        }
    }
}`

实体类

`public class ShopBean implements Serializable {

    private String shortName;//店铺简称
    private String storePic;//门头照
    private String storeAddr;//商铺地址
    private String merchantId;//商家Id
    private List<TicketBean> ticketActivityList;//活动券

    public String getShortName() {
        return shortName;
    }

    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    public String getStorePic() {
        return storePic;
    }

    public void setStorePic(String storePic) {
        this.storePic = storePic;
    }

    public String getStoreAddr() {
        return storeAddr;
    }

    public void setStoreAddr(String storeAddr) {
        this.storeAddr = storeAddr;
    }

    public String getMerchantId() {
        return merchantId;
    }

    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId;
    }

    public List<TicketBean> getTicketActivityList() {
        return ticketActivityList;
    }

    public void setTicketActivityList(List<TicketBean> ticketActivityList) {
        this.ticketActivityList = ticketActivityList;
    }
}`

BaseListResponse包含一个列表，这个列表元素中还包含一个列表。但是拿到的数据，Gson没有识别TicketBean这个类，将这个类转换成了 LinkedTreeMap。
报如下错误：

`ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast ShopBean`

请问这个问题是什么原因引起的?

**Comment by JessYanCoding** [comment]
@jasonlee3652   LinkedTreeMap  是 RxCache 的问题，
 https://github.com/JessYanCoding/MVPArms/wiki/Issues#16

**Comment by JessYanCoding** [comment]
@liuxuesong001 默认的 GsonConverterFactory 不能解析，就自定义一个 GsonConverterFactory 解析，不会自定义的话就百度一样，不一定只有 FastJson 才能解析某种格式

**Comment by isanwenyu** [comment]
范型嵌套的话 我一般框架解析为string类型 手动解析或是用gson/fastjson指定type解析
