### ISSUE TITLE
我除了重新构建一个okHttpclient对象外,还有其他方法动态为某一个接口重新设置超时时间吗?

### ISSUE THREAD

**Issue by 258188170** [JessYanCoding/MVPArms#283]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment

- [x] MVPArms Version: 
- [x] AndroidStudio Version: 
- [x] Gradle Plugin Version: 
- [x] Target Android Version: 
- [x] Device Model: 

### Related Code:
```java
  

```

### Bug Log:
```log


```

**Comment by 258188170** [comment]
使用反射无效

**Comment by JessYanCoding** [comment]
这是拦截器里面 chain 的方法

```java
interface Chain {
    Request request();

    Response proceed(Request request) throws IOException;

    /**
     * Returns the connection the request will be executed on. This is only available in the chains
     * of network interceptors; for application interceptors this is always null.
     */
    @Nullable Connection connection();

    Call call();

    int connectTimeoutMillis();

    Chain withConnectTimeout(int timeout, TimeUnit unit);

    int readTimeoutMillis();

    Chain withReadTimeout(int timeout, TimeUnit unit);

    int writeTimeoutMillis();

    Chain withWriteTimeout(int timeout, TimeUnit unit);
  }
```

你在拦截器里面，识别到这个需要改变超时时间的特殊接口，调用上面的方法修改超时时间即可，如何识别？你给这个接口的 url 加上一些参数，或者加上一个特殊 header，在拦截器识别到这个接口，昨完处理在把 header 剪切掉就可以，参照我的 [RetrofitUrlManager 框架](https://github.com/JessYanCoding/RetrofitUrlManager)

**Comment by yisan** [comment]
同问，根据以上描述设置如下，测试发现依旧未起作用，超时时间还是最初设置的时间。
`public class DynamicTimeoutInterceptor implements Interceptor {

    @Override
    public Response intercept(Chain chain) throws IOException {
        Request oldRequest = chain.request();
        String questUrl = oldRequest.url().toString();
        //过滤接口
        boolean isCloseApi = questUrl.contains(PayApi.API_CLOSEORDER);
        boolean isPollingApi = questUrl.contains(PayApi.API_POLLING);
        if (isCloseApi) {
            //动态设置超时
            chain.withConnectTimeout(TimeOut.CLOSE_CONNECT, TimeUnit.SECONDS);
            chain.withReadTimeout(TimeOut.CLOSE_READ, TimeUnit.SECONDS);
        } else if (isPollingApi) {
            chain.withReadTimeout(TimeOut.POLLING_READ, TimeUnit.SECONDS);
            chain.withConnectTimeout(TimeOut.DEFALT_CONNECT, TimeUnit.SECONDS);
        }
        Request newRequest = oldRequest.newBuilder()
                .method(oldRequest.method(), oldRequest.body())
                .url(oldRequest.url())
                .build();

        return chain.proceed(newRequest);
    }`

**Comment by a158684** [comment]
可以增加一个更换超时的接口吗，我在GlobalHttpHandlerImpl implements GlobalHttpHandler中的
onHttpRequestBefore中，增加了以下代码
     if (request.url().toString().contains("uploadFile")) {
            chain.withConnectTimeout(30, TimeUnit.SECONDS)
                    .withWriteTimeout(30, TimeUnit.SECONDS)
                    .withReadTimeout(30, TimeUnit.SECONDS);
        }
从okhttp3.internal.http.RealInterceptorChain的断点上来看，中间有一段我更改成了30，后面断点跑着，又被修改回去了。没找着后面修改回去的这个拦截器在哪
