### ISSUE TITLE
关于在meta-data配置GlobalConfiguration的时候加个优先级的字段的建议

### ISSUE THREAD

**Issue by isanwenyu** [JessYanCoding/MVPArms#287]
需求：根据指定的优先级按顺序插入外面module的配置

https://github.com/JessYanCoding/MVPArms/blob/9fda847dcb1cc8de9f28c510fd9f7ba0301a02a0/arms/src/main/java/com/jess/arms/base/delegate/AppDelegate.java#L79

实现思路

1. AndroidManifest的meta-data添加resource字段作为优先级

  ```
<meta-data
            android:name="me.jessyan.armscomponent.commonsdk.core.GlobalConfiguration"
            android:value="ConfigModule"
            android:resource="1"/>
```

2. 在 com.jess.arms.integration.ManifestParser#parse中根据设置的优先级排序

https://github.com/JessYanCoding/MVPArms/blob/9fda847dcb1cc8de9f28c510fd9f7ba0301a02a0/arms/src/main/java/com/jess/arms/integration/ManifestParser.java#L49

**Comment by isanwenyu** [comment]
resource & value对应的都是name的键值对 两个值无法同时取到

**Comment by JessYanCoding** [comment]
为什么关了？

**Comment by austenyad** [comment]
我要怎么保证App module 先被运行？
