### ISSUE TITLE
UserPresenter里面使用的adapte和userList和UserActivity里面使用的是同一个内存地址的吗?

### ISSUE THREAD

**Issue by HelloDearWorld** [JessYanCoding/MVPArms#289]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment

- [x] MVPArms Version: 
- [x] AndroidStudio Version: 
- [x] Gradle Plugin Version: 
- [x] Target Android Version: 
- [x] Device Model: 

### Related Code:
```java
  

```

### Bug Log:
```log


```

**Comment by JessYanCoding** [comment]
肯定是啊，如果不是同一个，Demo 中怎么能完成更新 ui 这个操作呢，自己打打断点看看
