### ISSUE TITLE
帮助:关于文件缺失

### ISSUE THREAD

**Issue by huan920924** [JessYanCoding/MVPArms#29]
你好作者:
       我需要你的帮助，我在克隆MVPArms之后发现了一个文件的缺失，但是我不知道是怎么回事，希望能得到帮助，如下是我截的图↓
![1](https://cloud.githubusercontent.com/assets/13694788/21580172/9f9b42da-d01c-11e6-973d-486d096dff78.PNG)
![2](https://cloud.githubusercontent.com/assets/13694788/21580173/9fc863b4-d01c-11e6-93f4-47a4f1e1b4e3.PNG)
![3](https://cloud.githubusercontent.com/assets/13694788/21580174/a09e1e1e-d01c-11e6-8215-fbf928ea1092.PNG)
万分感谢

**Comment by JessYanCoding** [comment]
编译下就可以了，用这个框架之前，麻烦了解下，dagger的基础知识

**Comment by jp1017** [comment]
@JessYanCoding 可以把这些常见的issue写到wiki里面 :smile:

**Comment by JessYanCoding** [comment]
其实Readme写了的,很多都不看
