### ISSUE TITLE
能支持AndroidX吗

### ISSUE THREAD

**Issue by gh1225987336** [JessYanCoding/MVPArms#294]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment

- [x] MVPArms Version: 
- [x] AndroidStudio Version: 
- [x] Gradle Plugin Version: 
- [x] Target Android Version: 
- [x] Device Model: 

### Related Code:
```java
  

```

### Bug Log:
```log


```

**Comment by JessYanCoding** [comment]
现在，还不能支持，在之前的 issues 回答过。
升级 AndroidX 没有这么简单

1. 会影响大量老项目
2. MVPArms 依赖了大量三方库，升级 AndroidX 之前，必须保证依赖的所有三方库都支持 AndroidX

光是第 2 点就不是这么容易解决的，有些库都很久没更新了

**Comment by JessYanCoding** [comment]
https://mp.weixin.qq.com/s/XeJQrwbxKk6JbBn8C3fqKg
