### ISSUE TITLE
关于框架BaseApplication，BaseActivity，BaseFragment问题？

### ISSUE THREAD

**Issue by tydqcjj** [JessYanCoding/MVPArms#297]
框架已经定义好了BaseApplication，BaseActivity，BaseFragment。
1、如果我想定义一个全局变量在BaseApplication里，怎么实现呢？
2、如果我想复写BaseActivity的dispatchTouchEvent方法怎么实现？
3、如果我想在BaseFragment定义方法怎么实现？

**Comment by JessYanCoding** [comment]
你要学会实现接口，朋友，https://mp.weixin.qq.com/s/Jwawa5C5MCH3qchsi3fc3A
