### ISSUE TITLE
你好，请问怎么才能添加自己的数据解析格式啊？

### ISSUE THREAD

**Issue by Wingge** [JessYanCoding/MVPArms#3]
比如，我的数据是这样的格式：
public class BaseResponse<T> {

```
private int code;
private String msg;
private T data;
```

}
，在amrs里怎么拦截，解析处理并自动封闭为entity啊？

**Comment by JessYanCoding** [comment]
Retrofit会自动把请求结果Convert成你指定的entity,如下面就是直接把结果转换为BaseResponse<List<NodeData>>并使用Observable包装好,我的demo中有请求和解析实例,具体用法请参阅Retrofit文档
```
@FormUrlEncoded
    @POST(Api.URL)
    Observable<BaseResponse<List<NodeData>>> getAllNodeData(@Field("param") String params);
```

**Comment by Wingge** [comment]
解决了，谢谢你~~ @JessYanCoding

**Comment by Wingge** [comment]
解决了，谢谢你~~
