### ISSUE TITLE
不懂混淆前务必注意将Java Bean,自定义组件添加进规则，什么意思，Java Bean

### ISSUE THREAD

**Issue by zjllh** [JessYanCoding/MVPArms#30]
1、不懂混淆前务必注意将Java Bean,自定义组件添加进规则，什么意思。
2、Java Bean是你写的一个class，还是指我自己写的实体类？那我该怎么添加进规则。我混淆不怎么懂，请大神您多包涵。

**Comment by JessYanCoding** [comment]
这个建议你百度一下
