### ISSUE TITLE
使用DialogFragment 内存泄漏

### ISSUE THREAD

**Issue by wangbang79408854** [JessYanCoding/MVPArms#304]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment
MvpArm版本  2.5.0

canary 版本 1.6.3

### Related Code:
```java
  
   cancelPayDialog.show(getSupportFragmentManager(),"cancel")
```

canary 报内存泄漏

AppManager.sAppManager
AppManager.mCurrentActivity

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/MVPArms/blob/master/arms/src/main/java/com/jess/arms/integration/ActivityLifecycle.java#L126   CurrentActivity 在 onPause 就会置空，你看看是否是其他问题引起的
