### ISSUE TITLE
configOkhttp 里修改超时时间不管用

### ISSUE THREAD

**Issue by 541954852** [JessYanCoding/MVPArms#305]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment

- [x] MVPArms Version: 
- [x] AndroidStudio Version: 
- [x] Gradle Plugin Version: 
- [x] Target Android Version: 
- [x] Device Model: 

### Related Code:
```java
   Interceptor interceptor=new Interceptor() {
                            @Override
                            public Response intercept(Chain chain) throws IOException {
                                Request request = chain.request();
                                chain.withConnectTimeout(1,TimeUnit.SECONDS);
                                chain.withReadTimeout(1,TimeUnit.SECONDS);
                                chain.withWriteTimeout(1,TimeUnit.SECONDS);
                                return chain.proceed(request);
                            }
                        };

```

### Bug Log:
```log


```

**Comment by JessYanCoding** [comment]
Interceptor 是 Okhttp 的 API 和 Arms 没什么关系
