### ISSUE TITLE
使用框架之后启动速度慢,这个有办法优化下吗

### ISSUE THREAD

**Issue by HelloDearWorld** [JessYanCoding/MVPArms#307]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment

- [x] MVPArms Version: 
- [x] AndroidStudio Version: 
- [x] Gradle Plugin Version: 
- [x] Target Android Version: 
- [x] Device Model: 

### Related Code:
```java
  

```

### Bug Log:
```log


```

**Comment by JessYanCoding** [comment]
有数据说明这是 框架 的问题吗

**Comment by HelloDearWorld** [comment]
> 有数据说明这是 框架 的问题吗

非常感谢你的回复,这个问题不存的,我应该及时关闭,经过验证release包确实不慢,我自己代码的问题

5. 第一次启动 app 时,冷启动会白屏很久,这并不是因为本框架导致的,是因为 Instant Run 在 Debug 模式下会在第一次启动时部署一些资源,如果签名打 Release 安装包则不会出现冷启动很慢的情况,所以不用担心影响用户体验.
