### ISSUE TITLE
2.5.0 Demo 里边有一个DemoService 继承了BaseService 里边就实例化了一个init 具体如果使用，wiki 也没用写，能否回复下如何使用的？

### ISSUE THREAD

**Issue by liuxuesong001** [JessYanCoding/MVPArms#308]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment

- [x] MVPArms Version: 
- [x] AndroidStudio Version: 
- [x] Gradle Plugin Version: 
- [x] Target Android Version: 
- [x] Device Model: 

### Related Code:
```java
  

```

### Bug Log:
```log


```

**Comment by JessYanCoding** [comment]
只要初始化后，就可以拿到  AppComponent 中的所有对象，不就想怎么用，都可以了
