### ISSUE TITLE
关于生命周期的bug

### ISSUE THREAD

**Issue by NerdAnonymous** [JessYanCoding/MVPArms#309]
Fragment在框架中，ButterKnife在onDestoryView中销毁View，然后RxLifecycle绑定Fragment的生命周期是FragmentEvent.onDestoryView,那么会出现问题，在出现一个Activity嵌套多个Fragment切换时（Fragment的initData中请求了网络），快速切换，然后退出Activity，Fragment销毁，这时的销毁顺序是ButterKnife解除绑定，View置空，然后RxLifecycle解绑，停止请求，这时候会走到RxUtils中applySchedulers的doFinally方法中的view.hideLoading()，如果Fragment实现的hideLoading并在其中使用到了相关View，这时候View是null，会出现异常，建议Fragment销毁顺序同步Activity，先进行RxLifecycle解绑，再进行ButterKnife解绑，这样就解决了这个问题

**Comment by JessYanCoding** [comment]
现在你可以暂时先将 Fragment 指定为 ButterKnife 解绑前停止任务

**Comment by NerdAnonymous** [comment]
@JessYanCoding 新版本的这个bug还没修复 是不

**Comment by RookieJay** [comment]
您好，我也是使用一个Activity嵌套多个Fragment出现这个控件空指针问题，请问下如何操作能在 ButterKnife 解绑前停止任务？

public void loadCoin() {
        mModel.personalCoin()
              .retryWhen(new RetryWithDelay(5, 3))
              .compose(RxLifecycleUtils.bindToLifecycle(mRootView))
              .compose(RxScheduler.Obs_io_main())
              .subscribe(new BaseWanObserver<WanAndroidResponse<Coin>>(mRootView) {
                  @Override
                  public void onSuccess(WanAndroidResponse<Coin> response) {
                      mRootView.showCoin(response.getData());
                  }
              });
    }
