### ISSUE TITLE
适配问题，App跳转到其他App之后，回调本App，本App字体变小

### ISSUE THREAD

**Issue by fendouwangzi** [JessYanCoding/MVPArms#315]
适配问题，App跳转到其他App之后，回调本App，本App字体变小

目前适配失败机型， pad型号华为M3青春版，分辨率为1920乘以1200，系统7.0

**Comment by JessYanCoding** [comment]
看这里 https://github.com/JessYanCoding/AndroidAutoSize/issues/13 ，有什么适配问题 issues 提到 AndroidAutoSize，不要提到 MVPArms
