### ISSUE TITLE
okhttp框架部分设备出现 SocketTimeOut 后 其他请求一直返回 SocketTimeOut

### ISSUE THREAD

**Issue by 258188170** [JessYanCoding/MVPArms#316]
这个问题在 okhttp 上一直是 open,我测试解决这个问题重新 new 一个 okhttpcient 对象可以,但是本框架配在全局,我能动态用新建的 okhttpclient 替换全局配置的吗

**Comment by JessYanCoding** [comment]
可以，但不建议这样做
