### ISSUE TITLE
框架中所依赖的okhttp3.11和as3.4存在冲突

### ISSUE THREAD

**Issue by bluetomcat** [JessYanCoding/MVPArms#317]
### Environment
- [x] MVPArms Version: 
- [x] AndroidStudio Version: 
- [x] Gradle Plugin Version: 

### Bug Description:
在android studio 3.4 中引入MVPArms后无法使用OKHttp相关包
具体表现:引用OKhttp相关包后编译器报红,但不影响项目编译运行

原因:MVPArms中使用的OKHttp3.11.0和android studio 3.4 存在冲突
解决:依赖MVPArms时剔除OKHttp相关,依赖其他OKHttp版本

### Others:
![image](https://user-images.githubusercontent.com/24225105/60780406-e3193580-a170-11e9-8fc7-003429f2d709.png)
![image](https://user-images.githubusercontent.com/24225105/60780421-fa582300-a170-11e9-80e4-d5cb43c03626.png)

**Comment by JessYanCoding** [comment]
好的，如果是版本问题的话，我后续会更新版本并发布新版本Arms。
