### ISSUE TITLE
mRootView aways nullPointException? how to solve it?

### ISSUE THREAD

**Issue by HelloDearWorld** [JessYanCoding/MVPArms#320]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment

- [x] MVPArms Version: 
- [x] AndroidStudio Version: 
- [x] Gradle Plugin Version: 
- [x] Target Android Version: 
- [x] Device Model: 

### Related Code:
```java
  

```

### Bug Log:
```log


```

**Comment by CAM1113** [comment]
没有代码或者日志么？
如果你在Activity里没有执行Dagger2的绑定代码会这样。
public void setupActivityComponent(@NonNull AppComponent appComponent) {
        DaggerMainComponent //如找不到该类,请编译一下项目
                .builder()
                .appComponent(appComponent)
                .view(this)
                .build()
                .inject(this);
    }

**Comment by TYUpya** [comment]
are you not Chinese?

**Comment by JessYanCoding** [comment]
May be an xml error
