### ISSUE TITLE
在VIVO手机中的启动问题

### ISSUE THREAD

**Issue by wushange** [JessYanCoding/MVPArms#321]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment

- [x] MVPArms Version: <2.5.2>
- [x] AndroidStudio Version: <3.4>
- [x] Gradle Plugin Version: <3.4.0>
- [x] Target Android Version: <28>
- [x] Device Model: <Vivo Y67A  Android6.0>

### Bug Description:

你好， 在测试中发现 使用arms框架的app 在退出应用后， 在手机的最近任务中点击app 不会回到app而是打开系统相册。 多次测试，arms2.5.2的demo也存在这个问题。不知道是哪里出错，也不确定是咱们框架的问题，能帮看一下吗 谢谢

### Related Code:
```java
  

```

### Bug Log:
```log


```

**Comment by wushange** [comment]
![录屏_20190719_133130](https://user-images.githubusercontent.com/8189991/61511881-bf84a380-aa2a-11e9-8d39-6c70aae4cb27.gif)
就像这样

**Comment by wushange** [comment]
简单发现了问题可能的原因  去掉canary-debug的引用就好了
`//    debugImplementation rootProject.ext.dependencies["canary-debug"]
//    releaseImplementation rootProject.ext.dependencies["canary-release"]
//    testImplementation rootProject.ext.dependencies["canary-release"]`
这是为什么呢？

**Comment by xichunjie** [comment]
我今天也遇到这个情况，是什么原因呢

**Comment by ruanbaojun1105** [comment]
打正式包还有这种问题吗？ @wushange

**Comment by wushange** [comment]
> 打正式包还有这种问题吗？ @wushange

正式包不会

**Comment by ruanbaojun1105** [comment]
那有什么影响呢

**Comment by JessYanCoding** [comment]
如果去掉 canary 的饮用就没问题了，那说明可能是 canary 影响到了 Activity 栈，打正式包没问题是因为，正式包不会饮用 canary
