### ISSUE TITLE
集成后app启动慢的问题？

### ISSUE THREAD

**Issue by KotlinLan** [JessYanCoding/MVPArms#326]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment

- [x] MVPArms Version: 
- [x] AndroidStudio Version: 
- [x] Gradle Plugin Version: 
- [x] Target Android Version: 
- [x] Device Model: 

### Bug Description:
未集成此框架之前，点击桌面app图标，app可以立马启动；集成后点击图标，需要等待至少3秒后才能启动app，看了issues，不止一个人有这样的问题。请问有办法处理吗，测试手机是三星S10+.

### Related Code:
```java
  

```

### Bug Log:
```log


```

**Comment by KotlinLan** [comment]
不好意思，是这边自己的问题。主题设置了windowDisablePreview为true导致的

**Comment by JessYanCoding** [comment]
。。。
