### ISSUE TITLE
Status code 200 回调 onFailure 方法是怎么回事？

### ISSUE THREAD

**Issue by DesignQu** [JessYanCoding/MVPArms#33]
我这有个登录接口
账号密码正确返回onResponse
密码错误返回到onFailure
但http的状态码都是200，不是应该都返回到onResponse吗？

**Comment by DesignQu** [comment]
01-05 14:43:31.958 32137-3229/com.ld.smb D/OkHttp: --> POST http://xxx?m=member&c=api&a=do_login http/1.1
01-05 14:43:31.958 32137-3229/com.ld.smb D/OkHttp: Content-Type: application/x-www-form-urlencoded
01-05 14:43:31.958 32137-3229/com.ld.smb D/OkHttp: Content-Length: 38
01-05 14:43:31.958 32137-3229/com.ld.smb D/OkHttp: username=18505126172&password=11111112
01-05 14:43:31.958 32137-3229/com.ld.smb D/OkHttp: --> END POST (38-byte body)
01-05 14:43:32.188 32137-3229/com.ld.smb D/OkHttp: <-- 200 OK http://xxxx/index.php?m=member&c=api&a=do_login (220ms)
01-05 14:43:32.188 32137-3229/com.ld.smb D/OkHttp: Server: nginx/1.6.2
01-05 14:43:32.188 32137-3229/com.ld.smb D/OkHttp: Date: Thu, 05 Jan 2017 06:43:31 GMT
01-05 14:43:32.188 32137-3229/com.ld.smb D/OkHttp: Content-Type: text/html; charset=utf-8
01-05 14:43:32.188 32137-3229/com.ld.smb D/OkHttp: Transfer-Encoding: chunked
01-05 14:43:32.188 32137-3229/com.ld.smb D/OkHttp: Connection: keep-alive
01-05 14:43:32.188 32137-3229/com.ld.smb D/OkHttp: X-Powered-By: PHP/5.5.21
01-05 14:43:32.188 32137-3229/com.ld.smb D/OkHttp: Vary: Accept-Encoding
01-05 14:43:32.188 32137-3229/com.ld.smb D/OkHttp: {"code":0,"info":"\u5bc6\u7801\u9519\u8bef","result":-5}
01-05 14:43:32.188 32137-3229/com.ld.smb D/OkHttp: <-- END HTTP (56-byte body)
01-05 14:43:32.188 32137-32137/com.ld.smb E/onFailure: onFailure

**Comment by DesignQu** [comment]
这是log

**Comment by JessYanCoding** [comment]
你这个不是issue,你可以加readme上的交流群沟通交流

**Comment by DesignQu** [comment]
谢谢

**Comment by LUCKYWUQI** [comment]
我clone 下来用studio 打开  一直在download  glide 包怎么也下不来  怎么办
