### ISSUE TITLE
activity和fragment共用presenter

### ISSUE THREAD

**Issue by Del-Gin** [JessYanCoding/MVPArms#331]
大神，请教一下
我有个activity和fragment，想共用一个presenter，该怎么处理？？

presenter应该是ActivityScope，但是activity和fragment对应的Component分别是ActivityScope和FragmentScope，他总是提示我may not reference bindings with different scopes。

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/MVPArms/issues/181

**Comment by Del-Gin** [comment]
这个我看了，我理解的这是一个activity使用两个presenter的解决方法。我回去再研究一下。
如果activity和fragment共用了一个presenter，那么activity和fragment持有的presenter是否为同一个？

**Comment by JessYanCoding** [comment]
可以用同一个 Presenter，但只是类是同一个，对象不是同一个，有时候不要纠结 ActivityScope，Scope 保证的是 Module 和 Component 的同步，也就是，如果 Component 的 Scope 和 Module 一样，就不会生成新的对象，也就是你 Fragment 的 Component 用 ActivityScope 也是可以的，但只要保证 Presenter 也是用的  ActivityScope 就可以了，达到的效果和用 FragmentScope 没有任何区别，自定义 Scope 没什么实际意义，就是为了在业务层好区分，但是在 Dagger 编辑器中和官方定义的 @Singleton 都是相同的处理逻辑，核心在于 Module 和 Component 是否是同一个 scope
