### ISSUE TITLE
autoLayout已经很久没更新了是否可以替换成autoSize

### ISSUE THREAD

**Issue by Followang** [JessYanCoding/MVPArms#335]
## Look at here

- → Did you conform to the [Rules](https://github.com/JessYanCoding/MVPArms/issues/150)?
- → Did you read the [Wiki](https://github.com/JessYanCoding/MVPArms/wiki) **Carefully**?
- → Did you search in Google?
- → Did you search in openned&closed Issues?
- → **Receive only bugs and suggestions**

### Environment

- [x] MVPArms Version: 
- [x] AndroidStudio Version: 
- [x] Gradle Plugin Version: 
- [x] Target Android Version: 
- [x] Device Model: 

### Related Code:
```java
  

```

### Bug Log:
```log


```

**Comment by JessYanCoding** [comment]
。。。兄弟，你多久没关注  MVPArms，MVPArms 去年就将 Demo 改为使用 Autosize  了，而且我还出了官方的替换步骤 [如何将旧项目从 AndroidAutoLayout 迁移至 AndroidAutoSize](https://github.com/JessYanCoding/AndroidAutoSize/issues/90)
