### ISSUE TITLE
dagger2更新问题

### ISSUE THREAD

**Issue by NerdAnonymous** [JessYanCoding/MVPArms#336]
dagger2出了dagger android了，框架是否考虑更新一波，减少接口...

**Comment by JessYanCoding** [comment]
daggerAndroid 需要自己在应用层自己对 AppComponent 做处理，框架层做不了这个处理，因为  daggerAndroid 使用 SubComponent 的方式，会和业务层的 Component 耦合，这个自己业务层自己做，框架层根本不知道你有哪些业务 Component

**Comment by NerdAnonymous** [comment]
哦 回头研究下
