### ISSUE TITLE
更新至rxjava3

### ISSUE THREAD

**Issue by yedajiang44** [JessYanCoding/MVPArms#356]
看了下提交记录，更新了第三方库版本，所以想问下能否再下一版更新至rxjava3

**Comment by JessYanCoding** [comment]
现在更新 rxjava3 不现实，大部分 Rxjava 扩展库都还没更新到 rxjava3，rxjava 可没有像 AndroidX
一样有 AndroidStudio 的支持，可以在编译时自动将所有依赖库的 Support 包替换成 Androidx，也就是你想把主工程更新到 Rxjava 3 要么做好工程中同时出现 Rxjava 3 和 Rxjava2 的准备，要么就自己将所有依赖的 Rxjava 扩展库改成 Rxjava 3，要么就报错

**Comment by yedajiang44** [comment]
确实是
