### ISSUE TITLE
dagger2支持的最低版本

### ISSUE THREAD

**Issue by a-cunmin** [JessYanCoding/MVPArms#36]
请问一下dagger2支持最低系统版本是哪个版本呢？百度都没找到呢。还有MVPArms支持api是15+的，我能不能换掉涉及到15+的第三方库呢，因为我想兼容到14+，

**Comment by JessYanCoding** [comment]
依赖的三方库好像大部分都支持14，你可以先改成14，将报错的三方库，剔除掉就可以了

**Comment by cunmin** [comment]
哦哦，谢谢啦！
