### ISSUE TITLE
AdapterViewPager中为什么这么写？

### ISSUE THREAD

**Issue by 464559332** [JessYanCoding/MVPArms#37]
请教一个问题AdapterViewPager中为什么这么写呢，切换不做任何保存立即销毁？我们一般都不重写这些方法。
    @Override
    public Parcelable saveState() {
        return null;
    }

    @Override
    public Object instantiateItem(ViewGroup container, int position) {
        Fragment f = (Fragment) super.instantiateItem(container, position);
        View view = f.getView();
        if (view != null)
            container.addView(view);
        return f;
    }

    @Override
    public void destroyItem(ViewGroup container, int position, Object object) {
        View view = list.get(position).getView();
        if (view != null)
            container.removeView(view);
    }

**Comment by JessYanCoding** [comment]
你好,这个类是之前其他项目复制过来了,我也没关注到这个点,并且这个框架的所有关于ui的东西,都不是我关注的点,所以我也不会用太多时间在上面

**Comment by 464559332** [comment]
好的，谢谢，架子搭的非常好，非常受益。
