### ISSUE TITLE
关于Contract里面的 Model,和View,

### ISSUE THREAD

**Issue by yubaokang** [JessYanCoding/MVPArms#38]
Contract 里面为什么只有View和Model的接口，google 官方架构是View和Presenter.
是否应该考虑Contract内包含了 View,Model，Presenter3个接口的定义呢？

**Comment by JessYanCoding** [comment]
不会考虑,官方的Demo才出来我就已经看过源码了,以我mvp使用一年以上的经验,presenter使用接口就是多余,至于为什么用久了就能体会,你也可以自己百度,用东西,不一定要跟随别人,根据自己的思路见解稍作改动用的称手习惯才是最好的

**Comment by yubaokang** [comment]
个人认为Contract的存在就是为了一目了然所有的接口逻辑，P就是处理业务逻辑的，你这里Contract只包含了View和Model,显然不能做到一目了然。Model这是数据的获取，P层的逻辑完全不能跟View层相呼应。个人觉得既然Contratc中包含了Model，也应该包含Presenter的接口，这样Contrat存在才有意义。

**Comment by JessYanCoding** [comment]
理论始终是理论,期待你使用你说的模式多开发几个项目再来交流
