### ISSUE TITLE
代码适合阅读学习，但是发现演示app的代码少一个接口 DaggerAppComponent

### ISSUE THREAD

**Issue by liuyatao** [JessYanCoding/MVPArms#4]
![qq 20161028161250](https://cloud.githubusercontent.com/assets/4133185/19799488/8cec02b2-9d29-11e6-897d-91ec000c6906.png)

**Comment by JessYanCoding** [comment]
这个是Dagger自动生成的类,如果缺失的话,把报错的地方注释了，在编译下项目，apt会自动生成相关的dagger类，这时在解除注释

**Comment by luocaca** [comment]
![image](https://user-images.githubusercontent.com/20178161/27986341-9ebc5108-6430-11e7-9069-2b70c3d5ef37.png)

![image](https://user-images.githubusercontent.com/20178161/27986344-aa4341e4-6430-11e7-8ac3-a831af911a91.png)

注释完后编译，会报另一个错。、。？
