### ISSUE TITLE
GlobeConfigModule 如何 在 WEApplication 之外进行修改？

### ISSUE THREAD

**Issue by pessonljxpd** [JessYanCoding/MVPArms#46]
我有一些 信息是需要根据用户的输入操作来 完成初始化的，但目前看到的GlobeConfigModule的配置只能是在WEApplication中，请问，怎么在其他地方修改这个呢？

**Comment by JessYanCoding** [comment]
@pessonljxpd GlobeConfigModule是全局的配置信息,必须在项目启动的时候确定所有配置信息,所以必须在Application中配置

**Comment by pessonljxpd** [comment]
我如果想 给 OkhttpClient 的 header 添加 Authorization，除了 在 application 中 之外，应该 在哪里去做呢？

**Comment by JessYanCoding** [comment]
可以在**Interceptor**中作统一处理,我项目里可以在GlobeConfigModule.globeHttpHandler#onHttpRequestBefore中做处理,具体请百度

**Comment by pessonljxpd** [comment]
恩，我之前就是在项目的 WEApplication中的GlobeConfigModule.globeHttpHandler#onHttpRequestBefore做的处理，但这个还是在WEApplication中的吧？ 其他地方获取不到这个呀？我技术比较菜，还在了解mvparm这个框架

**Comment by JessYanCoding** [comment]
@pessonljxpd 你的意思是这个header里的Authorization信息不是固定的,需要依赖于外部的数据做改变, **Retrofit** 可以在参数中传入@Header,具体请百度

**Comment by pessonljxpd** [comment]
额，明白了，太感谢了！
