### ISSUE TITLE
Rxjava升级了，框架要不要跟着升级

### ISSUE THREAD

**Issue by WooYu** [JessYanCoding/MVPArms#47]
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/rxjava.properties
	File1: C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\io.reactivex.rxjava2\rxjava\2.0.7\21734c0092a5d3c3ec99510e50c1ff76bdf0c65a\rxjava-2.0.7.jar
	File2: C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\io.reactivex\rxjava\1.2.7\138872ff3173fb7bee8b1d6303d6edb57d76599\rxjava-1.2.7.jar

其它依赖库中用的最新版本的Rxjava，项目运行报错了

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/MVPArms/wiki/Issues
