### ISSUE TITLE
无法clone项目到本地

### ISSUE THREAD

**Issue by david-2015** [JessYanCoding/MVPArms#48]
Jess:
你好，一直停留在 Gradle:Download https://jitpack.io/com/github/VictorAlbertos/RxCache/......，请问怎么解决，谢谢！
MVPArt，同样的问题

AS2.3   ，https://github.com/JessYanCoding/MVPArms.git

**Comment by JessYanCoding** [comment]
请翻墙

**Comment by david-2015** [comment]
谢谢。
忘记说前提了：修改的hosts , google 正常访问，之前已经试过github上的其他project没问题，试了试download整个项目打开，但builder的时候提示上面那个过不去。

**Comment by JessYanCoding** [comment]
As并不会用你的hosts所以还是要用工具翻墙

**Comment by david-2015** [comment]
谢谢，学习了，其他时候一直hosts人肉翻没问题，还真没留意AS
