### ISSUE TITLE
网络请求功能扩展

### ISSUE THREAD

**Issue by WooYu** [JessYanCoding/MVPArms#49]
可以扩展下网络请求吗？实现带进度条的上传和下载文件功能。

**Comment by JessYanCoding** [comment]
这个是关于retrofit及okhttp的扩展实现,百度搜索很多

**Comment by JessYanCoding** [comment]
刚刚看了下,大多数做法是自定义一个 **Interceptor**, 你将这个 **Interceptor**,在**WeApplication**中通过GlobeConfigModule.addInterceptor(),传进来就可以了,教程很多难度应该不大

**Comment by WooYu** [comment]
在你说的位置进行拦截，那不所有的请求都会被拦截了

**Comment by JessYanCoding** [comment]
@WooYu Okhttp的整个实现都建立在了,**Interceptor**上,它内部也是使用几个**Interceptor**对请求进行封装,请求服务器,返回数据,所以你使用**Interceptor**,并不一定要将所有请求拦截,如果不符合你的条件你不拦截也不处理就可以了,这并不会对后续的请求有什么影响,**Android**中的事件分发机制,也是使用了责任链模式,你不处理那就不拦截就可以了,不会对后面的事件有什么影响

**Comment by WooYu** [comment]
现在不知道如何将下载上传和其他请求区分开来，也就是不知道拦截的条件是什么


发自我的 iPhone

**Comment by JessYanCoding** [comment]
@WooYu 那我给你个意见,在 **Interceptor** 中可以拿到所有请求的header和参数,你可以在上传文件请求接口中添加一个用来区别其他请求接口的header,然后使用这个 **Interceptor** 判断是否含有这个 header 即可
