### ISSUE TITLE
代码clone下来导入android studio2.2.2 编译太慢，一直在编译中，，，

### ISSUE THREAD

**Issue by ml-bright** [JessYanCoding/MVPArms#5]
Gradle: resolve dependencies ':arms:_debug_Compile'

**Comment by JessYanCoding** [comment]
如果编译超过半个小时,可能不是编译慢,是gradle在下载一些第三方库,正好你网速不行或者需要翻墙

**Comment by ml-bright** [comment]
已使用shadowsocks翻墙成功，下载明显很快解决
