### ISSUE TITLE
Cannot get property 'android' on extra properties extension as it does not exist 

### ISSUE THREAD

**Issue by chenyy0708** [JessYanCoding/MVPArms#54]
![qq 20170405161238](https://cloud.githubusercontent.com/assets/16978940/24696079/cfe7f9ea-1a1a-11e7-834e-f33dcd7da176.png)
![qq 20170405161244](https://cloud.githubusercontent.com/assets/16978940/24696080/d0106308-1a1a-11e7-8653-f98d3e9e655e.png)
大神，请问导入arms报这个错误怎么解决

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/MVPArms/wiki#1.2
