### ISSUE TITLE
DaggerBaseComponent编译不过

### ISSUE THREAD

**Issue by wanwenxiu** [JessYanCoding/MVPArms#55]
是这样的，本来是直接compile 'me.jessyan:arms:1.2.4'，功能什么的都可以用。功能非常强大。在使用过程中，希望将每个activity的状态栏设置为透明的。就需要修改BaseActivty中的布局和内容。所以就是直接引用的compile project(':arms')。这样引用之后，编译DaggerBaseComponent通不过。Error:(42, 9) 错误: 找不到符号
符号:   变量 DaggerBaseComponent
位置: 类 BaseApplication

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/MVPArms/wiki/Issues

**Comment by wanwenxiu** [comment]
谢谢提醒。。现在是编译super.onCreate(savedInstanceState) 报空，不知道是什么原因？

**Comment by JessYanCoding** [comment]
这个你自己应该可以解决
