### ISSUE TITLE
能不能出一个不带dagger2的版本

### ISSUE THREAD

**Issue by liunewshine** [JessYanCoding/MVPArms#56]
感觉还不如直接new方便，而且让整个项目调用过程很模糊

**Comment by JessYanCoding** [comment]
没有,也不会考虑,不想用Dagger2你直接用google官方的MVP,Github搜索也一大把MVP+Rxjava的框架,这个框架的特色和其他MVP框架的差异化,就是Dagger2,其他功能都是根据这个架子衍生出来的,如果没有Dagger2那我和其他MVP框架就没什么大的区别,我也不喜欢重复建一些已经烂大街的轮子,仅仅使用Google官方MVP引入一些RxJava库,再写几个基类的框架,我想也没有开源的必要

**Comment by liunewshine** [comment]
了解
