### ISSUE TITLE
activity的view监听是直接实现OnClickListener就可以吗不知道我的为什么没有反应

### ISSUE THREAD

**Issue by appsw** [JessYanCoding/MVPArms#57]
MainActivity extends WEActivity<MainPresenter> implements MainContract.View,
        OnClickListener{  
@Override
    public void onClick(View view) {
       
      log.e（"没有","反应"）;
    }
}

**Comment by JessYanCoding** [comment]
你以前怎么使用OnClickListener现在就怎么使用,和框架没有关系

**Comment by Sum41forever** [comment]
你的View 没有setOncliclListener 没有任何回调。。。
