### ISSUE TITLE
加密问题！

### ISSUE THREAD

**Issue by mochengsheng** [JessYanCoding/MVPArms#59]
/**
     * app的全局配置信息封装进module(使用Dagger注入到需要配置信息的地方)
     * GlobeHttpHandler是在NetworkInterceptor中拦截数据
     * 如果想将请求参数加密,则必须在Interceptor中对参数进行处理,GlobeConfigModule.addInterceptor可以添加Interceptor
     *
     * @return
     */
    private Interceptor interceptor = new Interceptor() {
        @Override
        public Response intercept(Chain chain) throws IOException {
            return null;
        }
    };
这个Interceptor 要怎么处理？

**Comment by JessYanCoding** [comment]
GlobeHttpHandler有一个before 方法,可以拿到request,request里就有这个请求的header和请求参数等信息,你将request的参数解析出来,然后再加密后,request.newbuilder重新放进去,具体怎么操作request怎么解析,自己百度,我不可能手把手教你

**Comment by mochengsheng** [comment]
04-13 09:49:59.997 16628-16628/me.jessyan.mvparms.demo W/System.err: java.lang.IllegalArgumentException: Invalid % sequence at 105: �~���lI���ȻQ+��"�_Z�ЉI�huJ�Z�&�i��i)ǜ�7l�n)n�o}�m�C�(��Z-�ĵt[�:?�eB�z���=��<�ǃ{�^9)̙o��ڟ?�ʻ���Bǥ��%�JG:�ʱ.Un8Z5���������{蠴������	�
04-13 09:49:59.997 16628-16628/me.jessyan.mvparms.demo W/System.err: +U�L��K��l���l�D��;R������� �C�K�����`�U|�����
04-13 09:49:59.997 16628-16628/me.jessyan.mvparms.demo W/System.err:     at libcore.net.UriCodec.decode(UriCodec.java:169)
04-13 09:49:59.997 16628-16628/me.jessyan.mvparms.demo W/System.err:     at java.net.URLDecoder.decode(URLDecoder.java:60)
04-13 09:49:59.997 16628-16628/me.jessyan.mvparms.demo W/System.err:     at com.jess.arms.http.RequestIntercept.parseParams(RequestIntercept.java:106)
04-13 09:49:59.997 16628-16628/me.jessyan.mvparms.demo W/System.err:     at com.jess.arms.http.RequestIntercept.intercept(RequestIntercept.java:59)
04-13 09:49:59.997 16628-16628/me.jessyan.mvparms.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
04-13 09:49:59.997 16628-16628/me.jessyan.mvparms.demo W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
04-13 09:49:59.997 16628-16628/me.jessyan.mvparms.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
加密了，但是报错了Interceptor 报错

**Comment by JessYanCoding** [comment]
自己解决

**Comment by JessYanCoding** [comment]
在qq群上问

**Comment by mochengsheng** [comment]
好




发自网易邮箱大师
在2017年04月13日 10:18，JessYan 写道：

在qq群上问
