### ISSUE TITLE
源码分析有个疑问

### ISSUE THREAD

**Issue by ml-bright** [JessYanCoding/MVPArms#6]
BaseApplication中有如下方法：

`
public LinkedList<BaseActivity> mActivityList;

/**
     * 返回一个存储所有存在的activity的列表
     *
     * @return
     */
    public LinkedList<BaseActivity> getActivityList() {
        if (mActivityList == null) {
            mActivityList = new LinkedList<BaseActivity>();
        }
        return mActivityList;
    }
`

在BaseActivity中有：
`
//如果intent包含了此字段,并且为true说明不加入到list
        // 默认为false,如果不需要管理(比如不需要在退出所有activity(killAll)时，退出此activity就在intent加此字段为true)
        boolean isNotAdd = getIntent().getBooleanExtra(IS_NOT_ADD_ACTIVITY_LIST, false);
`

个人觉得要实现退出所有activity保留单个activity，做法是保存activity的实例这个做法可能会导致内存泄露，应该有更好的办法解决，希望楼主提供。

**Comment by JessYanCoding** [comment]
我将所有实例保存在一个list里面,是为了管理所有存在的Activity,并不只是局限于关闭所有activity,也可以用于其他功能,我每个Activity,onDestory都会从列表里remove掉,所以暂时还没遇到内存泄漏的问题,如果你遇到了,也可以提出来,我在针对这问题优化

**Comment by JessYanCoding** [comment]
@ml-bright https://github.com/JessYanCoding/MVPArms/wiki#3.11 新增AppManager管理所有Activity
