### ISSUE TITLE
框架更新

### ISSUE THREAD

**Issue by WooYu** [JessYanCoding/MVPArms#62]
v1.2.5更新挺大的，我的项目已经做了一大半。现在不更新框架有问题没？

**Comment by JessYanCoding** [comment]
v1.2.5属于日常更新,更新了一些三方库版本,替换Apt等,以前的版本,不更新也可以使用

**Comment by WooYu** [comment]
/**
     * 需要单独给RxCache提供缓存路径
     * 提供RxCache缓存地址
     */
    @Singleton
    @Provides
    @Named("RxCacheDirectory")
    File provideRxCacheDirectory(File cacheDir) {
        File cacheDirectory = new File(cacheDir, "RxCache");
        return DataHelper.makeDirs(cacheDirectory);
    }

@JessYanCoding 这个cacheDir从哪来的，没看明白。

**Comment by JessYanCoding** [comment]
在另外一个叫GlobeConfigModule类中提供,[详情见Wiki](https://github.com/JessYanCoding/MVPArms/wiki#3.1)

**Comment by JessYanCoding** [comment]
V1.5以下的版本,在WeApplication的getGlobeConfigModule中配置自定义参数
