### ISSUE TITLE
请教：2 次 subscribeOn 是为什么

### ISSUE THREAD

**Issue by tsunamilx** [JessYanCoding/MVPArms#65]
User 的那个例子中，UserPresenter.requestUsers() 里面用了 2 次 subscribeOn 不同的 Scheduler，请问是什么用意？

```java
        mModel.getUsers(lastUserId, isEvictCache)
              .subscribeOn(Schedulers.io()) // 第一次
              .doOnSubscribe(...)
              .subscribeOn(AndroidSchedulers.mainThread()) // 第二次
              .observeOn(AndroidSchedulers.mainThread())
              .doAfterTerminate(...)
              .compose(...)
              .subscribe(...);
```

**Comment by JessYanCoding** [comment]
百度rxjava的文章

**Comment by tsunamilx** [comment]
我看了几篇文章，其中一篇 （https://segmentfault.com/a/1190000004856071） 说道多次 subscribeOn 是无意义的，仅对第一次有效，可以多次使用 observeOn 来切换线程。

我也做了个下试验，多次 subscribeOn 确实是仅对第一次有效，所以这里是不是一个失误（虽然这个对 app 的运行无关紧要），还是有特别的用意？

我开这个 issue 不是来补盲的，确实对这里比较好奇，如有误解请指正。

**Comment by jp1017** [comment]
可以看看doOnSubscribe这货的使用

**Comment by JessYanCoding** [comment]
https://gank.io/post/560e15be2dca930e00da1083#toc_24

**Comment by tsunamilx** [comment]
多谢两位指正！然而我发现就算不加 subscribeOn(AndroidSchedulers.mainThread()) ，doOnSubscribe 也是执行在主线程，做了实验发现只要 doOnSubscribe 后面不跟 subscribeOn 貌似就是主线程。

**Comment by JessYanCoding** [comment]
那你试试在子线程执行subscribe

**Comment by tsunamilx** [comment]
哦，我的意思其实就是默认为当前的线程。不过显式的写明有助于代码理解。
再次感谢！

**Comment by JessYanCoding** [comment]
嗯,上面的文章也写的很清楚,默认为当前线程执行
