### ISSUE TITLE
接入Tinker，BaseApplication怎么处理 

### ISSUE THREAD

**Issue by Darksiderlyd** [JessYanCoding/MVPArms#66]
我想接入Tinker,BaseApplication该怎么处理

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/MVPArms/wiki#3.12

**Comment by Darksiderlyd** [comment]
谢谢 收到

**Comment by JessYanCoding** [comment]
你自定义个Application,参照BaseApplication使用AppDelegate

**Comment by Darksiderlyd** [comment]
嗯嗯 是不是就是在我自定义的Application里的生命周期方法调用APPDelegate相应的生命周期方法就可以了

**Comment by JessYanCoding** [comment]
对

**Comment by Darksiderlyd** [comment]
谢谢大神 我去试试

**Comment by JessYanCoding** [comment]
新更新的v1.5.2版本中加入了一个**App**接口,自定义的**Application**必须实现这个接口

**Comment by Darksiderlyd** [comment]
ok 我好好看看你写的文档 仔细研究下

**Comment by JessYanCoding** [comment]
👌
