### ISSUE TITLE
提一些小的建议

### ISSUE THREAD

**Issue by smuwjs** [JessYanCoding/MVPArms#67]
非常喜欢这套架构，提一些小小的建议。
1、Retrofit的Service命名规则容易与基本组件Service混淆。
2、把Presenter也写Interface，然后包进Contract里面，这样会不会更清晰。
3、去掉遗留的CompositeSubscription

**Comment by JessYanCoding** [comment]
Presenter是故意不写成接口的,平时使用中写成接口会显得多余不方便
Viwe层不一定是Activity或者Fragment,可能是dialog,所以Presenter并不一定是为Activity或者Fragment工作,使用RxLifecycle就不方便,所以CompositeSubscription就是为了应对这种状况

**Comment by smuwjs** [comment]
好咧，明白了，谢谢解答

**Comment by JessYanCoding** [comment]
至于那个命名规则,细致的东西确实没时间想,你可以看看我的提交记录,加上还有工作,所以只有合理分配时间
