### ISSUE TITLE
RefWatcher mRefWatcher的获取

### ISSUE THREAD

**Issue by lujianzhao** [JessYanCoding/MVPArms#68]
Demo里是在AppDelegate.Lifecycle里的回调里创建RefWatcher，如果想在Fragment里使用，应该怎么获取RefWatcher优雅一点呢？

**Comment by JessYanCoding** [comment]
之前因为某些原因删掉了这部分代码,后面,会增加ActivityDelegaet和FragmentDelegate,来提供给开发者,在基类中做自定义的逻辑

**Comment by JessYanCoding** [comment]
@lujianzhao 好了现在已经支持了,请看 [GlobalConfiguration](https://github.com/JessYanCoding/MVPArms/blob/master/app/src/main/java/me/jessyan/mvparms/demo/app/GlobalConfiguration.java)

**Comment by lujianzhao** [comment]
谢谢
