### ISSUE TITLE
BaseApplication 有一个错误 分析不出原因

### ISSUE THREAD

**Issue by YX-G** [JessYanCoding/MVPArms#69]
import com.jess.arms.di.component.DaggerAppComponent;

                 mAppComponent = DaggerAppComponent
                .builder()
                .appModule(new AppModule(this))////提供application
                .clientModule(new ClientModule())//用于提供okhttp和retrofit的单例
                .imageModule(new ImageModule())//图片加载框架默认使用glide
                .globeConfigModule(getGlobeConfigModule(this,modules))//全局配置
                .build();

加进来回报错求解

**Comment by JessYanCoding** [comment]
不晓得你什么意思
