### ISSUE TITLE
Demo首次运行，ImageLoad异常

### ISSUE THREAD

**Issue by xiaobailong24** [JessYanCoding/MVPArms#70]
demo首次运行时，当弹出请求权限的Dialog时， **GlideImageLoaderStrateg** 的 **loadImage()** 方法抛出异常。
```
    public void loadImage(Context ctx, GlideImageConfig config) {
        if (ctx == null) throw new IllegalStateException("Context is required");
        ......
    }
```
调试运行，发现 **UserItemHolder** 的 **setData()** 方法里
```
mAppComponent.appManager().getCurrentActivity() == null
```
如下图：
![issue](https://cloud.githubusercontent.com/assets/9431974/25415115/4244f2ec-2a68-11e7-8728-bf6e6e6018d5.png)

查看源码(**ActivityLifecycle.java**)，发现:
```
    @Override
    public void onActivityPaused(Activity activity) {
        if (mAppManager.getCurrentActivity() == activity) {
            mAppManager.setCurrentActivity(null);
        }
    }
```
此时 **mCurrentActivity**为null。

此处逻辑是否有问题，应该等用户授予权限后，再加载图片？

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/MVPArms/wiki/UpdateLog
