### ISSUE TITLE
parseBean

### ISSUE THREAD

**Issue by yangjinke** [JessYanCoding/MVPArms#72]
mModel.veryfyNewVersion()
                .retryWhen(new RetryWithDelay(3, 2))
                .subscribe(new ErrorHandleSubscriber<String>(mErrorHandler) {
                    @Override
                    public void onNext(String newVersionBean) {
                        Timber.tag(TAG).e(newVersionBean);
                    }
                });
我们的检测版本接口返回的json数据是用的单引号,且开头就是array，不能正常解析,所有我想直接拿到字符串先做处理再解析，这里泛型就是给的String，但是仍然报异常，
W/Result: ﻿[{'versionCode':30206,'versionName':'3.2.6','apkSize':'4382720'}] 
W/System.err: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 2 path $
W/System.err:     at com.google.gson.stream.JsonReader.nextString(JsonReader.java:825)
W/System.err:     at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:418)
.......
W/WEApplication: ------------>Expected a string but was BEGIN_ARRAY at line 1 column 2 path $
Disconnected from the target VM, address: 'localhost:8602', transport: 'socket'

**Comment by JessYanCoding** [comment]
怎么一会打开一会关闭issue?

**Comment by yangjinke** [comment]
现在打开了 ，先是问题没描述清楚

**Comment by yangjinke** [comment]
我想直接拿到返回结果为String

**Comment by xiaobailong24** [comment]
http://stackoverflow.com/questions/9598707/gson-throwing-expected-begin-object-but-was-begin-array
