### ISSUE TITLE
怎么动态修改baseUrl

### ISSUE THREAD

**Issue by shuigesuntao** [JessYanCoding/MVPArms#73]

**Comment by JessYanCoding** [comment]
@Get @post可以直接设置全路径

**Comment by shuigesuntao** [comment]
baseUrl是变量 没办法直接加在@GET 和@POST 需求是登录的时候可以手动输入IP 和 PORT  然后根据输入的这个地址去请求

**Comment by JessYanCoding** [comment]
使用全路径除了在@Get上给全路径外,还可以在参数中加入@Url注解,传入全路径,这输入retrofit的使用发发自己百度
