### ISSUE TITLE
关于 android:supportsRtl="true"

### ISSUE THREAD

**Issue by voler-JHL** [JessYanCoding/MVPArms#74]
这个属性应该由使用者添加才更灵活。由于历史遗留问题，我现在还不能开启这一属性。

**Comment by JessYanCoding** [comment]
Demo的Manifest你难道不能改吗?

**Comment by voler-JHL** [comment]
那你就非得加吗？不做阿语的用不到属性，做阿语的自己会加，你现在两个库上都加，我就都得下库，autolayout开始有，现在都不加了，你又不是做UI框架的，你跟着凑什么热闹，呵呵

**Comment by JessYanCoding** [comment]
完全不晓得你做什么,arms包才是我的框架,demo你自己不晓得改,有意见就不要用这个框架,不缺你一个

**Comment by DesignQu** [comment]
@voler-JHL 你是来秀智商吗？不用这个属性去掉不就行了

**Comment by longyuan5** [comment]
大兄弟这个属性你不懂，可以谷歌下嘛，实在不行百度下也是可以的。

**Comment by GloriousOnion** [comment]
@voler-JHL 真是智商捉急 就你这水平还做开发，是培训班出身么？

**Comment by wei3** [comment]
@GloriousOnion 对人对事，无关其他，培训班出身的也是想做开发的，请不要有偏见

**Comment by DesignQu** [comment]
现在4，5年以上基本都是培训班出来的，要么自学的，那时学校大部份还没有移动开发的课程

**Comment by GloriousOnion** [comment]
@wei3 我说的不涉及偏见，在我看来他这种人就不配编程。知道为什么好多维护开源项目停止维护开源项目么？就是对维护者横加指责，却对这些破坏规则的人沉默支持。Python前段时间一位核心开发者暂停维护，他发了一篇文章介绍原因，我找了中文的 建议你看一下 http://www.cnblogs.com/54Leo/p/6127783.html
@DesignQu 真不觉得自学的话能是这种像他那样问问题，自学一大特点就是去自己解决问题，也恰恰是培训班出身的大都不去深究问题，别提你认识的培训班的不那样，我说的是多数情况。

**Comment by DesignQu** [comment]
@GloriousOnion 那位可能也是太初级了，有些东西还没搞明白就来问

**Comment by JessYanCoding** [comment]
@GloriousOnion 感谢你的分享🙏,虽然我遭遇的处境没文章的作者这么严重,但你确实和文中提到的也基本吻合,如果大家不互相尊重,那开源社区风气会越来越糟糕,以后也没人愿意再来维护一个库,维护一个库比开源一个库累太多了

**Comment by CoderChoy** [comment]
我猜楼主指的是arms 包里面的manifest，这里加了android:supportsRtl="true"，依赖arms库的app也得这么设置，没必要的话第三方库最好不要加这个，个人见解，小白一枚，轻点喷

**Comment by JessYanCoding** [comment]
之前看的是 **app** 包里面的 **manifest** ,没注意 **arms** 包里面的 **manifest** , 刚刚看了下确实加了这个属性,但是 **manifest** 是提供有一个叫 **replace** 属性,不用下载远程库,直接在 **app** 里面就可以替换远程库的 **manifest** 属性, 其实这件事我一直不满意的是他的态度,其实这个也不叫 **bug**,只是说不能满足他的需求,但是我并不是收费为他服务,在不满足他个人需求的情况下,就恶言相对,这个换作是谁,也不会乐意

**Comment by CoderChoy** [comment]
@JessYanCoding 哈哈  态度确实有点问题，有事好好说嘛，看到那第二个回复我也是醉了
