### ISSUE TITLE
小问题遗漏：编译不过

### ISSUE THREAD

**Issue by abings** [JessYanCoding/MVPArms#77]
compile (rootProject.ext.dependencies["retrofit-adapter-rxjava"]){
        exclude module: 'rxjava'
    }

不应该是retrofit-adapter-rxjava2

**Comment by JessYanCoding** [comment]
你用的是v1.6.3的话就是用的这个库

**Comment by xiaobailong24** [comment]
就应该是retrofit-adapter-rxjava2啊。现在master已经是rxjava2了
