### ISSUE TITLE
请问大神如何解决RxCache解析泛型出问题的

### ISSUE THREAD

**Issue by pczhu** [JessYanCoding/MVPArms#78]
框架非常棒，RxCache也很棒，就是本地解析Response<List<ProjectBean>> 这种的时候，简直疯了。请问大神如何解决。

**Comment by JessYanCoding** [comment]
请看我之前写的[这篇文章](http://www.jianshu.com/p/b58ef6b0624b)的 **总结部分**

**Comment by pczhu** [comment]
@JessYanCoding 感谢指导，虽然不是用的原来的解决方案，但是差不多的思路，不过现在出现另一个问题，我希望正常加载时候使用缓存，一旦手动下拉刷新的时候，一次清除列表接口下所有页面的数据，所以在刷新部分用了EvictProvider（true）, 在加载更多部分用EvictDynamicKey（false）,但是发现EvictProvider只对刷新部分也就是第一页起作用，加载更多的时候依然取的本地缓存，逻辑上不应该是我调用了一次EvictProvider（true），该接口下缓存应该都被清除掉了么？请大神不吝赐教。

**Comment by JessYanCoding** [comment]
自己再去看我的文章,上面说了删除缓存并不只是EvictProvider(true),多看几篇再来问

**Comment by xiaobailong24** [comment]
@pczhu 也可以看看这篇
https://xiaobailong24.me/2017/04/14/Android-Retrofit-RxCache/

**Comment by pczhu** [comment]
@JessYanCoding  感谢您的回复。因为最近一直在研究RxCache, 所以您的文章我确实反复阅读多次，其中确实有

> EvictProvider 会删除当前接口下的所有缓存,比如你请求的是第一页的数据,它不仅会删除第一页的数据,还会把这个接口下其他分页的数据全删除

的说明，经过试验，有以下几种情况，同时传递
DynamicKey（1），EvictDynamicKey（true)  删除第一页数据
DynamicKey（1），EvictProvider(true)  仍然只删除了第一页数据
不传Dynamickey,只传EvictProvider(true) 仍然只删除了第一页数据（我们接口不传page默认第一页）
不传Dynamickey,只传EvictDynamicKey(true) 程序崩溃

今天有时间编译了源码，分析后修改了core-Action部分代码，重新测试，同时传递
DynamicKey（1），EvictDynamicKey（true)  删除第一页数据
DynamicKey（1），EvictProvider(true)  实现删除该接口下所有页面的数据
不传Dynamickey,只传EvictProvider(true) 删除了该接口下的所有页面的数据

通过修改部分代码实现了我的需求：下拉刷新清除该接口下的所有页面数据（不止是第一页），因为没有完全了解整个RxCache结构，只看了主干部分，所以不知道改动会有何影响，另外就是我确实不是很清楚如何在不改动的情况下删除一个分页接口下所有页面数据，我断点的结果就是只删除了第一页，请大神不吝赐教。

**Comment by JessYanCoding** [comment]
由于太久没看 **RxCache** 的源码了,所以具体怎么操作我就不说了,但是大致记得在传入 Evict(true) 时, **RxCache** 会在请求完网络后执行 **ProcessorProvidersBehaviour#clearKeyIfNeeded** 方法,删除对应的数据,你可以自己去看下相关的代码

**Comment by pczhu** [comment]
@JessYanCoding  是的。我改的就是clearKeyIfNeeded 后面匹配缓存key的部分。我会继续研究源码的，非常感谢您的指导。再次感谢。

**Comment by JessYanCoding** [comment]
既然改过那你应该,知道他之前是按什么规则删除的了
