### ISSUE TITLE
项目在Android6.0机子报错

### ISSUE THREAD

**Issue by zmin666** [JessYanCoding/MVPArms#79]
Couldn't opendir /data/app/vmdl532523354.tmp: No such file or directory
安装apk后无法打开. 问题很严重.

**Comment by JessYanCoding** [comment]
Demo不能打开？

**Comment by zmin666** [comment]
在小米4上demo可以打开, 但是问题是不能运行后打开, 非得手动点击图标打开...
我用4.4的模拟器测试是ok的.... 7.0的模拟器测试又是这样.
方便加个qq嘛. qq上比较好沟通~~ 谢谢

**Comment by JessYanCoding** [comment]
**README.md** 上有 QQ群
