### ISSUE TITLE
关于getCurrentActivity的问题

### ISSUE THREAD

**Issue by EightE** [JessYanCoding/MVPArms#80]
如果我在首个Activity内的initData方法里需要做跳转，这个时候getCurrentActivity是无法获取到当前activity的，看了一下你好像是在ActivityLifecycle的onActivityResumed里面才setCurrentActivity，而InitData是在onActivityCreated，还是我使用方法不正确？

**Comment by JessYanCoding** [comment]
是的,首个 **Activity** 是会有这样的问题,但是 **CurrentActivity** 在设计时就确定它可能会出现 **null** 的情况,所以 **AppManager** 的方法中,会判断为 **null** 的情况就加上  **NewInstance Flag**
