### ISSUE TITLE
为什么会在onTerminate中处理逻辑呢

### ISSUE THREAD

**Issue by TaitYoung** [JessYanCoding/MVPArms#81]
onTerminate 此方法，好像只在模拟器上有用，真机上不会调用的哦。
![image](https://cloud.githubusercontent.com/assets/6091057/25938394/9c7a8b50-3661-11e7-9c3e-b464a9360fcb.png)

**Comment by JessYanCoding** [comment]
是的,模拟器上我也不能不管

**Comment by JessYanCoding** [comment]
框架就是这样,每个地方都要考虑

**Comment by TaitYoung** [comment]
我的意思是，真机上好像就处理不了了？ 类似这种mApplication.unregisterActivityLifecycleCallbacks 代码还会执行吗

**Comment by TaitYoung** [comment]
ok ,了解，感谢。
