### ISSUE TITLE
如何设置状态栏背景，图标的改变，和文字的颜色

### ISSUE THREAD

**Issue by gnmmdk** [JessYanCoding/MVPArms#82]
1 在GlobalConfiguration实现

 @Override
    public void injectActivityLifecycle(Context context, List<Application.ActivityLifecycleCallbacks> lifecycles) {
        lifecycles.add(new Application.ActivityLifecycleCallbacks() {
            @Override
            public void onActivityCreated(Activity activity, Bundle savedInstanceState) {
                //这里全局给Activity设置toolbar和title,你想象力有多丰富,这里就有多强大,以前放到BaseActivity的操作都可以放到这里
                new ToolbarUtil(activity).setToolbar();
            }
2 ToolbarUtil类

public class ToolbarUtil {
    private Activity mActivity;
    public ToolbarUtil(Activity activity){
        this.mActivity = activity;
    }

    public void setToolbar(){
        //这里全局给Activity设置toolbar和title,你想象力有多丰富,这里就有多强大,以前放到BaseActivity的操作都可以放到这里
        if (findViewById(R.id.atb_toolbar) != null) {
            if (mActivity instanceof AppCompatActivity) {
                ((AppCompatActivity) mActivity).setSupportActionBar((Toolbar) findViewById(R.id.atb_toolbar));
                ((AppCompatActivity) mActivity).getSupportActionBar().setDisplayShowTitleEnabled(false);
            } else {
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                    mActivity.setActionBar((android.widget.Toolbar) findViewById(R.id.atb_toolbar));
                    mActivity.getActionBar().setDisplayShowTitleEnabled(false);
                }
            }
        }
        if (findViewById(R.id.tv_toolbar_title) != null) {
            ((TextView) findViewById(R.id.tv_toolbar_title)).setText(mActivity.getTitle());
        }
        if (findViewById(R.id.afl_toolbar_back) != null) {
            findViewById(R.id.afl_toolbar_back).setOnClickListener(v -> {
                mActivity.onBackPressed();
            });
        }
        if(mActivity instanceof IActivityToolbar) {
            IActivityToolbar mIToolBar = (IActivityToolbar) mActivity;           if(findViewById(R.id.atb_toolbar)!=null ){
                if(mIToolBar.getToolbarBackgroundColor()!=0) {    //设置状态栏颜色
                    findViewById(R.id.atb_toolbar).setBackgroundColor(mActivity.getResources().getColor(mIToolBar.getToolbarBackgroundColor()));

                }
            }
        }

    }

    @Nullable
    private View findViewById(@IdRes int id) {
        return mActivity.findViewById(id);
    }
}

3  IActivityToolbar接口

public interface IActivityToolbar {

    int getToolbarBackgroundColor();        //背景颜色

    int getToolbarTitileIcon();             //标题文字旁边的图标

    int getToolbarTitileColor();             //标题文字颜色

    int getToolbarackVisible();             //返回图标是否可见

    int getToolbarackIcon();          //设置返回图标

    int getToolbarRight1();            //右边图片按钮1

    int getToolbarRight2();             //右边图片按钮2 最右边的

    int getToolbarRight();               //右边文字

    int getToolbarRightColor();               //右边文字颜色

}

4 需要一个新的类继承BaseActivity并且实现IActivityToolbar
public abstract  class WisdomOneBaseActivity<P extends IPresenter> extends BaseActivity<P> implements IActivityToolbar {

    @Override
    public int getToolbarBackgroundColor() {
        return 0;
    }

    @Override
    public int getToolbarTitileIcon() {
        return 0;
    }

    @Override
    public int getToolbarTitileColor() {
        return 0;
    }

    @Override
    public int getToolbarackVisible() {
        return 0;
    }

    @Override
    public int getToolbarackIcon() {
        return 0;
    }

    @Override
    public int getToolbarRight1() {
        return 0;
    }

    @Override
    public int getToolbarRight2() {
        return 0;
    }

    @Override
    public int getToolbarRight() {
        return 0;
    }

    @Override
    public int getToolbarRightColor() {
        return 0;
    }
}

5 最后将原本继承BaseActivity的类改成继承WIsdomOneBaseActivity，然后需要更改颜色的话就在继承类那边实现getToolbarBackgroundColor()方法。
  @Override
    public int getToolbarBackgroundColor() {
        return R.color.white;
    }

**Comment by JessYanCoding** [comment]
well

**Comment by JessYanCoding** [comment]
给个建议,现在虽然你的 **Toolbar** 可定制化非常强大了, 但是接口方法也变得非常多,导致你不得不写一个抽象 **Activity** 作为父类,将这些接口默认实现,以避免子 **Activity** 实现一些非必需的接口, 所以我建议不用让接口自定义这么多样式, **Callbacks** 只用设置一些常用且必要的样式, 哪些复杂且少用的 **Toolbar** 样式就在当前 **Activity** 设置,这样就可以少写很多接口方法,解决方案都不可能是完美的,我们必须找到一个侧重点去平衡现有的一切

**Comment by JessYanCoding** [comment]
如果你确定要实现这么多复杂的自定义样式,我再给个建议,将这些样式封装到一个, **JavaBean** 中,里面有你需要的所有属性,这样子 **Activity** 只需要实现一个方法,将所有属性装入这个 **JavaBean** 并返回, **Callbacks** 只用调用这个方法拿到这个 **JavaBean** ,就可以根据里面的属性做对应的设置, 如果还要继续优化,那我建议这个 **JavaBean** 是 **Builder** 模式,这样就可以控制使用者必须传入某些必要的属性,又可以不断扩展

**Comment by xiaobailong24** [comment]
插一个外链：

白底黑字！Android浅色状态栏黑色字体模式
http://www.jianshu.com/p/7f5a9969be53
