### ISSUE TITLE
如何解决从Activity向Fragment传参的问题?

### ISSUE THREAD

**Issue by kkooff114** [JessYanCoding/MVPArms#84]
我想从Activity传一个`ArrayList<ResourceEntity>`到Fragment中

然后我常规性的在Fragment定义:
```
  public static ResourceFragment newInstance(ArrayList<ResourceEntity> list) {
        ResourceFragment fragment = new ResourceFragment();
        Bundle bundle = new Bundle();
        bundle.putParcelableArrayList("list", list);
        fragment.setArguments(bundle);
        return fragment;
    }
```

按照框架的设定, 我需要在`initData()`方法中进行初始化数据, 但是我Fragment中的数据源定义在他的presenter中(我一般将业务数据放到presenter里面):

```
public class ResourcePresenter extends BasePresenter<ResourceContract.View> {

    protected List<ResourceEntity> resourceList;
    ...
}
```

所以 我的目的就是**将Activity的数据传入Fragment的presenter中**
那现在有俩个问题:

1. `initData()`是在`onActivityCreated`中的, 无法获取到`Bundle`里面的数据
2. 如果我换做在`ResourceFragment fragment = new ResourceFragment(ArrayList<ResourceEntity> list)` 构造函数的时候传参, 这个时候Dagger还没有注入presenter, 所以presenter是null, 无法赋值.构造函数如下: 

```
public class ResourceFragment extends BaseFragment<ResourcePresenter> implements ResourceContract.View {
      public ResourceFragment(ArrayList<ResourceEntity> list) {
               mPresenter.resourceList = list;
      }
}

```

有什么好的方式解决Fragment传参的问题吗?

**Comment by JessYanCoding** [comment]
`initData` 不能获取到 **Bundle**  的数据? 你确定? 以你最上面的写法,在实例化 **Fragment** 时已经 ** setArguments(bundle)** ,那在 **onAttach** 里就已经可以拿到 **Bundle** 的数据了

**Comment by Sum41forever** [comment]
可以考虑用Android 架构组件 ViewModel
可以解决在同一个Activity下 Activity和fragment  ；fragment和Fragment之间的通信问题
[ViewModel官方文档](https://developer.android.com/topic/libraries/architecture/viewmodel.html)
