### ISSUE TITLE
执行gradlew assembleRelease命令报:app:transformClassesAndResourcesWithProguardForRelease

### ISSUE THREAD

**Issue by cocowobo** [JessYanCoding/MVPArms#85]
1.2017-05-15 下载的 2.0.1 压缩包,解压后直接导入Android Studio
2.什么都不修改,直接在terminal 命令台,执行gradlew assembleRelease
3.编译报出
>Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Job failed, see logs for details

4.百思不得其解,望指定迷津

**Comment by cocowobo** [comment]
1.此问题是自身问题
2.查看本框架wiki 中有对混淆使用的说明
3.demo的混淆需要将作者的混淆复制过去,
4.不要犯这样的错:认为所有混淆规则直接写在框架的混淆规则就可以了,编译那个项目,则混淆规则文件就需要在那个module项目下.

**Comment by JessYanCoding** [comment]
不错,问题自己解决
