### ISSUE TITLE
有一个问题，会出现空指针

### ISSUE THREAD

**Issue by Devin1102** [JessYanCoding/MVPArms#88]
手动调用BaseApplication里面的onTerminate方法的时候，出现空指针。
![image](https://cloud.githubusercontent.com/assets/14036184/26672216/f16d2656-46ea-11e7-9f34-4efb6022b96a.png)

**Comment by JessYanCoding** [comment]
这个方法是使用虚拟机时系统才会调用的,谁让你自己调了,你先百度下这个方法把

**Comment by JessYanCoding** [comment]
非空判断我已经加了,你记住不要主动去调用这个方法
