### ISSUE TITLE
Timber好在哪里，都不能跳转到代码

### ISSUE THREAD

**Issue by jp1017** [JessYanCoding/MVPArms#9]
可以尝试

KLog:  https://github.com/ZhaoKaiQiang/KLog
XLog:  https://github.com/elvishew/xLog

至于Logger就不推荐了，上面两个足够，xLog还能保存到文件

**Comment by JessYanCoding** [comment]
嗯,谢谢你的意见,这个可以按自己习惯定制这个框架,这项目不上传jcenter就是想让大家根据自己的需求改进,有意见也即时可以提出,我会一直维护改进此框架

**Comment by tianzhijiexian** [comment]
跳转代码是一个功能，timber是一个思路。很赞同作者的思路，支持一下。
