### ISSUE TITLE
为什么没在activity,fragment里面去注入present，而是用泛型

### ISSUE THREAD

**Issue by 4what2do** [JessYanCoding/MVPArms#90]

**Comment by JessYanCoding** [comment]
你自己看demo,没注入的话,我调presenter是会报空指针的,但是 **Demo** 确没报,正常运行,说明我是注入了的,只是你没看到

**Comment by 4what2do** [comment]
我看到了啊  你为啥没有选择在activtiy里去inject present 而是选择ActivityScope presenter

**Comment by JessYanCoding** [comment]
我就是在activity里注入的 presenter

**Comment by JessYanCoding** [comment]
你自己加qq群 301733278 ,在这里解释好累
