### ISSUE TITLE
DefaultAdapter

### ISSUE THREAD

**Issue by JacksonLi-LiBin** [JessYanCoding/MVPArms#92]
怎么封装，不同数据类型，多布局

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/MVPArms/issues/21

**Comment by JessYanCoding** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper
https://github.com/alibaba/vlayout
这种框架出名的都一大把

**Comment by JacksonLi-LiBin** [comment]
我说的是继承你的DefaultAdapter

**Comment by JessYanCoding** [comment]
我建议你使用以上框架,性能上和功能上比较强大一点
