### ISSUE TITLE
关于AutoLayout建议

### ISSUE THREAD

**Issue by daiwenbo88** [JessYanCoding/MVPArms#93]
我感觉AutoLayout 不应该融入到arms中 应该取决于 框架使用者是否使用

**Comment by JessYanCoding** [comment]
后期会在 **BaseActivity** 作出非必需使用 **AutoLayout** 的判断,不声明 **meta** 就不会转换 **AutoView**

**Comment by daiwenbo88** [comment]
感觉这个框架的学习成本很高  如果抛开RxJava  RxAndroid RxCache 。。。。等等  只突出MVPArms  中M-V-P 相信大家学习起来很轻松 莫要见笑哈 我是菜鸟一枚

**Comment by JessYanCoding** [comment]
我不会这样做的:
1. 同样的 **MVP** 框架太多了,数不胜数,如果只是为了学习 **MVP** 怎么使用, **Google** 官方的 **Sample** 就可以满足你的需求,而我这个框架主要教的是开发者怎么在实际的大型项目中和其他框架结合起来灵活的使用,说白了学会怎么使用 **MVP** ,并不会让你从小白变成大神,而学会我这里面的所有东西,不说成为大神但是也可以让开发者产生质的飞跃, **学习成本很高** 才说明可提升空间很大,前期学习的艰难才是成长的要素
2.**Dagger** 和 **Rxjava** 是我的核心,我抛弃了,那我这框架就失去了核心竞争力,完全被同质化了,我这个 **MVP** 框架的 **Star** 增长数是远超其他 **MVP** 框架的, 就是因为有这些技术作为基础
因为使用这个框架的人,并不是只是想简单学习下 **MVP** 怎么使用的,它们更愿意学习更多有价值的技术,得以在社会中更有竞争力,所以如果你愿意学习更多东西,有更多的成长空间,那欢迎使用,如果你确实觉得难以入手,那建议你使用比较纯粹易学的 **MVP** 库

**Comment by MissMyDearBear** [comment]
想和楼主交流学习一下，不知可否加个QQ

**Comment by JessYanCoding** [comment]
@MissMyDearBear qq群: 301733278

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/MVPArms/commit/70aa0f9e21c89b3937a932d5846f66c48bfbe274
