### ISSUE TITLE
小小的细节提示

### ISSUE THREAD

**Issue by cocowobo** [JessYanCoding/MVPArms#97]
AppManager-->
IS_NOT_ADD_ACTIVITY_LIST = "is_add_activity_list";//是否加入到activity的list，管理
IS_NOT_ADD_ACTIVITY_LIST 和"is_add_activity_list"不对应，按照作者的习惯应该是“is_not_add_activity_list"
如果作者手误请修改。

**Comment by JessYanCoding** [comment]
感谢指正,thx    https://github.com/JessYanCoding/MVPArms/commit/15ebfc7b1d4f45247e47fe5ef2ff9f88c0d2c20e
