### ISSUE TITLE
RxjavaRetrfit网络加载

### ISSUE THREAD

**Issue by aer874475222** [JessYanCoding/MVPArms#99]
如果有一个固定查询参数type=2，怎么加？

**Comment by aer874475222** [comment]
我看别人说用这个，我试了一下没效果 https://github.com/jkyeo/okhttp-basicparamsinterceptor

**Comment by JessYanCoding** [comment]
百度,不回答 **Retrofit** 的基本用法

**Comment by JessYanCoding** [comment]
可以加QQ群: 301733278 ,可以讨论
